genevalmag::Builder_code Class Reference
#include <Builder_code.h>
Public Member Functions
Builder_code (const string &path_folder_output, const string &name_file, const Attr_grammar &attribute_grammar, const Builder_plans &builder_plan, const Builder_visit_sequences &builder_v_seq)
virtual ~Builder_code ()
bool generate_code (const vector< string > &headers_file, const string path) const
Private Member Functions
void generate_header_file () const
void generate_footer_header () const
void generate_code_file (const vector< string > &headers_file) const
void generate_structs () const
void generate_constructor () const
void generate_methods () const
void generate_footer_code () const
string generate_print () const
string generate_translate () const
string generate_traverse () const
string generate_all_compute_eq () const
string generate_evaluator () const
string generate_eval_visiter () const
string generate_add_plan () const
string generate_add_plan_project () const
string generate_all_methods_eqs () const
string generate_initialize_rules () const
string generate_initialize_v_seq () const
string generate_initialize_context () const
string generate_initialize_plans () const
string generate_initialize_plan_proj () const
Private Attributes
const Attr_grammar & attr_grammar
References to the attribute grammar.
const Builder_plans & b_plans
References to all plans generates.
const Builder_visit_sequences & b_v_seq
References to all visit sequences generates.
string path_output
Defines the path where the files generated be saved.
string file_name
Defines the name of the files and the evaluator's class name.
Detailed Description
Definition at line 17 of file Builder_code.h.
Constructor & Destructor Documentation
genevalmag::Builder_code::Builder_code (const string & path_folder_output, const string & name_file, const Attr_grammar & attribute_grammar, const Builder_plans & builder_plan, const Builder_visit_sequences & builder_v_seq)
Contructor with the path and name of output files to be generated.
Parameters
path_folder_output
name_file
attribute_grammar
builder_plan
builder_v_seq
Returns
Contructor with the path and name of output files to be generated.
Definition at line 33 of file Builder_code.cpp.
genevalmag::Builder_code::~Builder_code () [virtual]
Destructor of the Builder_code.
Returns
Destructor of the Builder_code.
Definition at line 52 of file Builder_code.cpp.
Member Function Documentation
string genevalmag::Builder_code::generate_add_plan () const [private]
Generates and inserts the class method that insert a new plan.
Returns
Generates and inserts the class method that insert a new plan.
Definition at line 888 of file Builder_code.cpp.
References file_name.
Referenced by generate_methods().
string genevalmag::Builder_code::generate_add_plan_project () const [private]
Generates and inserts the class method that insert a new projected plan.
Returns
Generates and inserts the class method that insert a new projected plan.
Definition at line 903 of file Builder_code.cpp.
References file_name.
Referenced by generate_methods().
string genevalmag::Builder_code::generate_all_compute_eq () const [private]
Generates a method with a large switch with all equations, invoking in each case, the method that computes.
Returns
Generates a method with a large switch with all equations, invoking in each case, the method that computes.
Definition at line 806 of file Builder_code.cpp.
References attr_grammar, file_name, and genevalmag::Attr_grammar::get_count_eqs().
Referenced by generate_methods().
string genevalmag::Builder_code::generate_all_methods_eqs () const [private]
Generates one method for each equation in the grammar, that computes it's value.
Returns
Generates one method for each equation in the grammar, that computes it's value.
Definition at line 736 of file Builder_code.cpp.
References attr_grammar, utilities::cleaning_tabs(), genevalmag::generate_expr_text(), and genevalmag::Attr_grammar::get_rules().
Referenced by generate_methods().
bool genevalmag::Builder_code::generate_code (const vector< string > & headers_file, const string path) const
Generates the header and source code of the static evaluator of the grammar passed as parameter, with their evaluations plans, visit sequence and headers for uses user functions defined.
Parameters
headers_file
path
Returns
Generates the header and source code of the static evaluator of the grammar passed as parameter, alog with their evaluations plans, visit sequence and headers for uses user functions defined.
Definition at line 1096 of file Builder_code.cpp.
References utilities::copy_static_code(), generate_code_file(), generate_constructor(), generate_footer_code(), generate_footer_header(), generate_header_file(), generate_methods(), generate_structs(), and path_output.
void genevalmag::Builder_code::generate_code_file (const vector< string > & headers_file) const [private]
Create the source code file of the evaluator with some information.
Parameters
headers_file Create the source code file of the evaluator with some information.
Definition at line 111 of file Builder_code.cpp.
References file_name, and path_output.
Referenced by generate_code().
void genevalmag::Builder_code::generate_constructor () const [private]
Generates and inserts the evaluator class's constructor. With all initializations of Evaluation Plans, Evaluation Plans Project, Visit Sequences and Rules.
Definition at line 479 of file Builder_code.cpp.
References file_name, generate_initialize_context(), generate_initialize_plan_proj(), generate_initialize_plans(), generate_initialize_rules(), generate_initialize_v_seq(), and path_output.
Referenced by generate_code().
string genevalmag::Builder_code::generate_eval_visiter () const [private]
Generates the evaluator method, which following the visit sequences drawn, visit the nodes of the tree until computes it completely.
Returns
Generates the evaluator method, which following the visit sequences drawn, visit the nodes of the tree until computes it completely.
Definition at line 834 of file Builder_code.cpp.
References file_name.
Referenced by generate_methods().
string genevalmag::Builder_code::generate_evaluator () const [private]
Generates the evaluating method, which performs the method invocations to be computed all the attributes of the AST.
Returns
Generates the evaluating method, which performs the method invocations to be computed all the attributes of the AST.
Definition at line 866 of file Builder_code.cpp.
References b_plans, file_name, and genevalmag::Builder_plans::get_init_order().
Referenced by generate_methods().
void genevalmag::Builder_code::generate_footer_code () const [private]
Insert the source code file's footer of the evaluator.
Definition at line 210 of file Builder_code.cpp.
References file_name, and path_output.
Referenced by generate_code().
void genevalmag::Builder_code::generate_footer_header () const [private]
Insert the header file's footer of the evaluator.
Definition at line 162 of file Builder_code.cpp.
References file_name, and path_output.
Referenced by generate_code().
void genevalmag::Builder_code::generate_header_file () const [private]
Create the header file of the evaluator with some information.
Definition at line 59 of file Builder_code.cpp.
References file_name, and path_output.
Referenced by generate_code().
string genevalmag::Builder_code::generate_initialize_context () const [private]
Generates the initialization of all contexts rules uniques.
Returns
Generates the initialization of all contexts rules uniques.
Definition at line 330 of file Builder_code.cpp.
References b_plans, and genevalmag::Builder_plans::get_contexts_uniques().
Referenced by generate_constructor().
string genevalmag::Builder_code::generate_initialize_plan_proj () const [private]
Generates the initialization of all evaluation plan projects.
Returns
Generates the initialization of all evaluation plan projects.
Definition at line 388 of file Builder_code.cpp.
References b_plans, genevalmag::generate_key_plan(), and genevalmag::Builder_plans::get_plans_project().
Referenced by generate_constructor().
string genevalmag::Builder_code::generate_initialize_plans () const [private]
Generates the initialization of all evaluations plans.
Returns
Generates the initialization of all evaluations plans.
Definition at line 356 of file Builder_code.cpp.
References b_plans, genevalmag::generate_key_plan(), and genevalmag::Builder_plans::get_plans().
Referenced by generate_constructor().
string genevalmag::Builder_code::generate_initialize_rules () const [private]
Generates the initialization of all rules.
Returns
Generates the initialization of all rules.
Definition at line 435 of file Builder_code.cpp.
References attr_grammar, and genevalmag::Attr_grammar::get_rules().
Referenced by generate_constructor().
string genevalmag::Builder_code::generate_initialize_v_seq () const [private]
Generates the initialization of all visit sequences.
Returns
Generates the initialization of all visit sequences.
Definition at line 280 of file Builder_code.cpp.
References b_v_seq, and genevalmag::Builder_visit_sequences::get_visit_seq().
Referenced by generate_constructor().
void genevalmag::Builder_code::generate_methods () const [private]
Generates and inserts all class methods, includind traverse, visit evaluator and the main evaluator. This methods are based on the article by Wuu Yang.
Definition at line 919 of file Builder_code.cpp.
References file_name, generate_add_plan(), generate_add_plan_project(), generate_all_compute_eq(), generate_all_methods_eqs(), generate_eval_visiter(), generate_evaluator(), generate_print(), genevalmag::generate_return_index_context(), generate_translate(), generate_traverse(), and path_output.
Referenced by generate_code().
string genevalmag::Builder_code::generate_print () const [private]
Generates the print method, for show the all visit sequences.
Returns
Generates the print method, for show the all visit sequences.
Definition at line 509 of file Builder_code.cpp.
References file_name.
Referenced by generate_methods().
void genevalmag::Builder_code::generate_structs () const [private]
Generates and inserts all structs for represent each symbol of the grammar. With constructor and to_string methods.
For symbol S, with attrs s1 <syn> int, inserts:
 typedef struct Symbol_S: Node
 {
 int s0;
 Symbol_S(unsgned short r_id);
 string to_string() const;
 } S ;
Generates and inserts all structs for represent each symbol of the grammar. With constructor and to_string methods.
For symbol S, with attrs s1 <syn> int, inserts:
typedef struct Symbol_S: Node { int s0;
Symbol_S(unsgned short r_id);
string to_string() const; } S ;
Definition at line 966 of file Builder_code.cpp.
References attr_grammar, file_name, genevalmag::Attr_grammar::get_non_terminal_symbols(), and path_output.
Referenced by generate_code().
string genevalmag::Builder_code::generate_translate () const [private]
Generates the print method, for show the all visit sequences in a format more descriptive.
Returns
Generates the print method, for show the all visit sequences in a format more descriptive.
Definition at line 534 of file Builder_code.cpp.
References file_name.
Referenced by generate_methods().
string genevalmag::Builder_code::generate_traverse () const [private]
Generates the method that crosses the AST and sets the evaluation plan that corresponds to each node.
Returns
Generates the method that crosses the AST and sets the evaluation plan that corresponds to each node.
Definition at line 588 of file Builder_code.cpp.
References file_name.
Referenced by generate_methods().
Member Data Documentation
genevalmag::Builder_code::attr_grammar [private]
References to the attribute grammar.
Definition at line 21 of file Builder_code.h.
Referenced by generate_all_compute_eq(), generate_all_methods_eqs(), generate_initialize_rules(), and generate_structs().
genevalmag::Builder_code::b_plans [private]
References to all plans generates.
Definition at line 27 of file Builder_code.h.
Referenced by generate_evaluator(), generate_initialize_context(), generate_initialize_plan_proj(), and generate_initialize_plans().
genevalmag::Builder_code::b_v_seq [private]
References to all visit sequences generates.
Definition at line 33 of file Builder_code.h.
Referenced by generate_initialize_v_seq().
genevalmag::Builder_code::file_name [private]
Defines the name of the files and the evaluator's class name.
Definition at line 45 of file Builder_code.h.
Referenced by generate_add_plan(), generate_add_plan_project(), generate_all_compute_eq(), generate_code_file(), generate_constructor(), generate_eval_visiter(), generate_evaluator(), generate_footer_code(), generate_footer_header(), generate_header_file(), generate_methods(), generate_print(), generate_structs(), generate_translate(), and generate_traverse().
genevalmag::Builder_code::path_output [private]
Defines the path where the files generated be saved.
Definition at line 39 of file Builder_code.h.
Referenced by generate_code(), generate_code_file(), generate_constructor(), generate_footer_code(), generate_footer_header(), generate_header_file(), generate_methods(), and generate_structs().
The documentation for this class was generated from the following files:
include/Builders/Builder_code.h
src/Builders/Builder_code.cpp