genevalmag::Parser_AG Class Reference
#include <Parser_AG.h>
Public Member Functions
Parser_AG ()
~Parser_AG ()
const Attr_grammar & get_attr_grammar ()
bool parse_grammar (const string &path_file_input)
void save_grammar_file (const string path_output) const
Private Attributes
Attr_grammar attr_grammar
Internal structure of grammar.
Semantics_checks sem_check
Semantics control for grammar: Well define grammar.
Detailed Description
Definition at line 32 of file Parser_AG.h.
Constructor & Destructor Documentation
genevalmag::Parser_AG::Parser_AG ()
Constructor of Parser_AG.
Definition at line 33 of file Parser_AG.cpp.
genevalmag::Parser_AG::~Parser_AG ()
Destructor of Parser_AG.
Definition at line 39 of file Parser_AG.cpp.
Member Function Documentation
const Attr_grammar & genevalmag::Parser_AG::get_attr_grammar ()
Returns att_grammar of parser.
Returns
Returns att_grammar of parser.
Definition at line 46 of file Parser_AG.cpp.
References attr_grammar.
Referenced by genevalmag::Maglib::gen_evaluator().
bool genevalmag::Parser_AG::parse_grammar (const string & path_file_input)
This method invokes the method 'parse' of the library Spirit included in Boost. Returns true if could parse all the input.
Parameters
path_file_input
Returns
This method invokes the method 'parse' of the library Spitir included in Boost. Returns true if could parse all the input.
Definition at line 399 of file Parser_AG.cpp.
References attr_grammar, sem_check, genevalmag::set_attr_grammar(), and genevalmag::set_sem_check().
Referenced by genevalmag::Maglib::gen_evaluator().
void genevalmag::Parser_AG::save_grammar_file (const string path_output) const
This method saves all parsed string in a file. The file output is in argument path_output.
Parameters
path_output This method saves all parsed string in a file. The file output is in argument path_output.
Definition at line 447 of file Parser_AG.cpp.
References attr_grammar, genevalmag::FILE_GRAMMAR(), and genevalmag::Attr_grammar::to_string().
Referenced by genevalmag::Maglib::gen_evaluator().
Member Data Documentation
genevalmag::Parser_AG::attr_grammar [private]
Internal structure of grammar.
Definition at line 39 of file Parser_AG.h.
Referenced by get_attr_grammar(), parse_grammar(), and save_grammar_file().
genevalmag::Parser_AG::sem_check [private]
Semantics control for grammar: Well define grammar.
Definition at line 44 of file Parser_AG.h.
Referenced by parse_grammar().
The documentation for this class was generated from the following files:
include/Parser/Parser_AG.h
src/Parser/Parser_AG.cpp