genevalmag::Expr_node Class Reference
#include <Expr_node.h>
Public Member Functions
Expr_node ()
virtual ~Expr_node ()
const vector< Expression * > & get_childs () const
Expression * get_child (int index) const
void replace_child (int index, Expression *other)
void add_child (Expression *new_child)
virtual string to_string () const =0
Protected Attributes
vector< Expression * > childs
Childs's vector of node.
Detailed Description
Definition at line 19 of file Expr_node.h.
Constructor & Destructor Documentation
genevalmag::Expr_node::Expr_node ()
Constructor of Expr_node.
Returns
Definition at line 14 of file Expr_node.cpp.
genevalmag::Expr_node::~Expr_node () [virtual]
Destructor of Expr_node.
Returns
Destructor of Expr_node.
Definition at line 19 of file Expr_node.cpp.
References childs.
Member Function Documentation
void genevalmag::Expr_node::add_child (Expression * new_child)
Adds a child in Expr_function.
 Updates the parent of the child.
Parameters
new_child Adds a child in Expr_function. Updates the parent of the child.
Definition at line 57 of file Expr_node.cpp.
References childs, and genevalmag::Expression::set_parent().
Expression * genevalmag::Expr_node::get_child (int index) const
Returns the index-child of the Expr_function.
Parameters
index
Returns
Returns the index-child of the Expr_function.
Definition at line 38 of file Expr_node.cpp.
References childs.
Referenced by genevalmag::generate_expr_text().
const vector< Expression * > & genevalmag::Expr_node::get_childs () const
Returns the vector with all children of the Expr_function.
Returns
Returns the vector with all children of the Expr_function.
Definition at line 30 of file Expr_node.cpp.
References childs.
Referenced by genevalmag::Expr_function::copy(), and genevalmag::generate_expr_text().
void genevalmag::Expr_node::replace_child (int index, Expression * other)
Replaces index-child of the Expr_function with other.
 Updates the parent of the child.
Parameters
index
other Replaces index-child of the Expr_function with other. Updates the parent of the child.
Definition at line 47 of file Expr_node.cpp.
References childs, and genevalmag::Expression::set_parent().
virtual string genevalmag::Expr_node::to_string () const [pure virtual]
Generate and return a string reprensentation of an Expr_node.
Returns
Implements genevalmag::Expression.
Implemented in genevalmag::Expr_function.
Member Data Documentation
genevalmag::Expr_node::childs [protected]
Childs's vector of node.
Definition at line 26 of file Expr_node.h.
Referenced by add_child(), genevalmag::Expr_function::copy(), get_child(), get_childs(), replace_child(), genevalmag::Expr_function::to_string(), and ~Expr_node().
The documentation for this class was generated from the following files:
include/Expression_tree/Expr_node.h
src/Expression_tree/Expr_node.cpp