genevalmag::Expr_instance Class Reference
#include <Expr_instance.h>
Public Member Functions
Expr_instance ()
Expr_instance (const Expr_instance &other)
virtual ~Expr_instance ()
Expr_instance & operator= (const Expr_instance &other)
const Attribute * get_attr () const
unsigned short get_num () const
const Symbol * get_symb () const
void set_attr (const Attribute *attr)
void set_num (unsigned short num)
void set_symb (const Symbol *symb)
string to_string () const
bool equals_without_index (const Expr_instance *other) const
string key () const
Private Member Functions
void copy (const Expr_instance &other)
void destroy ()
Private Attributes
const Symbol * i_symb
Symbol of Expr_instance.
unsigned short i_num
Syntax index of the instance.
const Attribute * i_attr
Attribute of Expr_instance.
Detailed Description
Definition at line 20 of file Expr_instance.h.
Constructor & Destructor Documentation
genevalmag::Expr_instance::Expr_instance ()
Constructor empty of Expr_instance.
Returns
Constructor empty of Expr_instance.
Definition at line 25 of file Expr_instance.cpp.
genevalmag::Expr_instance::Expr_instance (const Expr_instance & other)
Constructor copy of Expr_instance.
Parameters
other
Returns
Constructor copy of Expr_instance.
Definition at line 35 of file Expr_instance.cpp.
References copy().
genevalmag::Expr_instance::~Expr_instance () [virtual]
Destructor of Expr_instance.
Returns
Destructor of Expr_instance.
Definition at line 47 of file Expr_instance.cpp.
References destroy().
Member Function Documentation
void genevalmag::Expr_instance::copy (const Expr_instance & other) [private]
Method of copy the Expr_instance, STL-like C++.
Parameters
other Method of copy the Expr_instance, STL-like C++.
Definition at line 76 of file Expr_instance.cpp.
References genevalmag::Expression::conflict, get_attr(), genevalmag::Expression::get_conflict(), get_num(), genevalmag::Expression::get_parent(), get_symb(), genevalmag::Expression::get_type_synthetized(), i_attr, i_num, i_symb, genevalmag::Expression::parent, and genevalmag::Expression::type_synthetized.
Referenced by Expr_instance(), and operator=().
void genevalmag::Expr_instance::destroy () [private]
Method destroy Expr_instance, STL-like C++.
Definition at line 89 of file Expr_instance.cpp.
References i_attr, and i_symb.
Referenced by operator=(), and ~Expr_instance().
bool genevalmag::Expr_instance::equals_without_index (const Expr_instance * other) const
Compares the Expr_instance with other.
 Respects Symbol and attribute.
Parameters
other
Returns
Compares the Expr_instance with other. Respects Symbol and attribute.
Definition at line 172 of file Expr_instance.cpp.
References get_attr(), genevalmag::Attribute::get_name(), genevalmag::Symbol::get_name(), get_symb(), i_attr, and i_symb.
const Attribute * genevalmag::Expr_instance::get_attr () const
Returns the attribute pointer of the Expr_instance.
Returns
Returns the attribute pointer of the Expr_instance.
Definition at line 98 of file Expr_instance.cpp.
References i_attr.
Referenced by copy(), genevalmag::create_instance_node(), equals_without_index(), genevalmag::Builder_visit_sequences::gen_visit_seq(), genevalmag::generate_expr_text(), genevalmag::Builder_plans::generates_topological_order(), genevalmag::Attr_grammar::get_index_eq_with_context(), genevalmag::save_attr_ins(), and genevalmag::save_rvalue().
unsigned short genevalmag::Expr_instance::get_num () const
Returns the number of the Expr_instance.
Returns
Returns the number of the Expr_instance.
Definition at line 106 of file Expr_instance.cpp.
References i_num.
Referenced by copy(), genevalmag::Builder_visit_sequences::gen_visit_seq(), genevalmag::generate_expr_text(), genevalmag::Attr_grammar::get_index_eq_with_context(), and utilities::project_graph().
const Symbol * genevalmag::Expr_instance::get_symb () const
Returns the symbol pointer of the Expr_instance.
Returns
Returns the symbol pointer of the Expr_instance.
Definition at line 114 of file Expr_instance.cpp.
References i_symb.
Referenced by copy(), equals_without_index(), genevalmag::Builder_visit_sequences::gen_visit_seq(), genevalmag::generate_expr_text(), genevalmag::Builder_plans::generates_topological_order(), utilities::project_graph(), genevalmag::save_attr_ins(), and genevalmag::save_index_ins().
string genevalmag::Expr_instance::key () const
Generates and returns the string key that identifies an Expr_instance definitely.
 Result= <symbol><number><attribute>
 Ex: E0valor
Returns
Generate and return the string key that identifies an Expr_instance definitely.
Result= <symbol><number><attribute>
Ex: E0valor
Definition at line 192 of file Expr_instance.cpp.
References genevalmag::Attribute::get_name(), genevalmag::Symbol::get_name(), i_attr, i_num, and i_symb.
Expr_instance & genevalmag::Expr_instance::operator= (const Expr_instance & other)
Operator assign(=) of Expr_instance.
Parameters
other
Returns
Operator assign(=) of Expr_instance.
Definition at line 63 of file Expr_instance.cpp.
References copy(), and destroy().
void genevalmag::Expr_instance::set_attr (const Attribute * attr)
Sets the attribute pointer of the Expr_instance.
Parameters
attr Sets the attribute pointer of the Expr_instance.
Definition at line 122 of file Expr_instance.cpp.
References i_attr.
Referenced by genevalmag::Builder_graphs::compute_attr_vertex(), and genevalmag::save_attr_ins().
void genevalmag::Expr_instance::set_num (unsigned short num)
Sets the number of the Expr_instance.
Parameters
num Sets the number of the Expr_instance.
Definition at line 130 of file Expr_instance.cpp.
References i_num.
Referenced by genevalmag::Builder_graphs::compute_attr_vertex(), and genevalmag::save_index_ins().
void genevalmag::Expr_instance::set_symb (const Symbol * symb)
Sets the symbol pointer of the Expr_instance.
Parameters
symb Sets the symbol pointer of the Expr_instance.
Definition at line 138 of file Expr_instance.cpp.
References i_symb.
Referenced by genevalmag::Builder_graphs::compute_attr_vertex(), and genevalmag::create_instance().
string genevalmag::Expr_instance::to_string () const [virtual]
Generates and returns a string reprensentation of a Expr_instance.
 Result= <symbol>`[`<number>`].`<attribute>
 Ex: E[0].valor
Returns
Generate and return a string reprensentation of a Expr_instance.
Result= <symbol>`[`<number>`].`<attribute>
Ex: E[0].valor
Implements genevalmag::Expr_leaf.
Definition at line 150 of file Expr_instance.cpp.
References genevalmag::Attribute::get_name(), genevalmag::Symbol::get_name(), i_attr, i_num, and i_symb.
Referenced by genevalmag::save_rvalue().
Member Data Documentation
genevalmag::Expr_instance::i_attr [private]
Attribute of Expr_instance.
Definition at line 37 of file Expr_instance.h.
Referenced by copy(), destroy(), equals_without_index(), get_attr(), key(), set_attr(), and to_string().
genevalmag::Expr_instance::i_num [private]
Syntax index of the instance.
Definition at line 32 of file Expr_instance.h.
Referenced by copy(), get_num(), key(), set_num(), and to_string().
genevalmag::Expr_instance::i_symb [private]
Symbol of Expr_instance.
Definition at line 27 of file Expr_instance.h.
Referenced by copy(), destroy(), equals_without_index(), get_symb(), key(), set_symb(), and to_string().
The documentation for this class was generated from the following files:
include/Expression_tree/Expr_instance.h
src/Expression_tree/Expr_instance.cpp