genevalmag Namespace Reference
Classes
class Attr_grammar
class Attribute
class Equation
class Function
class Rule
class Sort
class Symbol
class Builder_code
struct vertex_data_t
class Builder_graphs
struct c_rule
struct k_w
struct i_w
struct k_plan
struct k_p_project
class Builder_plans
class Builder_visit_sequences
class Expr_function
class Expr_instance
class Expr_leaf
class Expr_literal
class Expr_node
class Expression
class Maglib
class Parser_AG
class Semantics_checks
struct cycle_detector
struct skip_parser
struct attritute_grammar
struct decl_attribute
Typedefs
typedef adjacency_list< hash_setS, vecS, directedS, property_vertex_dp > Graph
typedef Graph::vertex_descriptor Vertex
typedef vector< unsigned short > Order_eval_eq
typedef vector< unsigned short > Order_rule
typedef struct genevalmag::c_rule Context_rule
typedef struct genevalmag::k_w Key_work_list
typedef struct genevalmag::i_w Item_work
typedef struct genevalmag::k_plan Key_plan
typedef struct genevalmag::k_p_project Key_plan_project
typedef vector< int > Visit_seq
typedef char char_t
typedef file_iterator< char_t > iterator_f
typedef position_iterator< iterator_f > iterator_t
Enumerations
enum type_attr { k_inherit,
k_synthetize
 }
enum oper_mode { k_prefix,
k_infix,
k_postfix
 }
enum oper_assoc { k_left,
k_right,
k_non_assoc
 }
enum symbol_type { k_terminal,
k_non_terminal
 }
enum literal_type {
k_int,
k_float,
k_char,
k_string,
k_bool
 }
Functions
const bool IS_OPERATOR (true)
void set_attr_grammar (Attr_grammar *at_grammar)
void set_sem_check (Semantics_checks *s_check)
void create_sort (const iterator_t str, const iterator_t end)
void inic_func (const iterator_t str, const iterator_t end)
void add_function (const iterator_t str, const iterator_t end)
void save_name_func (const iterator_t str, const iterator_t end)
void save_domain_func (const iterator_t str, const iterator_t end)
void save_image_func (const iterator_t str, const iterator_t end)
void add_operator (const iterator_t str, const iterator_t end)
void save_mode_op (const iterator_t str, const iterator_t end)
void save_prec_op (int const prec)
void save_assoc_op (const iterator_t str, const iterator_t end)
void add_attribute (const iterator_t str, const iterator_t end)
void save_sort_attr (const iterator_t str, const iterator_t end)
void save_type_attr (const iterator_t str, const iterator_t end)
void save_member_list_attr (const iterator_t str, const iterator_t end)
void create_attributes (const iterator_t str, const iterator_t end)
void create_new_non_terminal (const iterator_t str, const iterator_t end)
void create_new_terminal (const iterator_t str, const iterator_t end)
void create_rule (const iterator_t str, const iterator_t end)
void save_right_side_rule (const iterator_t str, const iterator_t end)
void create_abbreviated_rule (const iterator_t str, const iterator_t end)
void save_rule (const iterator_t str, const iterator_t end)
void create_instance (const iterator_t str, const iterator_t end)
void save_index_ins (int const index)
void save_attr_ins (const iterator_t str, const iterator_t end)
void create_lit_number (const iterator_t str, const iterator_t end)
void create_lit_ch (const iterator_t ch, const iterator_t end)
void create_lit_str (const iterator_t str, const iterator_t end)
void create_bool (const iterator_t str, const iterator_t end)
void create_function (const iterator_t str, const iterator_t end)
void create_operator (const iterator_t str, const iterator_t end)
void create_equation (const iterator_t str, const iterator_t end)
void save_rvalue (const iterator_t str, const iterator_t end)
void push_mark (char name)
void create_literal_node (const iterator_t str, const iterator_t end)
void create_instance_node (const iterator_t str, const iterator_t end)
void create_func_node (const iterator_t str, const iterator_t end)
void create_root_infix_node (const iterator_t str, const iterator_t end)
void create_root_function_node (const iterator_t str, const iterator_t end)
void create_root_postfix_node (const iterator_t str, const iterator_t end)
void create_root_prefix_node (const iterator_t str, const iterator_t end)
void check_well_defined (const iterator_t str, const iterator_t end)
void increment_level (char name)
void decrement_level (char name)
template<class K , class T >
const bool add (const T &elem, map< K, T > &map_elem)
template<class K , class T >
const string to_string_map (const map< K, T > &map_elem)
const bool belong (const Symbol &symb, const string &expr_attrs)
template<class T >
string write_vector_with_inic (string &text_buffer, const string name_vec, const size_t index, const vector< T > &vec, const string type_vec, const string type_array)
string generate_key_plan (string &text, const string &n_key, const int &num_key, const Key_plan &k_p)
string generate_return_index_context ()
string generate_expr_text (const Expression *node, const Rule &rule)
const string PATH_OUTPUT_GRAPHS (`graphs/`)
const string PATH_OUTPUT_DP (`1_DP_graphs/`)
const string PATH_OUTPUT_DOWN (`2_DOWN_graphs/`)
const string PATH_OUTPUT_DCG (`3_DCG_graphs/`)
const string PATH_OUTPUT_ADP (`4_ADP_graphs/`)
const string PATH_OUTPUT_CYCLIC (`CYCLIC_graphs/`)
const string FILE_DP_GRAPH (`_dp_graph`)
const string FILE_DOWN_GRAPH (`_down_graph`)
const string FILE_DCG_GRAPH (`_dcg_graph`)
const string FILE_ADP_GRAPH (`_adp_graph`)
const string FILE_ADP_SUBGRAPH_CYCLIC (`_adp_subgraph_with_cyclic`)
const string PATH_OUT_PLAN (`plans/`)
const string PATH_OUT_PLAN_PROJECT (`plans_project/`)
void purge_plan_with (const Rule &rule, const Order_eval_eq &order_eq, Order_eval_eq &purged_order)
bool defined_work (const vector< Item_work > &list, const Item_work &item_work)
unsigned short return_index_vec (const Order_eval_eq &order, vector< Order_eval_eq > &vec)
const unsigned short LEAVE (0)
bool ins_attr_computed (const Expr_instance *ins, const vector< Expr_instance > &vec)
void get_inherits_of (const Symbol *symb, const vector< Expr_instance > &computed, vector< Expr_instance > &rec_child)
bool belong_it (const map< Key_plan, unsigned short >::const_iterator it, const vector< map< Key_plan, unsigned short >::const_iterator > &vec)
void merge_vec (const vector< map< Key_plan, unsigned short >::const_iterator > &vec_source, vector< map< Key_plan, unsigned short >::const_iterator > &vec_targed)
void merge_vec_without_plan (const vector< map< Key_plan, unsigned short >::const_iterator > &vec_source, vector< map< Key_plan, unsigned short >::const_iterator > &vec_targed, const map< Key_plan, unsigned short >::const_iterator &plan)
void plan_family_computed (const vector< map< Key_plan, unsigned short >::const_iterator > &plans_computed, vector< unsigned short > &visit_seq_computed)
const string DEFAULT_PATH (`./out_maggen/`)
const string DEFAULT_FILE_NAME (`mag_eval`)
const string DEFAULT_INPUT_FILE (`/tmp/.input_maggen_default`)
double timeval_diff (struct timeval *a, struct timeval *b)
bool check_file_exist (const string &strFilename)
bool check_name (const string &strFilename)
void show_help_information ()
bool parse_parameters (int argc, char *argv[], string &path_input_file, string &path_folder_output, string &name_library, vector< string > &headers)
const string FILE_GRAMMAR (`Grammar_mag.log`)
std::ostream & operator<< (std::ostream &out, file_position const &lc)
int swap_root_child (Expr_function **old_root, int i_new_root)
int swap_root_grandson (Expr_function **old_root)
void warshall_algorithm (const unsigned int size, bool *matrix_plain)
int get_index (string name_symb, vector< string > non_term)
bool check_eq_defines_it (const Symbol *symb, const int index, const Attribute *attr, const map< unsigned short, Equation > eqs)
Variables
vector< Equation * > index_access_eq
Attr_grammar * attr_grammar
Semantics_checks * sem_check
Function * current_func
struct genevalmag::decl_attribute * new_attrs
Rule * current_rule
Expr_instance * current_instance
Expr_literal * current_literal
Expr_function * current_ast_function
Equation * current_eq
vector< Expression * > stack_node
vector< Expr_node * > stack_inner_node
Typedef Documentation
typedef char genevalmag::char_t
Type definitions to report parsing errors, showing row and column.
Definition at line 27 of file Parser_AG.h.
typedef struct genevalmag::c_rule genevalmag::Context_rule
This struct represent a Context_rule, that is a father rule and the context of rule.
typedef adjacency_list<hash_setS, vecS, directedS, property_vertex_dp> genevalmag::Graph
Definition at line 35 of file Builder_graphs.h.
typedef struct genevalmag::i_w genevalmag::Item_work
This struct represents an Item work, that is an Key_work_list and an equations order evaluation.
typedef file_iterator<char_t> genevalmag::iterator_f
Definition at line 28 of file Parser_AG.h.
typedef position_iterator<iterator_f> genevalmag::iterator_t
Definition at line 29 of file Parser_AG.h.
typedef struct genevalmag::k_plan genevalmag::Key_plan
This structs represent a Key_plan, that is an id and an equations order evaluation.
typedef struct genevalmag::k_p_project genevalmag::Key_plan_project
This struct represent a Key_plan_project, that is a Key_plan, the symbol and ocurrence, by which project.
typedef struct genevalmag::k_w genevalmag::Key_work_list
This struct represents a Key_work_list, that is a father rule and id-rule of the current rule.
typedef vector< unsigned short > genevalmag::Order_eval_eq
Vector for order of equation. Each number represent an equation.
Definition at line 28 of file Builder_plans.h.
typedef vector< unsigned short > genevalmag::Order_rule
Vector that represents the inferior context of rule. Each number represent a rule.
Definition at line 34 of file Builder_plans.h.
typedef Graph::vertex_descriptor genevalmag::Vertex
Definition at line 38 of file Builder_graphs.h.
typedef vector<int> genevalmag::Visit_seq
Where: item > 0 represent to visit to this rule number. item == 0 represent to leave. item < 0 represent to compute this equation number.
Definition at line 28 of file Builder_visit_sequences.h.
Enumeration Type Documentation
enum genevalmag::literal_type
Type of basics literals.
Enumerator:
k_int
k_float
k_char
k_string
k_bool
Definition at line 20 of file Expr_literal.h.
enum genevalmag::oper_assoc
Enumeration of operation's associative modes.
Enumerator:
k_left
k_right
k_non_assoc
Definition at line 33 of file Function.h.
enum genevalmag::oper_mode
Enumeration of operation's mode.
Enumerator:
k_prefix
k_infix
k_postfix
Definition at line 23 of file Function.h.
enum genevalmag::symbol_type
Enumeration of symbol's type.
Enumerator:
k_terminal
k_non_terminal
Definition at line 23 of file Symbol.h.
enum genevalmag::type_attr
Enumeration of the attribute's type: Inherit or Synthetize.
Enumerator:
k_inherit
k_synthetize
Definition at line 20 of file Attribute.h.
Function Documentation
template<class K , class T > const bool genevalmag::add (const T & elem, map< K, T > & map_elem) [inline]
Operation template that insert an object type T in the parameter map.
Returns true if insert succesfully. In other case, return false.
Definition at line 42 of file Attr_grammar.cpp.
void genevalmag::add_attribute (const iterator_t str, const iterator_t end)
Methods and functions for parse Attribute class.
Definition at line 161 of file Semantics_actions.cpp.
References genevalmag::decl_attribute::d_member_symbol, genevalmag::decl_attribute::d_mod_type, genevalmag::decl_attribute::d_names, k_synthetize, and new_attrs.
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::add_function (const iterator_t str, const iterator_t end)
Definition at line 104 of file Semantics_actions.cpp.
References genevalmag::Attr_grammar::add_function(), attr_grammar, current_func, and genevalmag::Function::to_string().
Referenced by add_operator(), and genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::add_operator (const iterator_t str, const iterator_t end)
Methods and functions for parse Operator.
Definition at line 135 of file Semantics_actions.cpp.
References add_function(), current_func, IS_OPERATOR(), and genevalmag::Function::set_is_operator().
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
const bool genevalmag::belong (const Symbol & symb, const string & expr_attrs)
Interprets the expression of sets and returns true if the symbol belongs to that set.
Definition at line 94 of file Attr_grammar.cpp.
References genevalmag::Symbol::get_name().
Referenced by genevalmag::Attr_grammar::load_attributes().
bool genevalmag::belong_it (const map< Key_plan, unsigned short >::const_iterator it, const vector< map< Key_plan, unsigned short >::const_iterator > & vec)
Returns true if the iterator belongs to the vector passed as parameter.
Definition at line 78 of file Builder_visit_sequences.cpp.
Referenced by genevalmag::Builder_visit_sequences::gen_visit_seq(), merge_vec(), and merge_vec_without_plan().
bool genevalmag::check_eq_defines_it (const Symbol * symb, const int index, const Attribute * attr, const map< unsigned short, Equation > eqs)
Checks if exist an equation that define the instance formed with the parameters.
Definition at line 469 of file Semantics_checks.cpp.
References genevalmag::Attribute::equals(), and genevalmag::Symbol::equals().
Referenced by genevalmag::Semantics_checks::check_well_defined_AG().
bool genevalmag::check_file_exist (const string & strFilename)
Definition at line 116 of file maggen.cpp.
Referenced by parse_parameters().
bool genevalmag::check_name (const string & strFilename)
Definition at line 128 of file maggen.cpp.
Referenced by parse_parameters().
void genevalmag::check_well_defined (const iterator_t str, const iterator_t end)
Definition at line 654 of file Semantics_actions.cpp.
References attr_grammar, genevalmag::Semantics_checks::check_all_defined_non_terminal(), genevalmag::Semantics_checks::check_reachability(), genevalmag::Semantics_checks::check_well_defined_AG(), genevalmag::Attr_grammar::get_initial_symb(), genevalmag::Attr_grammar::get_non_terminal_symbols(), genevalmag::Attr_grammar::get_rules(), and sem_check.
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::create_abbreviated_rule (const iterator_t str, const iterator_t end)
Definition at line 253 of file Semantics_actions.cpp.
References current_rule, genevalmag::Rule::get_left_symbol(), and genevalmag::Rule::set_left_symbol().
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::create_attributes (const iterator_t str, const iterator_t end)
Definition at line 204 of file Semantics_actions.cpp.
References genevalmag::Attr_grammar::add_attribute(), attr_grammar, genevalmag::decl_attribute::d_member_symbol, genevalmag::decl_attribute::d_mod_type, genevalmag::decl_attribute::d_names, genevalmag::decl_attribute::d_sort_type, new_attrs, genevalmag::Attr_grammar::return_sort(), genevalmag::Attribute::set_member_symbol(), genevalmag::Attribute::set_mod_type(), genevalmag::Attribute::set_name(), and genevalmag::Attribute::set_sort_type().
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::create_bool (const iterator_t str, const iterator_t end)
Definition at line 361 of file Semantics_actions.cpp.
References current_literal, k_bool, genevalmag::Expr_literal::set_type(), genevalmag::Expression::set_type_synthetized(), and genevalmag::Expr_literal::set_value().
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::create_equation (const iterator_t str, const iterator_t end)
Definition at line 385 of file Semantics_actions.cpp.
References current_eq, current_instance, and genevalmag::Equation::set_l_value().
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::create_func_node (const iterator_t str, const iterator_t end)
Definition at line 459 of file Semantics_actions.cpp.
References current_ast_function, current_func, genevalmag::Semantics_checks::get_index_syntax_order(), genevalmag::Semantics_checks::get_precedence_level(), genevalmag::Semantics_checks::increment_index_syntax_order(), sem_check, genevalmag::Expr_function::set_function(), genevalmag::Expr_function::set_precedence_level(), genevalmag::Expr_function::set_syntax_order(), and stack_inner_node.
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::create_function (const iterator_t str, const iterator_t end)
Definition at line 373 of file Semantics_actions.cpp.
References current_func, and save_name_func().
Referenced by create_operator(), and genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::create_instance (const iterator_t str, const iterator_t end)
Methods and functions for parse Equation class of Rule.
Definition at line 268 of file Semantics_actions.cpp.
References attr_grammar, genevalmag::Rule::belongs_non_terminal(), utilities::cleaning_tabs(), current_instance, current_rule, genevalmag::Attr_grammar::get_symbol(), genevalmag::Expr_instance::set_symb(), and genevalmag::Rule::to_string_not_eqs().
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::create_instance_node (const iterator_t str, const iterator_t end)
Definition at line 450 of file Semantics_actions.cpp.
References current_instance, genevalmag::Expr_instance::get_attr(), genevalmag::Sort::get_name(), genevalmag::Attribute::get_sort_type(), genevalmag::Expression::set_type_synthetized(), and stack_node.
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::create_lit_ch (const iterator_t ch, const iterator_t end)
Definition at line 333 of file Semantics_actions.cpp.
References current_literal, k_char, genevalmag::Expr_literal::set_type(), genevalmag::Expression::set_type_synthetized(), and genevalmag::Expr_literal::set_value().
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::create_lit_number (const iterator_t str, const iterator_t end)
Definition at line 309 of file Semantics_actions.cpp.
References current_literal, k_float, k_int, genevalmag::Expr_literal::set_type(), genevalmag::Expression::set_type_synthetized(), and genevalmag::Expr_literal::set_value().
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::create_lit_str (const iterator_t str, const iterator_t end)
Definition at line 347 of file Semantics_actions.cpp.
References current_literal, k_string, genevalmag::Expr_literal::set_type(), genevalmag::Expression::set_type_synthetized(), and genevalmag::Expr_literal::set_value().
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::create_literal_node (const iterator_t str, const iterator_t end)
Creation expression nodes.
Definition at line 443 of file Semantics_actions.cpp.
References current_literal, and stack_node.
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::create_new_non_terminal (const iterator_t str, const iterator_t end)
Methods and functions for parse Symbol class.
Definition at line 223 of file Semantics_actions.cpp.
References genevalmag::Attr_grammar::add_symbol(), attr_grammar, and k_non_terminal.
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::create_new_terminal (const iterator_t str, const iterator_t end)
Definition at line 230 of file Semantics_actions.cpp.
References genevalmag::Attr_grammar::add_symbol(), attr_grammar, and k_terminal.
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::create_operator (const iterator_t str, const iterator_t end)
Definition at line 379 of file Semantics_actions.cpp.
References create_function(), current_func, IS_OPERATOR(), and genevalmag::Function::set_is_operator().
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::create_root_function_node (const iterator_t str, const iterator_t end)
Definition at line 524 of file Semantics_actions.cpp.
References attr_grammar, genevalmag::Attr_grammar::get_function(), stack_inner_node, and stack_node.
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::create_root_infix_node (const iterator_t str, const iterator_t end)
Definition at line 477 of file Semantics_actions.cpp.
References attr_grammar, genevalmag::Semantics_checks::correct_precedence(), genevalmag::Attr_grammar::get_function(), sem_check, stack_inner_node, and stack_node.
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::create_root_postfix_node (const iterator_t str, const iterator_t end)
Definition at line 574 of file Semantics_actions.cpp.
References attr_grammar, genevalmag::Semantics_checks::correct_precedence(), genevalmag::Attr_grammar::get_function(), sem_check, stack_inner_node, and stack_node.
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::create_root_prefix_node (const iterator_t str, const iterator_t end)
Definition at line 614 of file Semantics_actions.cpp.
References attr_grammar, genevalmag::Semantics_checks::correct_precedence(), genevalmag::Attr_grammar::get_function(), sem_check, stack_inner_node, and stack_node.
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::create_rule (const iterator_t str, const iterator_t end)
Methods and functions for parse Rule class.
Definition at line 240 of file Semantics_actions.cpp.
References attr_grammar, current_rule, genevalmag::Attr_grammar::get_symbol(), and genevalmag::Rule::set_left_symbol().
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::create_sort (const iterator_t str, const iterator_t end)
Methods and functions for parse Sort class.
Definition at line 85 of file Semantics_actions.cpp.
References genevalmag::Attr_grammar::add_sort(), attr_grammar, and genevalmag::Sort::to_string().
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::decrement_level (char name)
Definition at line 668 of file Semantics_actions.cpp.
References genevalmag::Semantics_checks::decrement_precedence_level(), and sem_check.
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
const string genevalmag::DEFAULT_FILE_NAME (`mag_eval`)
Default name of the files generated by the library.
Referenced by main().
const string genevalmag::DEFAULT_INPUT_FILE (`/tmp/.input_maggen_default`)
Default input file.
Referenced by main().
const string genevalmag::DEFAULT_PATH (`./out_maggen/`)
Default output path of the generation code.
Referenced by main().
bool genevalmag::defined_work (const vector< Item_work > & list, const Item_work & item_work)
Searchs in the list the item work that passed as parameter, if it find return true, otherwise false.
Definition at line 338 of file Builder_plans.cpp.
Referenced by genevalmag::Builder_plans::generate_plans().
const string genevalmag::FILE_ADP_GRAPH (`_adp_graph`)
Referenced by genevalmag::Builder_graphs::save_adp_graphs().
const string genevalmag::FILE_ADP_SUBGRAPH_CYCLIC (`_adp_subgraph_with_cyclic`)
Referenced by genevalmag::Builder_graphs::save_cyclic_graphs().
const string genevalmag::FILE_DCG_GRAPH (`_dcg_graph`)
Referenced by genevalmag::Builder_graphs::save_dcg_graphs().
const string genevalmag::FILE_DOWN_GRAPH (`_down_graph`)
Referenced by genevalmag::Builder_graphs::save_down_graphs().
const string genevalmag::FILE_DP_GRAPH (`_dp_graph`)
Referenced by genevalmag::Builder_graphs::save_dp_graphs().
const string genevalmag::FILE_GRAMMAR (`Grammar_mag.log`)
Referenced by genevalmag::Parser_AG::save_grammar_file().
string genevalmag::generate_expr_text (const Expression * node, const Rule & rule)
Generates the plain text of a equation of this rule.
Definition at line 643 of file Builder_code.cpp.
References genevalmag::Symbol::equals(), genevalmag::Expr_instance::get_attr(), genevalmag::Expr_node::get_child(), genevalmag::Expr_node::get_childs(), genevalmag::Expr_function::get_function(), genevalmag::Rule::get_left_symbol(), genevalmag::Attribute::get_name(), genevalmag::Symbol::get_name(), genevalmag::Function::get_name(), genevalmag::Rule::get_non_terminals_right_side(), genevalmag::Expr_instance::get_num(), genevalmag::Expr_instance::get_symb(), genevalmag::Expr_function::is_infix(), genevalmag::Function::is_operator(), genevalmag::Expr_function::is_postfix(), genevalmag::Expr_function::is_prefix(), and genevalmag::Expr_literal::to_string().
Referenced by genevalmag::Builder_code::generate_all_methods_eqs().
string genevalmag::generate_key_plan (string & text, const string & n_key, const int & num_key, const Key_plan & k_p)
Generate a key plan with the parameters.
Definition at line 306 of file Builder_code.cpp.
References genevalmag::k_plan::id_plan, and genevalmag::k_plan::plan.
Referenced by genevalmag::Builder_code::generate_initialize_plan_proj(), and genevalmag::Builder_code::generate_initialize_plans().
string genevalmag::generate_return_index_context ()
Generates the return_index_context method, for get the index of a context rule.
Definition at line 569 of file Builder_code.cpp.
Referenced by genevalmag::Builder_code::generate_methods().
int genevalmag::get_index (string name_symb, vector< string > non_term)
Returns the index in the vector of the symbol with these name.
Definition at line 387 of file Semantics_checks.cpp.
Referenced by genevalmag::Semantics_checks::check_reachability().
void genevalmag::get_inherits_of (const Symbol * symb, const vector< Expr_instance > & computed, vector< Expr_instance > & rec_child)
Obtains the instances of inherit attributes that this symbol.
Definition at line 61 of file Builder_visit_sequences.cpp.
Referenced by genevalmag::Builder_visit_sequences::gen_visit_seq().
void genevalmag::increment_level (char name)
Definition at line 663 of file Semantics_actions.cpp.
References genevalmag::Semantics_checks::increment_precedence_level(), and sem_check.
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::inic_func (const iterator_t str, const iterator_t end)
Methods and functions for parse Function.
Definition at line 98 of file Semantics_actions.cpp.
References current_func.
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
bool genevalmag::ins_attr_computed (const Expr_instance * ins, const vector< Expr_instance > & vec)
Searches this instance on the list passed as parameter. If found the instance return true.
Definition at line 46 of file Builder_visit_sequences.cpp.
Referenced by genevalmag::Builder_visit_sequences::gen_visit_seq().
const bool genevalmag::IS_OPERATOR (true)
This constant is used for set a function on operator.
Referenced by add_operator(), and create_operator().
const unsigned short genevalmag::LEAVE (0)
Referenced by genevalmag::Builder_visit_sequences::gen_visit_seq().
void genevalmag::merge_vec (const vector< map< Key_plan, unsigned short >::const_iterator > & vec_source, vector< map< Key_plan, unsigned short >::const_iterator > & vec_targed)
Merge two vector in the vec_target argument.
Definition at line 93 of file Builder_visit_sequences.cpp.
References belong_it().
Referenced by genevalmag::Builder_visit_sequences::gen_visit_seq(), and genevalmag::Builder_visit_sequences::generate_visit_sequences().
void genevalmag::merge_vec_without_plan (const vector< map< Key_plan, unsigned short >::const_iterator > & vec_source, vector< map< Key_plan, unsigned short >::const_iterator > & vec_targed, const map< Key_plan, unsigned short >::const_iterator & plan)
Merge two vector in the vec_target argument without the iterator passed as parameter.
Definition at line 117 of file Builder_visit_sequences.cpp.
References belong_it().
Referenced by genevalmag::Builder_visit_sequences::gen_visit_seq().
std::ostream& genevalmag::operator<< (std::ostream & out, file_position const & lc)
Our error reporting parsers
Definition at line 54 of file Parser_AG.cpp.
bool genevalmag::parse_parameters (int argc, char * argv[], string & path_input_file, string & path_folder_output, string & name_library, vector< string > & headers)
maggen [OPTIONS] where OPTIONS include: -f file Define the input file of the tool. Othercase, uses the standart input (cin). -i header Including header '.h' or '.hpp' file for resolve externs variables in generated code. -fo folder Defines the folder output for output generated information. Othercase, uses `./out_maggen/`. -o name Defines the names files generated tool. Otherwise, uses `mag_eval`. -h Show this help message.
Definition at line 165 of file maggen.cpp.
References check_file_exist(), check_name(), and show_help_information().
Referenced by main().
const string genevalmag::PATH_OUT_PLAN (`plans/`)
Defaults path to saves evaluation plans y their projections.
Referenced by genevalmag::Builder_plans::save_all_plans().
const string genevalmag::PATH_OUT_PLAN_PROJECT (`plans_project/`)
Referenced by genevalmag::Builder_plans::save_all_plans_project().
const string genevalmag::PATH_OUTPUT_ADP (`4_ADP_graphs/`)
Referenced by genevalmag::Builder_graphs::save_adp_graphs().
const string genevalmag::PATH_OUTPUT_CYCLIC (`CYCLIC_graphs/`)
Referenced by genevalmag::Builder_graphs::save_cyclic_graphs().
const string genevalmag::PATH_OUTPUT_DCG (`3_DCG_graphs/`)
Referenced by genevalmag::Builder_graphs::save_dcg_graphs().
const string genevalmag::PATH_OUTPUT_DOWN (`2_DOWN_graphs/`)
Referenced by genevalmag::Builder_graphs::save_down_graphs().
const string genevalmag::PATH_OUTPUT_DP (`1_DP_graphs/`)
Referenced by genevalmag::Builder_graphs::save_dp_graphs().
const string genevalmag::PATH_OUTPUT_GRAPHS (`graphs/`)
Referenced by genevalmag::Builder_graphs::save_all_graphs(), and genevalmag::Builder_graphs::save_cyclic_graphs().
void genevalmag::plan_family_computed (const vector< map< Key_plan, unsigned short >::const_iterator > & plans_computed, vector< unsigned short > & visit_seq_computed)
Converts the vector of iterators over evaluations plans, in their indexs inside of plans uniques.
Definition at line 144 of file Builder_visit_sequences.cpp.
References utilities::belong_index().
Referenced by genevalmag::Builder_visit_sequences::gen_visit_seq(), and genevalmag::Builder_visit_sequences::generate_visit_sequences().
void genevalmag::purge_plan_with (const Rule & rule, const Order_eval_eq & order_eq, Order_eval_eq & purged_order)
Copy in the result vector all equations belonging to the rule passed as parameter.
Definition at line 321 of file Builder_plans.cpp.
References utilities::belong_index(), and genevalmag::Rule::get_eq().
Referenced by genevalmag::Builder_plans::generate_plans().
void genevalmag::push_mark (char name)
Definition at line 429 of file Semantics_actions.cpp.
References current_literal, genevalmag::Expression::set_type_synthetized(), genevalmag::Expr_literal::set_value(), and stack_node.
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
unsigned short genevalmag::return_index_vec (const Order_eval_eq & order, vector< Order_eval_eq > & vec)
Returns the index in the vector, or inserts in the last position.
Definition at line 370 of file Builder_plans.cpp.
Referenced by genevalmag::Builder_plans::return_index_plan(), and genevalmag::Builder_plans::return_index_plan_p().
void genevalmag::save_assoc_op (const iterator_t str, const iterator_t end)
Definition at line 152 of file Semantics_actions.cpp.
References current_func, and genevalmag::Function::set_oper_assoc().
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::save_attr_ins (const iterator_t str, const iterator_t end)
Definition at line 298 of file Semantics_actions.cpp.
References current_instance, genevalmag::Expr_instance::get_attr(), genevalmag::Symbol::get_attribute(), genevalmag::Expr_instance::get_symb(), and genevalmag::Expr_instance::set_attr().
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::save_domain_func (const iterator_t str, const iterator_t end)
Definition at line 120 of file Semantics_actions.cpp.
References genevalmag::Function::add_domain(), attr_grammar, current_func, and genevalmag::Attr_grammar::return_sort().
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::save_image_func (const iterator_t str, const iterator_t end)
Definition at line 126 of file Semantics_actions.cpp.
References attr_grammar, current_func, genevalmag::Attr_grammar::return_sort(), and genevalmag::Function::set_image().
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::save_index_ins (int const index)
Definition at line 288 of file Semantics_actions.cpp.
References genevalmag::Rule::count_non_terminal(), current_instance, current_rule, genevalmag::Symbol::get_name(), genevalmag::Expr_instance::get_symb(), and genevalmag::Expr_instance::set_num().
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::save_member_list_attr (const iterator_t str, const iterator_t end)
Definition at line 195 of file Semantics_actions.cpp.
References genevalmag::decl_attribute::d_member_symbol, and new_attrs.
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::save_mode_op (const iterator_t str, const iterator_t end)
Definition at line 141 of file Semantics_actions.cpp.
References current_func, and genevalmag::Function::set_mode().
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::save_name_func (const iterator_t str, const iterator_t end)
Definition at line 114 of file Semantics_actions.cpp.
References current_func, and genevalmag::Function::set_name().
Referenced by create_function(), and genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::save_prec_op (int const prec)
Definition at line 147 of file Semantics_actions.cpp.
References current_func, and genevalmag::Function::set_prec().
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::save_right_side_rule (const iterator_t str, const iterator_t end)
Definition at line 247 of file Semantics_actions.cpp.
References genevalmag::Rule::add_right_symbol(), attr_grammar, current_rule, and genevalmag::Attr_grammar::get_symbol().
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::save_rule (const iterator_t str, const iterator_t end)
Definition at line 259 of file Semantics_actions.cpp.
References genevalmag::Attr_grammar::add_rule(), attr_grammar, and current_rule.
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::save_rvalue (const iterator_t str, const iterator_t end)
Definition at line 393 of file Semantics_actions.cpp.
References genevalmag::Rule::add_eq(), utilities::cleaning_tabs(), genevalmag::Semantics_checks::correct_associativity(), current_eq, current_rule, genevalmag::Expr_instance::get_attr(), genevalmag::Equation::get_l_value(), genevalmag::Sort::get_name(), genevalmag::Attribute::get_sort_type(), genevalmag::Semantics_checks::reset_semantic_context(), sem_check, genevalmag::Equation::set_r_value(), stack_node, genevalmag::Expr_instance::to_string(), genevalmag::Equation::to_string(), and genevalmag::Rule::to_string_not_eqs().
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::save_sort_attr (const iterator_t str, const iterator_t end)
Definition at line 180 of file Semantics_actions.cpp.
References genevalmag::decl_attribute::d_sort_type, and new_attrs.
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::save_type_attr (const iterator_t str, const iterator_t end)
Definition at line 186 of file Semantics_actions.cpp.
References genevalmag::decl_attribute::d_mod_type, k_inherit, and new_attrs.
Referenced by genevalmag::attritute_grammar::definition< ScannerT >::definition().
void genevalmag::set_attr_grammar (Attr_grammar * at_grammar)
Sets attribute attr_grammar.
Parameters
at_grammar Sets attribute attr_grammar.
Definition at line 33 of file Semantics_actions.cpp.
References attr_grammar.
Referenced by genevalmag::Parser_AG::parse_grammar().
void genevalmag::set_sem_check (Semantics_checks * s_check)
Sets attribute sem_check.
Parameters
s_check Sets attribute sem_check.
Definition at line 41 of file Semantics_actions.cpp.
References sem_check.
Referenced by genevalmag::Parser_AG::parse_grammar().
void genevalmag::show_help_information ()
Definition at line 144 of file maggen.cpp.
Referenced by main(), and parse_parameters().
int genevalmag::swap_root_child (Expr_function ** old_root, int i_new_root)
Precedence Section. Swaps the root for a left/right child with the correspondent rotations.
Case 1 A(op) B(op) / \ / \ B C --------> D A / \ / \ D E E C
Case 2 A(op) C(op) / \ / \ B C --------> A E / \ / \ D E B D
Definition at line 107 of file Semantics_checks.cpp.
Referenced by genevalmag::Semantics_checks::correct_associativity(), genevalmag::Semantics_checks::correct_precedence(), and genevalmag::Semantics_checks::correct_subtree().
int genevalmag::swap_root_grandson (Expr_function ** old_root)
Swaps the root for left-most grandson.
A (op) B(op) / \ / \ B C --------> D E / \ \ D E(op) A \ / \ F F C
Definition at line 145 of file Semantics_checks.cpp.
Referenced by genevalmag::Semantics_checks::correct_precedence().
double genevalmag::timeval_diff (struct timeval * a, struct timeval * b)
Definition at line 109 of file maggen.cpp.
Referenced by main().
template<class K , class T > const string genevalmag::to_string_map (const map< K, T > & map_elem) [inline]
Operation template that print each element type T of the parameter map.
Returns the string representation of all elements of the map.
Definition at line 54 of file Attr_grammar.cpp.
void genevalmag::warshall_algorithm (const unsigned int size, bool * matrix_plain)
Computes the closure transitive with the Warshall algorithm.
Definition at line 367 of file Semantics_checks.cpp.
Referenced by genevalmag::Semantics_checks::check_reachability().
template<class T > string genevalmag::write_vector_with_inic (string & text_buffer, const string name_vec, const size_t index, const vector< T > & vec, const string type_vec, const string type_array) [inline]
Generates the initialice of an array of type T, with the elements of the vector, and create a new vector with this array.
Definition at line 227 of file Builder_code.cpp.
Variable Documentation
Attr_grammar* genevalmag::attr_grammar
Definition at line 26 of file Semantics_actions.cpp.
Referenced by add_function(), check_well_defined(), create_attributes(), create_instance(), create_new_non_terminal(), create_new_terminal(), create_root_function_node(), create_root_infix_node(), create_root_postfix_node(), create_root_prefix_node(), create_rule(), create_sort(), genevalmag::Builder_visit_sequences::gen_visit_seq(), save_domain_func(), save_image_func(), save_right_side_rule(), save_rule(), and set_attr_grammar().
Expr_function* genevalmag::current_ast_function
Definition at line 72 of file Semantics_actions.cpp.
Referenced by create_func_node().
Equation* genevalmag::current_eq
Definition at line 73 of file Semantics_actions.cpp.
Referenced by create_equation(), and save_rvalue().
Function* genevalmag::current_func
Pointer that reference a new function in the grammar.
Definition at line 49 of file Semantics_actions.cpp.
Referenced by add_function(), add_operator(), create_func_node(), create_function(), create_operator(), inic_func(), save_assoc_op(), save_domain_func(), save_image_func(), save_mode_op(), save_name_func(), and save_prec_op().
Expr_instance* genevalmag::current_instance
Pointer to the last instance of attribute to parse successfully.
Definition at line 70 of file Semantics_actions.cpp.
Referenced by create_equation(), create_instance(), create_instance_node(), save_attr_ins(), and save_index_ins().
Expr_literal* genevalmag::current_literal
Definition at line 71 of file Semantics_actions.cpp.
Referenced by create_bool(), create_lit_ch(), create_lit_number(), create_lit_str(), create_literal_node(), and push_mark().
Rule* genevalmag::current_rule
Pointer that reference a current rule parsed in the grammar.
Definition at line 65 of file Semantics_actions.cpp.
Referenced by genevalmag::Builder_graphs::compute_adp_graph(), genevalmag::Builder_graphs::compute_dcg(), genevalmag::Builder_graphs::compute_down_graph(), create_abbreviated_rule(), create_instance(), create_rule(), genevalmag::Builder_graphs::save_dcg_graphs(), genevalmag::Builder_graphs::save_dp_graphs(), save_index_ins(), save_right_side_rule(), save_rule(), and save_rvalue().
vector<Equation*> genevalmag::index_access_eq
Definition at line 20 of file Rule.cpp.
struct genevalmag::decl_attribute * genevalmag::new_attrs
Type that represent the structure of a full declaration of one Attribute.
Referenced by add_attribute(), create_attributes(), save_member_list_attr(), save_sort_attr(), and save_type_attr().
Semantics_checks* genevalmag::sem_check
Definition at line 28 of file Semantics_actions.cpp.
Referenced by check_well_defined(), create_func_node(), create_root_infix_node(), create_root_postfix_node(), create_root_prefix_node(), decrement_level(), increment_level(), save_rvalue(), and set_sem_check().
vector<Expr_node*> genevalmag::stack_inner_node
Definition at line 79 of file Semantics_actions.cpp.
Referenced by create_func_node(), create_root_function_node(), create_root_infix_node(), create_root_postfix_node(), and create_root_prefix_node().
vector<Expression*> genevalmag::stack_node
Stacks for expression precedence manager.
Definition at line 78 of file Semantics_actions.cpp.
Referenced by create_instance_node(), create_literal_node(), create_root_function_node(), create_root_infix_node(), create_root_postfix_node(), create_root_prefix_node(), push_mark(), and save_rvalue().