genevalmag::Maglib Class Reference
#include <Maglib.h>
Public Member Functions
Maglib ()
virtual ~Maglib ()
int gen_evaluator (const string path_input_file, const string path_folder_output, const string name_library, const vector< string > &headers, const string path) const
Detailed Description
Definition at line 19 of file Maglib.h.
Constructor & Destructor Documentation
genevalmag::Maglib::Maglib ()
Contructor empty of Mag_lib.
Definition at line 26 of file Maglib.cpp.
genevalmag::Maglib::~Maglib () [virtual]
Destructor empty of Mag_lib.
Definition at line 33 of file Maglib.cpp.
Member Function Documentation
int genevalmag::Maglib::gen_evaluator (const string path_input_file, const string path_folder_output, const string name_library, const vector< string > & headers, const string path) const
Generates the static evaluator's files for the Attribute grammar specificated in the input_path_file passed as parameter. All outputs of the library be saved in the path_folder_output. The evaluator classname is defined by name_library. The user could include somes headers for uses externs functions to evaluator.
Parameters
path_input_file
path_folder_output
name_library
headers
path
Returns
Generates the static evaluator's files for the Attribute grammar specificated in the input_path_file passed as parameter. All outputs of the library be saved in the path_folder_output. The evaluator classname is defined by name_library. The user could include somes headers for uses externs functions to evaluator.
Definition at line 45 of file Maglib.cpp.
References utilities::clean_output_folder(), genevalmag::Parser_AG::get_attr_grammar(), genevalmag::Parser_AG::parse_grammar(), and genevalmag::Parser_AG::save_grammar_file().
Referenced by main().
The documentation for this class was generated from the following files:
include/Maglib.h
src/Maglib.cpp