.TH "include/Attr_grammar/Attr_grammar.h" 3 "4 Sep 2010" "Version 1.0" "maggen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Attr_grammar/Attr_grammar.h \- 
.PP
Class that represent the full attribute grammar.  

.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include 'Sort.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Sort.h'\fP
.br
\fC#include 'Attribute.h'\fP
.br
\fC#include 'Symbol.h'\fP
.br
\fC#include '../Attr_grammar/Sort.h'\fP
.br
\fC#include 'Expression.h'\fP
.br
\fC#include 'Expr_leaf.h'\fP
.br
\fC#include '../Attr_grammar/Symbol.h'\fP
.br
\fC#include '../Attr_grammar/Attribute.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgenevalmag::Attr_grammar\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgenevalmag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class that represent the full attribute grammar. 

\fBDate:\fP
.RS 4
28/09/2009 
.RE
.PP
\fBAuthor:\fP
.RS 4
Kilmurray, Gerardo Luis <gerakilmurray@gmail.com> 
.PP
Picco, Gonzalo Martin <gonzalopicco@gmail.com> 
.RE
.PP

.PP
Definition in file \fBAttr_grammar.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for maggen from the source code.
