.TH "src/Attr_grammar/Attr_grammar.cpp" 3 "4 Sep 2010" "Version 1.0" "maggen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Attr_grammar/Attr_grammar.cpp \- 
.PP
Implementation of the methods the \fBAttr_grammar.h\fP.  

.SH SYNOPSIS
.br
.PP
\fC#include <boost/tokenizer.hpp>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include '../../include/Attr_grammar/Attr_grammar.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgenevalmag\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class K , class T > const bool \fBgenevalmag::add\fP (const T &elem, map< K, T > &map_elem)"
.br
.ti -1c
.RI "template<class K , class T > const string \fBgenevalmag::to_string_map\fP (const map< K, T > &map_elem)"
.br
.ti -1c
.RI "const bool \fBgenevalmag::belong\fP (const Symbol &symb, const string &expr_attrs)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of the methods the \fBAttr_grammar.h\fP. 

\fBDate:\fP
.RS 4
28/09/2009 
.RE
.PP
\fBAuthor:\fP
.RS 4
Kilmurray, Gerardo Luis <gerakilmurray@gmail.com> 
.PP
Picco, Gonzalo Martin <gonzalopicco@gmail.com> 
.RE
.PP

.PP
Definition in file \fBAttr_grammar.cpp\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for maggen from the source code.
