.TH "include/Attr_grammar/Attribute.h" 3 "4 Sep 2010" "Version 1.0" "maggen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Attr_grammar/Attribute.h \- 
.PP
Class of the attribute of the attribute grammar.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Sort.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgenevalmag::Attribute\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgenevalmag\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBgenevalmag::type_attr\fP { \fBgenevalmag::k_inherit\fP, \fBgenevalmag::k_synthetize\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class of the attribute of the attribute grammar. 

\fBDate:\fP
.RS 4
23/10/2009 
.RE
.PP
\fBAuthor:\fP
.RS 4
Kilmurray, Gerardo Luis <gerakilmurray@gmail.com> 
.PP
Picco, Gonzalo Martin <gonzalopicco@gmail.com> 
.RE
.PP

.PP
Definition in file \fBAttribute.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for maggen from the source code.
