.TH "include/Builders/Builder_visit_sequences.h" 3 "4 Sep 2010" "Version 1.0" "maggen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Builders/Builder_visit_sequences.h \- 
.PP
Header with the functions for build the visits sequences of grammar.  

.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include '../Attr_grammar/Attr_grammar.h'\fP
.br
\fC#include 'Builder_plans.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgenevalmag::Builder_visit_sequences\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgenevalmag\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef vector< int > \fBgenevalmag::Visit_seq\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header with the functions for build the visits sequences of grammar. 

Implementation of the methods the \fBBuilder_visit_sequences.h\fP.
.PP
\fBDate:\fP
.RS 4
17/03/2010 
.RE
.PP
\fBAuthor:\fP
.RS 4
Kilmurray, Gerardo Luis <gerakilmurray@gmail.com> 
.PP
Picco, Gonzalo Martin <gonzalopicco@gmail.com> 
.RE
.PP

.PP
Definition in file \fBBuilder_visit_sequences.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for maggen from the source code.
