.TH "src/Expression_tree/Expr_instance.cpp" 3 "4 Sep 2010" "Version 1.0" "maggen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Expression_tree/Expr_instance.cpp \- 
.PP
Implementation of a instance element of an Expression.  

.SH SYNOPSIS
.br
.PP
\fC#include <sstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include '../../include/Expression_tree/Expr_instance.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgenevalmag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of a instance element of an Expression. 

\fBDate:\fP
.RS 4
21/12/2009 
.RE
.PP
\fBAuthor:\fP
.RS 4
Kilmurray, Gerardo Luis <gerakilmurray@gmail.com> 
.PP
Picco, Gonzalo Martin <gonzalopicco@gmail.com> 
.RE
.PP

.PP
Definition in file \fBExpr_instance.cpp\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for maggen from the source code.
