.TH "genevalmag::vertex_data_t" 3 "4 Sep 2010" "Version 1.0" "maggen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
genevalmag::vertex_data_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Builder_graphs.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef vertex_property_tag \fBkind\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file Builder_graphs.h.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef vertex_property_tag \fBgenevalmag::vertex_data_t::kind\fP"
.PP
Definition at line 30 of file Builder_graphs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for maggen from the source code.
