.TH "genevalmag::skip_parser::definition" 3 "4 Sep 2010" "Version 1.0" "maggen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
genevalmag::skip_parser::definition \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdefinition\fP (\fBskip_parser\fP const &self)"
.br
.ti -1c
.RI "rule< ScannerT > const & \fBstart\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "rule< ScannerT > \fBskip\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename ScannerT> struct genevalmag::skip_parser::definition< ScannerT >"

.PP
Definition at line 69 of file Parser_AG.cpp.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename ScannerT > \fBgenevalmag::skip_parser::definition\fP< ScannerT >::\fBdefinition\fP (\fBskip_parser\fP const & self)\fC [inline]\fP"
.PP
Definition at line 71 of file Parser_AG.cpp.
.PP
References genevalmag::skip_parser::definition< ScannerT >::skip.
.SH "Member Function Documentation"
.PP 
.SS "template<typename ScannerT > rule<ScannerT> const& \fBgenevalmag::skip_parser::definition\fP< ScannerT >::start () const\fC [inline]\fP"
.PP
Definition at line 81 of file Parser_AG.cpp.
.PP
References genevalmag::skip_parser::definition< ScannerT >::skip.
.SH "Member Data Documentation"
.PP 
.SS "template<typename ScannerT > rule<ScannerT> \fBgenevalmag::skip_parser::definition\fP< ScannerT >::\fBskip\fP"
.PP
Definition at line 79 of file Parser_AG.cpp.
.PP
Referenced by genevalmag::skip_parser::definition< ScannerT >::definition(), and genevalmag::skip_parser::definition< ScannerT >::start().

.SH "Author"
.PP 
Generated automatically by Doxygen for maggen from the source code.
