.TH "src/Maglib.cpp" 3 "4 Sep 2010" "Version 1.0" "maggen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Maglib.cpp \- 
.PP
Implementation of the library of evaluator's generator.  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include '../include/Parser/Parser_AG.h'\fP
.br
\fC#include '../include/Builders/Builder_plans.h'\fP
.br
\fC#include '../include/Builders/Builder_visit_sequences.h'\fP
.br
\fC#include '../include/Builders/Builder_code.h'\fP
.br
\fC#include '../include/Util/Utilities.h'\fP
.br
\fC#include '../include/Maglib.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgenevalmag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of the library of evaluator's generator. 

\fBDate:\fP
.RS 4
14/04/2010 
.RE
.PP
\fBAuthor:\fP
.RS 4
Kilmurray, Gerardo Luis <gerakilmurray@gmail.com> 
.PP
Picco, Gonzalo Martin <gonzalopicco@gmail.com> 
.RE
.PP

.PP
Definition in file \fBMaglib.cpp\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for maggen from the source code.
