.TH "include/Builders/Builder_plans.h" 3 "4 Sep 2010" "Version 1.0" "maggen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Builders/Builder_plans.h \- 
.PP
Header of generation plans module of Attribute Grammar.  

.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include '../Attr_grammar/Attr_grammar.h'\fP
.br
\fC#include '../Attr_grammar/Rule.h'\fP
.br
\fC#include 'Builder_graphs.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBgenevalmag::c_rule\fP"
.br
.ti -1c
.RI "struct \fBgenevalmag::k_w\fP"
.br
.ti -1c
.RI "struct \fBgenevalmag::i_w\fP"
.br
.ti -1c
.RI "struct \fBgenevalmag::k_plan\fP"
.br
.ti -1c
.RI "struct \fBgenevalmag::k_p_project\fP"
.br
.ti -1c
.RI "class \fBgenevalmag::Builder_plans\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgenevalmag\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef vector< unsigned short > \fBgenevalmag::Order_eval_eq\fP"
.br
.ti -1c
.RI "typedef vector< unsigned short > \fBgenevalmag::Order_rule\fP"
.br
.ti -1c
.RI "typedef struct \fBgenevalmag::c_rule\fP \fBgenevalmag::Context_rule\fP"
.br
.ti -1c
.RI "typedef struct \fBgenevalmag::k_w\fP \fBgenevalmag::Key_work_list\fP"
.br
.ti -1c
.RI "typedef struct \fBgenevalmag::i_w\fP \fBgenevalmag::Item_work\fP"
.br
.ti -1c
.RI "typedef struct \fBgenevalmag::k_plan\fP \fBgenevalmag::Key_plan\fP"
.br
.ti -1c
.RI "typedef struct \fBgenevalmag::k_p_project\fP \fBgenevalmag::Key_plan_project\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header of generation plans module of Attribute Grammar. 

\fBDate:\fP
.RS 4
18/02/2010 
.RE
.PP
\fBAuthor:\fP
.RS 4
Kilmurray, Gerardo Luis <gerakilmurray@gmail.com> 
.PP
Picco, Gonzalo Martin <gonzalopicco@gmail.com> 
.RE
.PP

.PP
Definition in file \fBBuilder_plans.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for maggen from the source code.
