.TH "include/Attr_grammar/Function.h" 3 "4 Sep 2010" "Version 1.0" "maggen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Attr_grammar/Function.h \- 
.PP
Class of the function of the attribute grammar.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Sort.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgenevalmag::Function\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgenevalmag\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBgenevalmag::oper_mode\fP { \fBgenevalmag::k_prefix\fP, \fBgenevalmag::k_infix\fP, \fBgenevalmag::k_postfix\fP }"
.br
.ti -1c
.RI "enum \fBgenevalmag::oper_assoc\fP { \fBgenevalmag::k_left\fP, \fBgenevalmag::k_right\fP, \fBgenevalmag::k_non_assoc\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class of the function of the attribute grammar. 

\fBDate:\fP
.RS 4
26/11/2009 
.RE
.PP
\fBAuthor:\fP
.RS 4
Kilmurray, Gerardo Luis <gerakilmurray@gmail.com> 
.PP
Picco, Gonzalo Martin <gonzalopicco@gmail.com> 
.RE
.PP

.PP
Definition in file \fBFunction.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for maggen from the source code.
