.TH "genevalmag::attritute_grammar" 3 "4 Sep 2010" "Version 1.0" "maggen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
genevalmag::attritute_grammar \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBdefinition\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Declaration of the \fBAttribute\fP Grammar structure with the Spirit library of Boost. 
.PP
Definition at line 92 of file Parser_AG.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for maggen from the source code.
