.TH "genevalmag::decl_attribute" 3 "4 Sep 2010" "Version 1.0" "maggen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
genevalmag::decl_attribute \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "vector< string > \fBd_names\fP"
.br
.ti -1c
.RI "string \fBd_sort_type\fP"
.br
.ti -1c
.RI "\fBtype_attr\fP \fBd_mod_type\fP"
.br
.ti -1c
.RI "string \fBd_member_symbol\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type that represent the structure of a full declaration of one \fBAttribute\fP. 
.PP
Definition at line 54 of file Semantics_actions.cpp.
.SH "Member Data Documentation"
.PP 
.SS "string \fBgenevalmag::decl_attribute::d_member_symbol\fP"
.PP
Definition at line 59 of file Semantics_actions.cpp.
.PP
Referenced by genevalmag::add_attribute(), genevalmag::create_attributes(), and genevalmag::save_member_list_attr().
.SS "\fBtype_attr\fP \fBgenevalmag::decl_attribute::d_mod_type\fP"
.PP
Definition at line 58 of file Semantics_actions.cpp.
.PP
Referenced by genevalmag::add_attribute(), genevalmag::create_attributes(), and genevalmag::save_type_attr().
.SS "vector<string> \fBgenevalmag::decl_attribute::d_names\fP"
.PP
Definition at line 56 of file Semantics_actions.cpp.
.PP
Referenced by genevalmag::add_attribute(), and genevalmag::create_attributes().
.SS "string \fBgenevalmag::decl_attribute::d_sort_type\fP"
.PP
Definition at line 57 of file Semantics_actions.cpp.
.PP
Referenced by genevalmag::create_attributes(), and genevalmag::save_sort_attr().

.SH "Author"
.PP 
Generated automatically by Doxygen for maggen from the source code.
