.TH "include/Maglib.h" 3 "4 Sep 2010" "Version 1.0" "maggen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Maglib.h \- 
.PP
Header of the library of evaluator's generator.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgenevalmag::Maglib\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgenevalmag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header of the library of evaluator's generator. 

\fBDate:\fP
.RS 4
14/04/2010 
.RE
.PP
\fBAuthor:\fP
.RS 4
Kilmurray, Gerardo Luis <gerakilmurray@gmail.com> 
.PP
Picco, Gonzalo Martin <gonzalopicco@gmail.com> 
.RE
.PP

.PP
Definition in file \fBMaglib.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for maggen from the source code.
