.TH "include/Attr_grammar/Rule.h" 3 "4 Sep 2010" "Version 1.0" "maggen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Attr_grammar/Rule.h \- 
.PP
Class of the rule of the attribute grammar.  

.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include 'Symbol.h'\fP
.br
\fC#include 'Equation.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgenevalmag::Rule\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgenevalmag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class of the rule of the attribute grammar. 

\fBDate:\fP
.RS 4
05/11/2009 
.RE
.PP
\fBAuthor:\fP
.RS 4
Kilmurray, Gerardo Luis <gerakilmurray@gmail.com> 
.PP
Picco, Gonzalo Martin <gonzalopicco@gmail.com> 
.RE
.PP

.PP
Definition in file \fBRule.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for maggen from the source code.
