.TH "include/Parser/Semantics_checks.h" 3 "4 Sep 2010" "Version 1.0" "maggen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Parser/Semantics_checks.h \- 
.PP
Header method Semantics checks of Attribute grammar.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <map>\fP
.br
\fC#include '../Expression_tree/Expr_function.h'\fP
.br
\fC#include '../Attr_grammar/Rule.h'\fP
.br
\fC#include '../Attr_grammar/Symbol.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgenevalmag::Semantics_checks\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgenevalmag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header method Semantics checks of Attribute grammar. 

\fBDate:\fP
.RS 4
11/02/2010 
.RE
.PP
\fBAuthor:\fP
.RS 4
Kilmurray, Gerardo Luis <gerakilmurray@gmail.com> 
.PP
Picco, Gonzalo Martin <gonzalopicco@gmail.com> 
.RE
.PP

.PP
Definition in file \fBSemantics_checks.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for maggen from the source code.
