.TH "include/Attr_grammar/Symbol.h" 3 "4 Sep 2010" "Version 1.0" "maggen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Attr_grammar/Symbol.h \- 
.PP
Class of the symbol of the attribute grammar.  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'Attribute.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgenevalmag::Symbol\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgenevalmag\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBgenevalmag::symbol_type\fP { \fBgenevalmag::k_terminal\fP, \fBgenevalmag::k_non_terminal\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class of the symbol of the attribute grammar. 

\fBDate:\fP
.RS 4
04/11/2009 
.RE
.PP
\fBAuthor:\fP
.RS 4
Kilmurray, Gerardo Luis <gerakilmurray@gmail.com> 
.PP
Picco, Gonzalo Martin <gonzalopicco@gmail.com> 
.RE
.PP

.PP
Definition in file \fBSymbol.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for maggen from the source code.
