genevalmag::Equation Class Reference
#include <Equation.h>
Public Member Functions
Equation ()
Equation (const Equation &other)
virtual ~Equation ()
Equation & operator= (const Equation &other)
const Expr_instance * get_l_value () const
const Expression * get_r_value () const
const unsigned short get_id () const
void set_id (const unsigned short id)
void set_l_value (const Expr_instance &lvalue)
void set_r_value (const Expression *rvalue)
void inorder_only_leaf (const Expression *head, vector< const Expr_leaf * > &result) const
const vector< const Expr_instance * > get_instance_right_side () const
const string to_string () const
const bool equals (const Equation &other) const
const string key () const
Private Member Functions
void copy (const Equation &other)
void destroy ()
unsigned short * _get_count_ref () const
void inorder_only_instance (const Expression *head, vector< const Expr_instance * > &result) const
Private Attributes
unsigned short eq_id
Equation's identifier.
Expr_instance l_value
const Expression * r_value
unsigned short * count_ref
Similar to a Smart Pointer to manage the release of the memory tree. When this is 0, all memory is freed from the tree.
Detailed Description
Definition at line 19 of file Equation.h.
Constructor & Destructor Documentation
genevalmag::Equation::Equation ()
Constructor empty of equation.
Definition at line 21 of file Equation.cpp.
References count_ref.
genevalmag::Equation::Equation (const Equation & other)
Contructor copy of Equation.
Parameters:
other
Returns:
Contructor copy of Equation.
Definition at line 30 of file Equation.cpp.
References copy().
genevalmag::Equation::~Equation () [virtual]
Destructor of equation.
Definition at line 38 of file Equation.cpp.
References destroy().
Member Function Documentation
unsigned short * genevalmag::Equation::_get_count_ref () const [private]
Returns the count reference.
Returns:
Return the count reference.
Definition at line 91 of file Equation.cpp.
References count_ref.
Referenced by copy().
void genevalmag::Equation::copy (const Equation & other) [private]
Method of copy the equation, STL-like C++.
Parameters:
other Method of copy the equation, STL-like C++.
Definition at line 62 of file Equation.cpp.
References _get_count_ref(), count_ref, eq_id, get_id(), get_l_value(), get_r_value(), l_value, and r_value.
Referenced by Equation(), and operator=().
void genevalmag::Equation::destroy () [private]
Method destroy equation, STL-like C++.
Definition at line 76 of file Equation.cpp.
References count_ref, and r_value.
Referenced by operator=(), and ~Equation().
const bool genevalmag::Equation::equals (const Equation & other) const
Compares the equation with other.
Parameters:
other
Returns:
Compares the equation with other.
Definition at line 247 of file Equation.cpp.
References key().
const unsigned short genevalmag::Equation::get_id () const
Returns the id of the equation.
Returns:
Returns the id of the equation.
Definition at line 115 of file Equation.cpp.
References eq_id.
Referenced by copy().
const vector< const Expr_instance * > genevalmag::Equation::get_instance_right_side () const
Returns the pointer of the Expression.
Returns:
Returns the pointer of the Expression.
Definition at line 215 of file Equation.cpp.
References inorder_only_instance(), and r_value.
const Expr_instance * genevalmag::Equation::get_l_value () const
Returns the l_value of the equation.
Returns:
Returns the l_value of the equation.
Definition at line 99 of file Equation.cpp.
References l_value.
Referenced by copy(), genevalmag::Rule::defined_equation(), genevalmag::Attr_grammar::get_eq_l_value(), and genevalmag::save_rvalue().
const Expression * genevalmag::Equation::get_r_value () const
Returns the r_value of the equation.
Returns:
Returns the r_value of the equation.
Definition at line 107 of file Equation.cpp.
References r_value.
Referenced by copy().
void genevalmag::Equation::inorder_only_instance (const Expression * head, vector< const Expr_instance * > & result) const [private]
Traverse the equation tree while saves only the Expr_instance nodes in the vector result.
Parameters:
head
result Traverse the equation tree while saves only the Expr_instance nodes in the vector result.
Definition at line 178 of file Equation.cpp.
References genevalmag::Expr_node::get_child(), and genevalmag::Expr_node::get_childs().
Referenced by get_instance_right_side().
void genevalmag::Equation::inorder_only_leaf (const Expression * head, vector< const Expr_leaf * > & result) const
Traverse the equation tree while saves only the Expr_leaf nodes in the vector result.
Parameters:
head
result Traverse the equation tree while saves only the Expr_leaf nodes in the vector result.
Definition at line 147 of file Equation.cpp.
References genevalmag::Expr_node::get_child(), and genevalmag::Expr_node::get_childs().
const string genevalmag::Equation::key () const
Generates and returns the string key that identifies an Equation definitely.
 Result = <l_value><r_value>
 where <l_value> = `instance_attr` and <r_value> is= `list of node_ast`
Returns:
Generate and return the string key that identifies an Equation definitely.
Result = <l_value><r_value>
where <l_value> = `instance_attr` and <r_value> is= `list of node_ast`
Definition at line 259 of file Equation.cpp.
References l_value, r_value, genevalmag::Expression::to_string(), and genevalmag::Expr_instance::to_string().
Referenced by equals().
Equation & genevalmag::Equation::operator= (const Equation & other)
Operator assign(=) of Equation.
Parameters:
other
Returns:
Operator assign(=) of Equation.
Definition at line 49 of file Equation.cpp.
References copy(), and destroy().
void genevalmag::Equation::set_id (const unsigned short id)
Sets the id of the equation.
Parameters:
id Sets the id of the equation.
Definition at line 123 of file Equation.cpp.
References eq_id.
Referenced by genevalmag::Rule::add_eq().
void genevalmag::Equation::set_l_value (const Expr_instance & lvalue)
Sets the left value of the equation.
Parameters:
lvalue Set the left value of the equation.
Definition at line 131 of file Equation.cpp.
References l_value.
Referenced by genevalmag::create_equation().
void genevalmag::Equation::set_r_value (const Expression * rvalue)
Sets the rigth value of the equation: is a tree.
Parameters:
rvalue Set the left value of the equation.
Definition at line 139 of file Equation.cpp.
References r_value.
Referenced by genevalmag::save_rvalue().
const string genevalmag::Equation::to_string () const
Generates and returns a string reprensentation of an Equation.
 Result = <l_value> `=` <r_value> `;`
 where <l_value> = `instance_attr` and <r_value> is= `list of node_ast`
Returns:
Generate and return a string reprensentation of an Equation.
Result= <l_value> `=` <r_value> `;`
where <l_value> = `instance_attr` and <r_value> is= `list of node_ast`
Definition at line 229 of file Equation.cpp.
References eq_id, l_value, r_value, genevalmag::Expression::to_string(), and genevalmag::Expr_instance::to_string().
Referenced by genevalmag::save_rvalue().
Member Data Documentation
genevalmag::Equation::count_ref [private]
Similar to a Smart Pointer to manage the release of the memory tree. When this is 0, all memory is freed from the tree.
Definition at line 43 of file Equation.h.
Referenced by _get_count_ref(), copy(), destroy(), and Equation().
genevalmag::Equation::eq_id [private]
Equation's identifier.
Equation's tree expression.
Equation's left value.
Definition at line 26 of file Equation.h.
Referenced by copy(), get_id(), set_id(), and to_string().
Expr_instance genevalmag::Equation::l_value [private]
Definition at line 31 of file Equation.h.
Referenced by copy(), get_l_value(), key(), set_l_value(), and to_string().
const Expression* genevalmag::Equation::r_value [private]
Definition at line 36 of file Equation.h.
Referenced by copy(), destroy(), get_instance_right_side(), get_r_value(), key(), set_r_value(), and to_string().
The documentation for this class was generated from the following files:
include/Attr_grammar/Equation.h
src/Attr_grammar/Equation.cpp