genevalmag::Expression Class Reference
#include <Expression.h>
Inherited by genevalmag::Expr_leaf, and genevalmag::Expr_node.
Public Member Functions
Expression ()
virtual ~Expression ()
const Expression * get_parent () const
const string get_type_synthetized () const
int get_conflict () const
void set_parent (const Expression *new_parent)
void set_type_synthetized (string new_type_synthetized)
void delete_parent ()
void active_conflict (int prec_conflict)
void desactive_conflict ()
virtual string to_string () const =0
Protected Attributes
const Expression * parent
Father of Expression.
string type_synthetized
Type of node: Obtains of parse.
int conflict
Mark when conflicted node.
 This conflict is a conflict in the parse.
 Used for define the precedence of function.
.
Detailed Description
Definition at line 21 of file Expression.h.
Constructor & Destructor Documentation
genevalmag::Expression::Expression ()
Constructor of Expression.
Returns:
Contructor of Expression.
Definition at line 17 of file Expression.cpp.
References conflict, parent, and type_synthetized.
genevalmag::Expression::~Expression () [virtual]
Destructor of Expression.
Returns:
Destructor of Expression.
Definition at line 27 of file Expression.cpp.
Member Function Documentation
void genevalmag::Expression::active_conflict (int prec_conflict)
Turn on the conflict flag with the precendence wath produces.
Parameters:
prec_conflict Turn on the conflict flag with the precendence wath produces.
Definition at line 80 of file Expression.cpp.
References conflict.
void genevalmag::Expression::delete_parent ()
Sets the parent pointer of the Expression in NULL.
Definition at line 72 of file Expression.cpp.
References parent.
void genevalmag::Expression::desactive_conflict ()
Turn off the conflict flag with negative precendence.
Definition at line 88 of file Expression.cpp.
References conflict.
int genevalmag::Expression::get_conflict () const
Returns the precendence wath produces the conflict.
Returns:
Returns the precendence wath produces the conflict.
Definition at line 48 of file Expression.cpp.
References conflict.
Referenced by genevalmag::Expr_literal::copy(), genevalmag::Expr_instance::copy(), and genevalmag::Expr_function::copy().
const Expression * genevalmag::Expression::get_parent () const
Returns the parent pointer of the Expression.
Returns:
Returns the parent pointer of the Expression.
Definition at line 32 of file Expression.cpp.
References parent.
Referenced by genevalmag::Expr_literal::copy(), genevalmag::Expr_instance::copy(), and genevalmag::Expr_function::copy().
const string genevalmag::Expression::get_type_synthetized () const
Returns the type synthetized of the Expression.
Returns:
Returns the type synthetized of the Expression.
Definition at line 40 of file Expression.cpp.
References type_synthetized.
Referenced by genevalmag::Expr_literal::copy(), genevalmag::Expr_instance::copy(), and genevalmag::Expr_function::copy().
void genevalmag::Expression::set_parent (const Expression * new_parent)
Sets the parent pointer of the Expression.
Parameters:
new_parent Sets the parent pointer of the Expression.
Definition at line 56 of file Expression.cpp.
References parent.
Referenced by genevalmag::Expr_node::add_child(), and genevalmag::Expr_node::replace_child().
void genevalmag::Expression::set_type_synthetized (string new_type_synthetized)
Returns the type synthetized of the Expression.
Parameters:
new_type_synthetized Returns the type synthetized of the Expression.
Definition at line 64 of file Expression.cpp.
References type_synthetized.
Referenced by genevalmag::create_bool(), genevalmag::create_instance_node(), genevalmag::create_lit_ch(), genevalmag::create_lit_number(), genevalmag::create_lit_str(), and genevalmag::push_mark().
virtual string genevalmag::Expression::to_string () const [pure virtual]
Generate and return a string reprensentation of a Expression.
Returns:
Implemented in genevalmag::Expr_function, genevalmag::Expr_instance, genevalmag::Expr_leaf, genevalmag::Expr_literal, and genevalmag::Expr_node.
Referenced by genevalmag::Equation::key(), and genevalmag::Equation::to_string().
Member Data Documentation
genevalmag::Expression::conflict [protected]
Mark when conflicted node.
 This conflict is a conflict in the parse.
 Used for define the precedence of function.
.
Definition at line 40 of file Expression.h.
Referenced by active_conflict(), genevalmag::Expr_literal::copy(), genevalmag::Expr_instance::copy(), genevalmag::Expr_function::copy(), desactive_conflict(), Expression(), and get_conflict().
genevalmag::Expression::parent [protected]
Father of Expression.
Definition at line 28 of file Expression.h.
Referenced by genevalmag::Expr_literal::copy(), genevalmag::Expr_instance::copy(), genevalmag::Expr_function::copy(), delete_parent(), Expression(), get_parent(), and set_parent().
genevalmag::Expression::type_synthetized [protected]
Type of node: Obtains of parse.
Definition at line 33 of file Expression.h.
Referenced by genevalmag::Expr_literal::copy(), genevalmag::Expr_instance::copy(), genevalmag::Expr_function::copy(), Expression(), get_type_synthetized(), and set_type_synthetized().
The documentation for this class was generated from the following files:
include/Expression_tree/Expression.h
src/Expression_tree/Expression.cpp