genevalmag::Sort Class Reference
#include <Sort.h>
Public Member Functions
Sort ()
Sort (const string name)
Sort (const Sort &other)
virtual ~Sort ()
Sort & operator= (const Sort &other)
const string get_name () const
void set_name (const string name)
void set_type_basic (const bool type_basic)
const string to_string () const
const bool equals (const Sort &other) const
const bool is_type_basic () const
const string key () const
Private Member Functions
void copy (const Sort &other)
void destroy ()
Private Attributes
string s_name
Sort's name.
unsigned int s_ins
Sort's instance.
bool s_type_basic
Is true iff is a type basic of C++.
Detailed Description
Definition at line 19 of file Sort.h.
Constructor & Destructor Documentation
genevalmag::Sort::Sort ()
Contructor empty of Sort.
Definition at line 20 of file Sort.cpp.
References s_ins.
genevalmag::Sort::Sort (const string name)
Contructor with the name of the Sort.
Parameters:
name
Returns:
Contructor with the name of the Sosrt.
Definition at line 28 of file Sort.cpp.
References s_ins, s_name, and s_type_basic.
genevalmag::Sort::Sort (const Sort & other)
Contructor copy of Sort.
Parameters:
other
Returns:
Contructor copy of Sort.
Definition at line 38 of file Sort.cpp.
References copy().
genevalmag::Sort::~Sort () [virtual]
Destructor of Sort.
Definition at line 46 of file Sort.cpp.
References destroy().
Member Function Documentation
void genevalmag::Sort::copy (const Sort & other) [private]
Method of copy the Sort, STL-like C++.
Parameters:
other Method of copy the Sort, STL-like C++.
Definition at line 67 of file Sort.cpp.
References get_name(), is_type_basic(), s_ins, s_name, and s_type_basic.
Referenced by operator=(), and Sort().
void genevalmag::Sort::destroy () [private]
Method destroy Sort, STL-like C++.
Definition at line 79 of file Sort.cpp.
Referenced by operator=(), and ~Sort().
const bool genevalmag::Sort::equals (const Sort & other) const
Compares the Sort with other.
Parameters:
other
Returns:
Compares the Sort with other.
Definition at line 141 of file Sort.cpp.
References key().
const string genevalmag::Sort::get_name () const
Returns the name of the Sort.
Returns:
Returns the name of the Sort.
Definition at line 86 of file Sort.cpp.
References s_name.
Referenced by copy(), genevalmag::create_instance_node(), genevalmag::Attribute::key(), genevalmag::save_rvalue(), genevalmag::Function::signature(), genevalmag::Function::to_string(), and genevalmag::Attribute::to_string().
const bool genevalmag::Sort::is_type_basic () const
Returns if the Sort is basic.
Returns:
Returns if the Sort is basic.
Definition at line 149 of file Sort.cpp.
References s_type_basic.
Referenced by copy(), and to_string().
const string genevalmag::Sort::key () const
Generates and returns the string key that identifies a Sort definitely.
 Result = <name>
Returns:
Generates and returns the string key that identifies a Sort definitely.
Result = <name>
Definition at line 159 of file Sort.cpp.
References s_name.
Referenced by equals().
Sort & genevalmag::Sort::operator= (const Sort & other)
Operator assign(=) of Sort.
Parameters:
other
Returns:
Operator assign(=) of Sort.
Definition at line 54 of file Sort.cpp.
References copy(), and destroy().
void genevalmag::Sort::set_name (const string name)
Sets the name of the Sort.
Parameters:
name Sets the name of the Sort.
Definition at line 94 of file Sort.cpp.
References s_name.
void genevalmag::Sort::set_type_basic (const bool type_basic)
Sets if the Sort is basic.
Parameters:
type_basic Set if the Sort is basic.
Definition at line 101 of file Sort.cpp.
References s_type_basic.
Referenced by genevalmag::Attr_grammar::return_sort().
const string genevalmag::Sort::to_string () const
Generates and returns a string reprensentation of a Sort.
 Result = `sort` <name> [`(` <instance> `)` IF DEBUG IS ON] `;`
Returns:
Generates and returns a string reprensentation of a Sort.
Result = `sort` <name> [`(` <instance> `)` IF DEBUG IS ON] `;`
Definition at line 111 of file Sort.cpp.
References is_type_basic(), s_ins, and s_name.
Referenced by genevalmag::create_sort().
Member Data Documentation
genevalmag::Sort::s_ins [private]
Sort's instance.
Definition at line 31 of file Sort.h.
Referenced by copy(), Sort(), and to_string().
genevalmag::Sort::s_name [private]
Sort's name.
Definition at line 26 of file Sort.h.
Referenced by copy(), get_name(), key(), set_name(), Sort(), and to_string().
genevalmag::Sort::s_type_basic [private]
Is true iff is a type basic of C++.
Definition at line 36 of file Sort.h.
Referenced by copy(), is_type_basic(), set_type_basic(), and Sort().
The documentation for this class was generated from the following files:
include/Attr_grammar/Sort.h
src/Attr_grammar/Sort.cpp