genevalmag::Function Class Reference
#include <Function.h>
Public Member Functions
Function ()
Function (const Function &other)
virtual ~Function ()
Function & operator= (const Function &other)
string get_name () const
const vector< const Sort * > & get_domain () const
const Sort * get_image () const
const oper_mode get_mode () const
const unsigned short get_prec () const
const oper_assoc get_oper_assoc () const
const int get_arity () const
void set_name (const string name)
void set_image (const Sort *image)
void set_mode (const string mode)
void set_prec (const unsigned short prec)
void set_oper_assoc (const string mod)
void set_is_operator (const bool value)
void add_domain (const Sort *sort)
const string to_string () const
const string signature () const
const bool is_operator () const
const bool equals (const Function &other) const
const string key () const
Private Member Functions
void copy (const Function &other)
void destroy ()
Private Attributes
string f_name
Function's name.
vector< const Sort * > f_domain
Function's sort domain.
const Sort * f_image
Function's sort image.
oper_mode f_mod
Function's notation. Functions are always prefix. Operators can be anyone.
unsigned short f_prec
Function's precedence.
oper_assoc f_assoc
Function's associativity.
bool f_is_operator
If that value is TRUE then the object function is a operator. This can be: prefix, infix or postfix.
Detailed Description
Definition at line 40 of file Function.h.
Constructor & Destructor Documentation
genevalmag::Function::Function ()
Contructor empty of function.
Contructor empty of Function.
Definition at line 21 of file Function.cpp.
References f_assoc, f_is_operator, f_mod, f_prec, genevalmag::k_left, and genevalmag::k_prefix.
genevalmag::Function::Function (const Function & other)
Contructor copy of function.
Parameters:
other
Returns:
Contructor copy of Function.
Definition at line 32 of file Function.cpp.
References copy().
genevalmag::Function::~Function () [virtual]
Destructor of the function.
Destructor of the Function.
Definition at line 40 of file Function.cpp.
References destroy().
Member Function Documentation
void genevalmag::Function::add_domain (const Sort * sort)
Enqueues a sort in the domain of the Function.
Parameters:
sort Enqueue a sort in the domain of the Function.
Definition at line 230 of file Function.cpp.
References f_domain.
Referenced by genevalmag::save_domain_func().
void genevalmag::Function::copy (const Function & other) [private]
Method of copy the function, STL-like C++.
Parameters:
other Method of copy the Function, STL-like C++.
Definition at line 61 of file Function.cpp.
References f_assoc, f_domain, f_image, f_is_operator, f_mod, f_name, f_prec, get_domain(), get_image(), get_mode(), get_name(), get_oper_assoc(), get_prec(), and is_operator().
Referenced by Function(), and operator=().
void genevalmag::Function::destroy () [private]
Method destroy function, STL-like C++.
Method destroy Function, STL-like C++.
Definition at line 75 of file Function.cpp.
Referenced by operator=(), and ~Function().
const bool genevalmag::Function::equals (const Function & other) const
Compares the Function with other.
Parameters:
other
Returns:
Compares the Function with other.
Definition at line 346 of file Function.cpp.
References key().
const int genevalmag::Function::get_arity () const
Returns the arity of Function.
Returns:
Returns the arity of Function.
Definition at line 130 of file Function.cpp.
References f_domain.
const vector< const Sort * > & genevalmag::Function::get_domain () const
Returns the domain of the Function.
Returns:
Returns the domain of the Function.
Definition at line 90 of file Function.cpp.
References f_domain.
Referenced by copy().
const Sort * genevalmag::Function::get_image () const
Returns the image of the Function.
Returns:
Returns the image of the Function.
Definition at line 98 of file Function.cpp.
References f_image.
Referenced by copy().
const oper_mode genevalmag::Function::get_mode () const
Returns the mode of the operator.
Returns:
Returns the mode of the operator.
Definition at line 106 of file Function.cpp.
References f_mod.
Referenced by copy(), genevalmag::Expr_function::is_infix(), genevalmag::Expr_function::is_postfix(), genevalmag::Expr_function::is_prefix(), and genevalmag::Expr_function::to_string().
string genevalmag::Function::get_name () const
Returns the name of the Function.
Returns:
Returns the name of the Function.
Definition at line 82 of file Function.cpp.
References f_name.
Referenced by copy(), genevalmag::generate_expr_text(), key(), signature(), genevalmag::Expr_function::to_string(), and to_string().
const oper_assoc genevalmag::Function::get_oper_assoc () const
Returns the associativity of the operator.
Returns:
Returns the associativity of the operator.
Definition at line 122 of file Function.cpp.
References f_assoc.
Referenced by copy().
const unsigned short genevalmag::Function::get_prec () const
Returns the precedence of the operator.
Returns:
Returns the precedence of the operator.
Definition at line 114 of file Function.cpp.
References f_prec.
Referenced by genevalmag::Expr_function::compare_precedence(), copy(), and genevalmag::Semantics_checks::correct_precedence().
const bool genevalmag::Function::is_operator () const
Returns true if the Function is a Operator.
Returns:
Returns true if the Function is a Operator.
Definition at line 338 of file Function.cpp.
References f_is_operator.
Referenced by copy(), genevalmag::generate_expr_text(), key(), signature(), genevalmag::Expr_function::to_string(), and to_string().
const string genevalmag::Function::key () const
Generates and returns the string key that identifies a Function definitely.
 Result = <name> <domain> <image>
 where <domain> is = sort_1 ... sort_n
Returns:
Generates and returns the string key that identifies a Function definitely.
Result = <name> <domain> <image>
where <domain> is = sort_1 ... sort_n
Definition at line 358 of file Function.cpp.
References f_domain, f_mod, f_name, get_name(), is_operator(), genevalmag::k_infix, genevalmag::k_postfix, and genevalmag::k_prefix.
Referenced by equals().
Function & genevalmag::Function::operator= (const Function & other)
Operator assign(=) of function.
Parameters:
other
Returns:
Operator assign(=) of Function.
Definition at line 48 of file Function.cpp.
References copy(), and destroy().
void genevalmag::Function::set_image (const Sort * image)
Sets the sort image of the Function.
Parameters:
image Sets the sort image of the Function.
Definition at line 146 of file Function.cpp.
References f_image.
Referenced by genevalmag::save_image_func().
void genevalmag::Function::set_is_operator (const bool value)
Sets the boolean attribute with the parameter.
Parameters:
value Sets the boolean attribute with the parameter.
Definition at line 222 of file Function.cpp.
References f_is_operator.
Referenced by genevalmag::add_operator(), and genevalmag::create_operator().
void genevalmag::Function::set_mode (const string mode)
Sets the mode of the operator.
Parameters:
mode Sets the mode of the operator.
Definition at line 154 of file Function.cpp.
References f_mod, genevalmag::k_infix, genevalmag::k_postfix, and genevalmag::k_prefix.
Referenced by genevalmag::save_mode_op().
void genevalmag::Function::set_name (const string name)
Sets the name of the Function.
Parameters:
name Sets the name of the Function.
Definition at line 138 of file Function.cpp.
References f_name.
Referenced by genevalmag::save_name_func().
void genevalmag::Function::set_oper_assoc (const string mod)
Sets the associativity of the operator.
Parameters:
mod Sets the associativity of the operator.
Definition at line 192 of file Function.cpp.
References f_assoc, genevalmag::k_left, genevalmag::k_non_assoc, and genevalmag::k_right.
Referenced by genevalmag::save_assoc_op().
void genevalmag::Function::set_prec (const unsigned short prec)
Sets the precedence of the operator.
Parameters:
prec Sets the precedence of the operator.
Definition at line 184 of file Function.cpp.
References f_prec.
Referenced by genevalmag::save_prec_op().
const string genevalmag::Function::signature () const
Generates and returns a string with the signature of a Function.
 Result = <image> <name> `(` <domain> `);`
 or if is an operator:
 Result = <image> `operator`<name> `(` <domain> `);`
 where <domain> is = sort_1 P1`,` ... `,` sort_n Pn
Returns:
Generates and returns a string with the signature of a Function.
Result = <image> <name> `(` <domain> `);`
or if is an operator:
Result = <image> `operator`<name> `(` <domain> `);`
where <domain> is= sort_1 P1`,` ... `,` sort_n Pn
Definition at line 308 of file Function.cpp.
References f_domain, f_image, f_name, get_name(), genevalmag::Sort::get_name(), and is_operator().
const string genevalmag::Function::to_string () const
Generates and returns a string reprensentation of a Function.
 Result = `function` <name> `:` <domain> ` $\rightarrow$ ` <image> `;`
 where <domain> is= sort_1 [`(` <instance> `)` IF DEBUG IS ON] `,` ... `,` sort_n [`(` <instance> `)` IF DEBUG IS ON]
Returns:
Generates and returns a string reprensentation of a Function.
Result = `function` <name> `:` <domain> ` $\rightarrow$ ` <image> `;`
where <domain> is= sort_1 [`(` <instance> `)` IF DEBUG IS ON] `,` ... `,` sort_n [`(` <instance> `)` IF DEBUG IS ON]
Definition at line 242 of file Function.cpp.
References f_assoc, f_domain, f_image, f_mod, f_name, f_prec, genevalmag::Sort::get_name(), get_name(), is_operator(), genevalmag::k_infix, genevalmag::k_left, genevalmag::k_non_assoc, genevalmag::k_postfix, genevalmag::k_prefix, and genevalmag::k_right.
Referenced by genevalmag::add_function().
Member Data Documentation
genevalmag::Function::f_assoc [private]
Function's associativity.
Definition at line 72 of file Function.h.
Referenced by copy(), Function(), get_oper_assoc(), set_oper_assoc(), and to_string().
genevalmag::Function::f_domain [private]
Function's sort domain.
Definition at line 52 of file Function.h.
Referenced by add_domain(), copy(), get_arity(), get_domain(), key(), signature(), and to_string().
genevalmag::Function::f_image [private]
Function's sort image.
Definition at line 57 of file Function.h.
Referenced by copy(), get_image(), set_image(), signature(), and to_string().
genevalmag::Function::f_is_operator [private]
If that value is TRUE then the object function is a operator. This can be: prefix, infix or postfix.
Definition at line 78 of file Function.h.
Referenced by copy(), Function(), is_operator(), and set_is_operator().
genevalmag::Function::f_mod [private]
Function's notation. Functions are always prefix. Operators can be anyone.
Definition at line 62 of file Function.h.
Referenced by copy(), Function(), get_mode(), key(), set_mode(), and to_string().
genevalmag::Function::f_name [private]
Function's name.
Definition at line 47 of file Function.h.
Referenced by copy(), get_name(), key(), set_name(), signature(), and to_string().
genevalmag::Function::f_prec [private]
Function's precedence.
Definition at line 67 of file Function.h.
Referenced by copy(), Function(), get_prec(), set_prec(), and to_string().
The documentation for this class was generated from the following files:
include/Attr_grammar/Function.h
src/Attr_grammar/Function.cpp