genevalmag::Builder_plans Class Reference
#include <Builder_plans.h>
Public Member Functions
Builder_plans (const Attr_grammar &attribute_grammar)
~Builder_plans ()
unsigned short build_plans ()
bool save_all_plans (const string path_output) const
bool save_all_plans_project (const string path_output) const
const Order_rule & get_context_unique (const unsigned short i_context) const
const vector< Order_rule > & get_contexts_uniques () const
const map< Key_plan, unsigned short > & get_plans () const
const vector< Order_eval_eq > & get_plans_uniques () const
const map< Key_plan_project, unsigned short > & get_plans_project () const
const vector< Order_eval_eq > & get_plans_project_uniques () const
const unsigned short & get_init_order () const
const unsigned short get_index_plan (const map< Key_plan, unsigned short >::const_iterator it_plan) const
const map< Key_plan_project, unsigned short >::const_iterator get_plan_project (const Key_plan_project &key) const
void save_all_graphs (const string path_output) const
void save_cyclic_graphs (const string path_output) const
Private Member Functions
void generates_topological_order (const Graph &graph, Order_eval_eq &result_order, const Context_rule &context_rule) const
Order_eval_eq compute_order (const Graph &graph_adp, unsigned short index_order, const Context_rule &context_rule)
bool generate_plans ()
bool generate_graphs ()
unsigned short return_index_context (const Order_rule &order)
unsigned short return_index_plan (const Order_eval_eq &order)
unsigned short return_index_plan_p (const Order_eval_eq &order)
Private Attributes
const Attr_grammar & attr_grammar
References to the attribute grammar.
vector< Order_rule > contexts_uniques
Store all different context rule generates in the grammar.
map< Key_plan, unsigned short > eval_plans
Store all evaluation plans of the grammar. Saves index of plans_uniques vector. `ro` function. Wuu Yang's paper.
vector< Order_eval_eq > plans_uniques
map< Key_plan_project, unsigned short > plans_project
Store all evaluation plans projects of the grammar.Saves index of plans_project_uniques vector. `theta` function. Wuu Yang's paper.
vector< Order_eval_eq > plans_project_uniques
unsigned short init_order_ag
Store the initial evaluation order of the attributes of the initial symbol.
Builder_graphs build_graphs
Stores all graphs DP, DOWN, DCG and ADP, generated for the grammar's analisys.
Detailed Description
Definition at line 254 of file Builder_plans.h.
Constructor & Destructor Documentation
genevalmag::Builder_plans::Builder_plans (const Attr_grammar & attribute_grammar)
Constructor empty of Builder plans.
Parameters:
attribute_grammar
Returns:
Constructor empty of Builder plan.
Definition at line 34 of file Builder_plans.cpp.
genevalmag::Builder_plans::~Builder_plans ()
Destructor of Builder plans.
Returns:
Destructor of Builder plan.
Definition at line 43 of file Builder_plans.cpp.
Member Function Documentation
unsigned short genevalmag::Builder_plans::build_plans ()
Generates and saves all evaluation's plans for the Attribute Grammar.
Return: 0: when all success process. 1: when detects cilcyc graph. 2: when detects error in the graph generation.
Returns:
Return: 0: when all success process. 1: when detects cilcyc graph. 2: when detects error in the graph generation.
Definition at line 521 of file Builder_plans.cpp.
References build_graphs, genevalmag::Builder_graphs::check_cyclic_adp_dependencies(), generate_graphs(), and generate_plans().
Order_eval_eq genevalmag::Builder_plans::compute_order (const Graph & graph_adp, unsigned short index_order, const Context_rule & context_rule) [private]
Compute the rule's order. The changes are applies about paramenter `result_order`.
Parameters:
graph_adp
index_order
context_rule
Returns:
Compute the rule's order. The changes are applies about paramenter `result_order`.
Definition at line 134 of file Builder_plans.cpp.
References attr_grammar, generates_topological_order(), genevalmag::Attr_grammar::get_eq_l_value(), plans_project_uniques, and utilities::return_vertex().
Referenced by generate_plans().
bool genevalmag::Builder_plans::generate_graphs () [private]
Generates all graphs for attribute grammar: DP, DOWN, DCG and ADP.
Returns:
Generates all graphs for attribute grammar: DP, DOWN, DCG and ADP.
Definition at line 66 of file Builder_plans.cpp.
References build_graphs, genevalmag::Builder_graphs::compute_adp_graph(), genevalmag::Builder_graphs::compute_dcg(), genevalmag::Builder_graphs::compute_dependency_graphs(), and genevalmag::Builder_graphs::compute_down_graph().
Referenced by build_plans().
bool genevalmag::Builder_plans::generate_plans () [private]
Generates and saves all evaluation's plans for the Attribute Grammar.
Returns:
Generates and saves all evaluation's plans for the Attribute Grammar.
Definition at line 403 of file Builder_plans.cpp.
References attr_grammar, build_graphs, compute_order(), genevalmag::c_rule::context, genevalmag::defined_work(), eval_plans, genevalmag::k_w::father, genevalmag::c_rule::father, generates_topological_order(), genevalmag::Builder_graphs::get_adp_graphs(), genevalmag::Builder_graphs::get_dcg_graph(), genevalmag::Attr_grammar::get_rule(), genevalmag::Attr_grammar::get_rules(), genevalmag::k_plan::id_plan, genevalmag::k_p_project::id_plan_project, genevalmag::k_w::id_rule, genevalmag::k_p_project::index_ocurrence, init_order_ag, genevalmag::i_w::item, genevalmag::i_w::order_attr, genevalmag::k_plan::plan, plans_project, genevalmag::purge_plan_with(), return_index_context(), return_index_plan(), return_index_plan_p(), and genevalmag::k_p_project::symbol_project.
Referenced by build_plans().
void genevalmag::Builder_plans::generates_topological_order (const Graph & graph, Order_eval_eq & result_order, const Context_rule & context_rule) const [private]
Applies a topological order at graph. The changes are applies about paramenter `result_order`.
Parameters:
graph
result_order
context_rule Applies a topological order at graph. The changes are applies about paramenter `result_order`.
Definition at line 90 of file Builder_plans.cpp.
References attr_grammar, genevalmag::c_rule::context, genevalmag::Symbol::equals(), genevalmag::c_rule::father, genevalmag::Expr_instance::get_attr(), genevalmag::Attr_grammar::get_index_eq_with_context(), genevalmag::Rule::get_left_symbol(), genevalmag::Attr_grammar::get_rule(), genevalmag::Expr_instance::get_symb(), and genevalmag::Attribute::is_inherit().
Referenced by compute_order(), and generate_plans().
const Order_rule & genevalmag::Builder_plans::get_context_unique (const unsigned short i_context) const
Returns the context rule unique in this index.
Parameters:
i_context
Returns:
Returns the context rule unique in this index.
Definition at line 543 of file Builder_plans.cpp.
References contexts_uniques.
Referenced by genevalmag::Builder_visit_sequences::generate_visit_sequences().
const vector< Order_rule > & genevalmag::Builder_plans::get_contexts_uniques () const
Returns all contexts rule uniques.
Returns:
Returns all contexts rule uniques.
Definition at line 551 of file Builder_plans.cpp.
References contexts_uniques.
Referenced by genevalmag::Builder_code::generate_initialize_context().
const unsigned short genevalmag::Builder_plans::get_index_plan (const map< Key_plan, unsigned short >::const_iterator it_plan) const
Returns the index inside the map of the plan that passed as parameter.
Parameters:
it_plan
Returns:
Returns the index inside the map of the plan that passed as parameter.
Definition at line 599 of file Builder_plans.cpp.
References eval_plans.
const unsigned short & genevalmag::Builder_plans::get_init_order () const
Returns the intial order of attributes of the initial symbol.
Returns:
Returns the intial order of attributes of the initial symbol.
Definition at line 591 of file Builder_plans.cpp.
References init_order_ag.
Referenced by genevalmag::Builder_code::generate_evaluator().
const map< Key_plan_project, unsigned short >::const_iterator genevalmag::Builder_plans::get_plan_project (const Key_plan_project & key) const
Returns an constant iterator of a project plan with key equals at the key that passed as parameter. Always finds the element.
Parameters:
key
Returns:
Returns an constant iterator of a project plan with key equals at the key that passed as parameter. Always finds the element.
Definition at line 618 of file Builder_plans.cpp.
References plans_project.
const map< Key_plan, unsigned short > & genevalmag::Builder_plans::get_plans () const
Returns all evaluations plans.
Returns:
Returns all evaluations plans.
Definition at line 559 of file Builder_plans.cpp.
References eval_plans.
Referenced by genevalmag::Builder_code::generate_initialize_plans(), and genevalmag::Builder_visit_sequences::generate_visit_sequences().
const map< Key_plan_project, unsigned short > & genevalmag::Builder_plans::get_plans_project () const
Returns all evaluations plans project.
Returns:
Returns all evaluations plans project.
Definition at line 575 of file Builder_plans.cpp.
References plans_project.
Referenced by genevalmag::Builder_code::generate_initialize_plan_proj().
const vector< Order_eval_eq > & genevalmag::Builder_plans::get_plans_project_uniques () const
Returns all evaluations plans project uniques.
Returns:
Returns all evaluations plans project uniques.
Definition at line 583 of file Builder_plans.cpp.
References plans_project_uniques.
const vector< Order_eval_eq > & genevalmag::Builder_plans::get_plans_uniques () const
Returns all evaluations plans uniques.
Returns:
Returns all evaluations plans uniques.
Definition at line 567 of file Builder_plans.cpp.
References plans_uniques.
Referenced by genevalmag::Builder_visit_sequences::generate_visit_sequences().
unsigned short genevalmag::Builder_plans::return_index_context (const Order_rule & order) [private]
Returns the index in the vector of context, or inserts in the last position.
Parameters:
order
Returns:
Returns the index in the vector of context, or inserts in the last position.
Definition at line 353 of file Builder_plans.cpp.
References contexts_uniques.
Referenced by generate_plans().
unsigned short genevalmag::Builder_plans::return_index_plan (const Order_eval_eq & order) [private]
Returns the index in the vector of plans, or inserts in the last position.
Parameters:
order
Returns:
Returns the index in the vector of plans, or inserts in the last position.
Definition at line 387 of file Builder_plans.cpp.
References plans_uniques, and genevalmag::return_index_vec().
Referenced by generate_plans().
unsigned short genevalmag::Builder_plans::return_index_plan_p (const Order_eval_eq & order) [private]
Returns the index in the vector of plans projects, or inserts in the last position.
Parameters:
order
Returns:
Returns the index in the vector of plans projects, or inserts in the last position.
Definition at line 395 of file Builder_plans.cpp.
References plans_project_uniques, and genevalmag::return_index_vec().
Referenced by generate_plans().
void genevalmag::Builder_plans::save_all_graphs (const string path_output) const
Saves all graphs generated as the analysis of the dependencies between attributes.
Parameters:
path_output Saves all graphs generated as the analysis of the dependencies between attributes.
Definition at line 50 of file Builder_plans.cpp.
References build_graphs, and genevalmag::Builder_graphs::save_all_graphs().
bool genevalmag::Builder_plans::save_all_plans (const string path_output) const
Saves all plans. Creates a graph that represents the plan and uses print_graph with dot.
Parameters:
path_output
Returns:
Saves all plans. Creates a graph that represents the plan and uses print_graph with dot.
Definition at line 171 of file Builder_plans.cpp.
References attr_grammar, utilities::clean_output_folder(), utilities::cleaning_tabs(), contexts_uniques, eval_plans, genevalmag::Attr_grammar::get_eq(), genevalmag::Attr_grammar::get_rules(), genevalmag::PATH_OUT_PLAN(), plans_project_uniques, plans_uniques, utilities::print_graph(), genevalmag::Rule::to_string_not_eqs(), and utilities::write_inf_context().
bool genevalmag::Builder_plans::save_all_plans_project (const string path_output) const
Saves all proyected's plans. Creates a graph that represents the plan and uses print_graph with dot.
Parameters:
path_output
Returns:
Saves all proyected's plans. Creates a graph that represents the plan and uses print_graph with dot.
Definition at line 242 of file Builder_plans.cpp.
References attr_grammar, utilities::clean_output_folder(), utilities::cleaning_tabs(), contexts_uniques, genevalmag::Attr_grammar::get_eq(), genevalmag::Attr_grammar::get_rules(), genevalmag::PATH_OUT_PLAN_PROJECT(), plans_project, plans_project_uniques, utilities::print_graph(), genevalmag::Rule::to_string_not_eqs(), and utilities::write_inf_context().
void genevalmag::Builder_plans::save_cyclic_graphs (const string path_output) const
Saves the graphs generated as the analysis of the dependencies between attributes, which demonstrate cyclicity.
Parameters:
path_output Saves the graphs generated as the analysis of the dependencies between attributes, which demonstrate cyclicity.
Definition at line 58 of file Builder_plans.cpp.
References build_graphs, and genevalmag::Builder_graphs::save_cyclic_graphs().
Member Data Documentation
genevalmag::Builder_plans::attr_grammar [private]
References to the attribute grammar.
Definition at line 261 of file Builder_plans.h.
Referenced by compute_order(), generate_plans(), generates_topological_order(), save_all_plans(), and save_all_plans_project().
genevalmag::Builder_plans::build_graphs [private]
Stores all graphs DP, DOWN, DCG and ADP, generated for the grammar's analisys.
Definition at line 295 of file Builder_plans.h.
Referenced by build_plans(), generate_graphs(), generate_plans(), save_all_graphs(), and save_cyclic_graphs().
genevalmag::Builder_plans::contexts_uniques [private]
Store all different context rule generates in the grammar.
Definition at line 267 of file Builder_plans.h.
Referenced by get_context_unique(), get_contexts_uniques(), return_index_context(), save_all_plans(), and save_all_plans_project().
genevalmag::Builder_plans::eval_plans [private]
Store all evaluation plans of the grammar. Saves index of plans_uniques vector. `ro` function. Wuu Yang's paper.
Definition at line 274 of file Builder_plans.h.
Referenced by generate_plans(), get_index_plan(), get_plans(), and save_all_plans().
genevalmag::Builder_plans::init_order_ag [private]
Store the initial evaluation order of the attributes of the initial symbol.
Definition at line 289 of file Builder_plans.h.
Referenced by generate_plans(), and get_init_order().
genevalmag::Builder_plans::plans_project [private]
Store all evaluation plans projects of the grammar.Saves index of plans_project_uniques vector. `theta` function. Wuu Yang's paper.
Definition at line 282 of file Builder_plans.h.
Referenced by generate_plans(), get_plan_project(), get_plans_project(), and save_all_plans_project().
vector< Order_eval_eq > genevalmag::Builder_plans::plans_project_uniques [private]
Definition at line 283 of file Builder_plans.h.
Referenced by compute_order(), get_plans_project_uniques(), return_index_plan_p(), save_all_plans(), and save_all_plans_project().
vector< Order_eval_eq > genevalmag::Builder_plans::plans_uniques [private]
Definition at line 275 of file Builder_plans.h.
Referenced by get_plans_uniques(), return_index_plan(), and save_all_plans().
The documentation for this class was generated from the following files:
include/Builders/Builder_plans.h
src/Builders/Builder_plans.cpp