genevalmag::Expr_function Class Reference
#include <Expr_function.h>
Public Member Functions
Expr_function ()
Expr_function (const Expr_function &other)
virtual ~Expr_function ()
Expr_function & operator= (const Expr_function &other)
const Function * get_function () const
unsigned short get_precedence_level () const
unsigned short get_syntax_order () const
void set_function (const Function *function)
void set_precedence_level (unsigned short p_level)
void set_syntax_order (unsigned short s_order)
bool is_prefix () const
bool is_infix () const
bool is_postfix () const
bool is_comparable (const Expr_function *other) const
int compare_precedence (const Expr_function *other) const
int compare_order (const Expr_function *other) const
string to_string () const
Private Member Functions
void copy (const Expr_function &other)
void destroy ()
Private Attributes
const Function * func
Function associates with Expr_function.
unsigned short precedence_level
Level precedence of the function.
unsigned short syntax_order
Syntax order in the parse.
Detailed Description
Definition at line 23 of file Expr_function.h.
Constructor & Destructor Documentation
genevalmag::Expr_function::Expr_function ()
Constructor empty of Expr_function.
Returns:
Constructor empty of Expr_function.
Definition at line 24 of file Expr_function.cpp.
References precedence_level, and syntax_order.
genevalmag::Expr_function::Expr_function (const Expr_function & other)
Constructor copy of Expr_function.
Parameters:
other
Returns:
Constructor copy of Expr_function.
Definition at line 37 of file Expr_function.cpp.
References copy().
genevalmag::Expr_function::~Expr_function () [virtual]
Destructor of Expr_function.
Returns:
Destructor of Expr_function.
Definition at line 49 of file Expr_function.cpp.
References destroy().
Member Function Documentation
int genevalmag::Expr_function::compare_order (const Expr_function * other) const
Returns:
 \= O when is same order
 < 0 when other have great order
 > 0 when other have small order
Parameters:
other
Returns:
Return: = O when is same order < 0 when other have great order > 0 when other have small order
Definition at line 193 of file Expr_function.cpp.
References get_syntax_order(), and syntax_order.
int genevalmag::Expr_function::compare_precedence (const Expr_function * other) const
Returns:
 \= O when is same precedence
 < 0 when other have great precedence
 > 0 when other have small precedence
Parameters:
other
Returns:
Return: = O when is same precedence < 0 when other have great precedence > 0 when other have small precedence
Definition at line 182 of file Expr_function.cpp.
References func, get_function(), and genevalmag::Function::get_prec().
void genevalmag::Expr_function::copy (const Expr_function & other) [private]
Method of copy the Expr_function, STL-like C++.
Parameters:
other Method of copy the Expr_function, STL-like C++.
Definition at line 78 of file Expr_function.cpp.
References genevalmag::Expr_node::childs, genevalmag::Expression::conflict, func, genevalmag::Expr_node::get_childs(), genevalmag::Expression::get_conflict(), get_function(), genevalmag::Expression::get_parent(), get_precedence_level(), get_syntax_order(), genevalmag::Expression::get_type_synthetized(), genevalmag::Expression::parent, precedence_level, syntax_order, and genevalmag::Expression::type_synthetized.
Referenced by Expr_function(), and operator=().
void genevalmag::Expr_function::destroy () [private]
Method destroy Expr_function, STL-like C++.
Definition at line 92 of file Expr_function.cpp.
Referenced by operator=(), and ~Expr_function().
const Function * genevalmag::Expr_function::get_function () const
Returns the function pointer of the Expr_function.
Returns:
Returns the function pointer of the Expr_function.
Definition at line 99 of file Expr_function.cpp.
References func.
Referenced by compare_precedence(), copy(), genevalmag::Semantics_checks::correct_associativity(), genevalmag::Semantics_checks::correct_precedence(), and genevalmag::generate_expr_text().
unsigned short genevalmag::Expr_function::get_precedence_level () const
Returns the precedence level of the Expr_function.
Returns:
Returns the precedence level of the Expr_function.
Definition at line 107 of file Expr_function.cpp.
References precedence_level.
Referenced by copy(), and is_comparable().
unsigned short genevalmag::Expr_function::get_syntax_order () const
Returns the syntax order of the Expr_function.
Returns:
Returns the syntax order of the Expr_function.
Definition at line 115 of file Expr_function.cpp.
References syntax_order.
Referenced by compare_order(), and copy().
bool genevalmag::Expr_function::is_comparable (const Expr_function * other) const
Returns if both Expr_functions are in the same precedence level.
Parameters:
other
Returns:
Returns if both Expr_functions are in the same precedence level.
Definition at line 171 of file Expr_function.cpp.
References get_precedence_level(), and precedence_level.
bool genevalmag::Expr_function::is_infix () const
Returns if the function of Expr_function is infix.
Returns:
Returns if the function of Expr_function is infix.
Definition at line 155 of file Expr_function.cpp.
References func, genevalmag::Function::get_mode(), and genevalmag::k_infix.
Referenced by genevalmag::generate_expr_text().
bool genevalmag::Expr_function::is_postfix () const
Returns if the function of Expr_function is postfix.
Returns:
Returns if the function of Expr_function is postfix.
Definition at line 163 of file Expr_function.cpp.
References func, genevalmag::Function::get_mode(), and genevalmag::k_postfix.
Referenced by genevalmag::Semantics_checks::correct_precedence(), and genevalmag::generate_expr_text().
bool genevalmag::Expr_function::is_prefix () const
Returns if the function of Expr_function is prefix.
Returns:
Returns if the function of Expr_function is prefix.
Definition at line 147 of file Expr_function.cpp.
References func, genevalmag::Function::get_mode(), and genevalmag::k_prefix.
Referenced by genevalmag::Semantics_checks::correct_precedence(), and genevalmag::generate_expr_text().
Expr_function & genevalmag::Expr_function::operator= (const Expr_function & other)
Operator assign(=) of Expr_function.
Parameters:
other
Returns:
Operator assign(=) of Expr_function.
Definition at line 65 of file Expr_function.cpp.
References copy(), and destroy().
void genevalmag::Expr_function::set_function (const Function * function)
Sets the function pointer of the Expr_function.
Parameters:
function Sets the function pointer of the Expr_function.
Definition at line 123 of file Expr_function.cpp.
References func.
Referenced by genevalmag::create_func_node().
void genevalmag::Expr_function::set_precedence_level (unsigned short p_level)
Sets the precedence level of the Expr_function.
Parameters:
p_level Sets the precedence level of the Expr_function.
Definition at line 131 of file Expr_function.cpp.
References precedence_level.
Referenced by genevalmag::create_func_node().
void genevalmag::Expr_function::set_syntax_order (unsigned short s_order)
Sets the syntax order of the Expr_function.
Parameters:
s_order Sets the syntax order of the Expr_function.
Definition at line 139 of file Expr_function.cpp.
References syntax_order.
Referenced by genevalmag::create_func_node().
string genevalmag::Expr_function::to_string () const [virtual]
Generate and return a string reprensentation of a Expr_function.
 If is a pure function:
 Result= <func_name> `(` child[0], ... , child[n] `)`
 If is an infix binary operator:
 Result= `(` child[0] <op_name> child[1] `)`
 If is an prefix unary operator:
 Result= <op_name> `(` child[0] `)`
 If is an postfix unary operator:
 Result= `(` child[0] `)` <op_name>
Returns:
Generate and return a string reprensentation of a Expr_function.
If is a pure function: Result= <func_name> `(` child[0], ... , child[n] `)`
If is an infix binary operator: Result= `(` child[0] <op_name> child[1] `)`
If is an prefix unary operator: Result= <op_name> `(` child[0] `)`
If is an postfix unary operator: Result= `(` child[0] `)` <op_name>
Implements genevalmag::Expr_node.
Definition at line 213 of file Expr_function.cpp.
References genevalmag::Expr_node::childs, func, genevalmag::Function::get_mode(), genevalmag::Function::get_name(), genevalmag::Function::is_operator(), genevalmag::k_infix, genevalmag::k_postfix, and genevalmag::k_prefix.
Member Data Documentation
genevalmag::Expr_function::func [private]
Function associates with Expr_function.
Definition at line 30 of file Expr_function.h.
Referenced by compare_precedence(), copy(), get_function(), is_infix(), is_postfix(), is_prefix(), set_function(), and to_string().
genevalmag::Expr_function::precedence_level [private]
Level precedence of the function.
Definition at line 35 of file Expr_function.h.
Referenced by copy(), Expr_function(), get_precedence_level(), is_comparable(), and set_precedence_level().
genevalmag::Expr_function::syntax_order [private]
Syntax order in the parse.
Definition at line 40 of file Expr_function.h.
Referenced by compare_order(), copy(), Expr_function(), get_syntax_order(), and set_syntax_order().
The documentation for this class was generated from the following files:
include/Expression_tree/Expr_function.h
src/Expression_tree/Expr_function.cpp