genevalmag::Builder_visit_sequences Class Reference
#include <Builder_visit_sequences.h>
Public Member Functions
Builder_visit_sequences (const Builder_plans &builder_plan, const Attr_grammar &attribute_grammar)
virtual ~Builder_visit_sequences ()
bool generate_visit_sequences ()
const vector< Visit_seq > & get_visit_seq () const
void print_all_visit_sequences () const
Private Member Functions
bool gen_visit_seq (const map< Key_plan, unsigned short >::const_iterator &it_plan, vector< Expr_instance > &ins_computed, vector< map< Key_plan, unsigned short >::const_iterator > &plans_computed, const vector< unsigned short > &v_seq_computed)
void update_visit_sequence (const Visit_seq &sequence, const size_t i_plan)
Private Attributes
const Builder_plans & b_plans
References to all plans generates.
const Attr_grammar & attr_grammar
References to the attribute grammar.
vector< Visit_seq > all_visit_seqs
Stores all visit sequences generates.
Detailed Description
Definition at line 30 of file Builder_visit_sequences.h.
Constructor & Destructor Documentation
genevalmag::Builder_visit_sequences::Builder_visit_sequences (const Builder_plans & builder_plan, const Attr_grammar & attribute_grammar)
Contructor empty of Builder_visit_sequences.
Parameters:
builder_plan
attribute_grammar
Returns:
Contructor empty of Builder_visit_sequences.
Definition at line 26 of file Builder_visit_sequences.cpp.
genevalmag::Builder_visit_sequences::~Builder_visit_sequences () [virtual]
Destructor of Builder_visit_sequences.
Returns:
Destructor of Builder_visit_sequences.
Definition at line 38 of file Builder_visit_sequences.cpp.
Member Function Documentation
bool genevalmag::Builder_visit_sequences::gen_visit_seq (const map< Key_plan, unsigned short >::const_iterator & it_plan, vector< Expr_instance > & ins_computed, vector< map< Key_plan, unsigned short >::const_iterator > & plans_computed, const vector< unsigned short > & v_seq_computed) [private]
Generates recursively the visit sequence, navigating the tree as indicated by the plans, visiting the children, returning to the parent or generating a compute attribute.
Parameters:
it_plan
ins_computed
plans_computed
v_seq_computed
Returns:
Generates recursively the visit sequence, navigating the tree as indicated by the plans, visiting the children, returning to the parent or generating a compute attribute.
Definition at line 162 of file Builder_visit_sequences.cpp.
References genevalmag::attr_grammar, utilities::belong_index(), genevalmag::belong_it(), genevalmag::Symbol::equals(), genevalmag::Expr_instance::get_attr(), genevalmag::Rule::get_eq(), genevalmag::get_inherits_of(), genevalmag::Rule::get_left_symbol(), genevalmag::Rule::get_non_terminals_right_side(), genevalmag::Expr_instance::get_num(), genevalmag::Attr_grammar::get_rule(), genevalmag::Expr_instance::get_symb(), genevalmag::k_p_project::id_plan_project, genevalmag::k_p_project::index_ocurrence, genevalmag::ins_attr_computed(), genevalmag::Attribute::is_inherit(), genevalmag::Attribute::is_synthetize(), genevalmag::LEAVE(), genevalmag::merge_vec(), genevalmag::merge_vec_without_plan(), genevalmag::plan_family_computed(), and genevalmag::k_p_project::symbol_project.
Referenced by generate_visit_sequences().
bool genevalmag::Builder_visit_sequences::generate_visit_sequences ()
Generates a visit sequence for each evaluation plan.
Returns:
Generates a visit sequence for each evaluation plan.
Definition at line 358 of file Builder_visit_sequences.cpp.
References all_visit_seqs, attr_grammar, b_plans, utilities::belong_index(), genevalmag::Symbol::equals(), gen_visit_seq(), genevalmag::Builder_plans::get_context_unique(), genevalmag::Attr_grammar::get_initial_symb(), genevalmag::Rule::get_left_symbol(), genevalmag::Builder_plans::get_plans(), genevalmag::Builder_plans::get_plans_uniques(), genevalmag::Attr_grammar::get_rule(), genevalmag::merge_vec(), and genevalmag::plan_family_computed().
const vector< Visit_seq > & genevalmag::Builder_visit_sequences::get_visit_seq () const
Returns the vector with all visit sequences generates.
Returns:
Returns the vector with all visit sequences generates.
Definition at line 393 of file Builder_visit_sequences.cpp.
References all_visit_seqs.
Referenced by genevalmag::Builder_code::generate_initialize_v_seq().
void genevalmag::Builder_visit_sequences::print_all_visit_sequences () const
Print in console, all visit sequences generates.
Definition at line 401 of file Builder_visit_sequences.cpp.
References all_visit_seqs.
void genevalmag::Builder_visit_sequences::update_visit_sequence (const Visit_seq & sequence, const size_t i_plan) [private]
Updates the visit sequence generate, mixing with pre-generated visit sequences.
Parameters:
sequence
i_plan Update the visit sequence generate, mixing with pre-generated visit sequences.
Definition at line 317 of file Builder_visit_sequences.cpp.
References all_visit_seqs.
Member Data Documentation
genevalmag::Builder_visit_sequences::all_visit_seqs [private]
Stores all visit sequences generates.
Definition at line 49 of file Builder_visit_sequences.h.
Referenced by generate_visit_sequences(), get_visit_seq(), print_all_visit_sequences(), and update_visit_sequence().
genevalmag::Builder_visit_sequences::attr_grammar [private]
References to the attribute grammar.
Definition at line 43 of file Builder_visit_sequences.h.
Referenced by generate_visit_sequences().
genevalmag::Builder_visit_sequences::b_plans [private]
References to all plans generates.
Definition at line 37 of file Builder_visit_sequences.h.
Referenced by generate_visit_sequences().
The documentation for this class was generated from the following files:
include/Builders/Builder_visit_sequences.h
src/Builders/Builder_visit_sequences.cpp