genevalmag::Symbol Class Reference
#include <Symbol.h>
Public Member Functions
Symbol ()
Symbol (const string &name, const symbol_type &type)
Symbol (const Symbol &other)
virtual ~Symbol ()
Symbol & operator= (const Symbol &other)
string get_name () const
symbol_type get_type () const
unsigned short get_id () const
const vector< const Attribute * > & get_attrs () const
const Attribute * get_attribute (const string &name_attr) const
void set_name (const string name)
void set_type (const symbol_type type)
void set_id (unsigned short id)
void add_attr (const Attribute *attr)
const bool is_non_terminal () const
string to_string () const
bool equals (const Symbol &other) const
string key () const
Private Member Functions
void copy (const Symbol &other)
void destroy ()
Private Attributes
string symb_name
Symbol's name.
symbol_type symb_type
Symbol's type.
vector< const Attribute * > symb_attrs
Symbol's vector attribute.
unsigned short symb_id
Symbol's identifier.
Detailed Description
Definition at line 29 of file Symbol.h.
Constructor & Destructor Documentation
genevalmag::Symbol::Symbol ()
Constructor empty of Symbol.
Definition at line 19 of file Symbol.cpp.
genevalmag::Symbol::Symbol (const string & name, const symbol_type & type)
Constructor with name and type of Symbol.
Parameters:
name
type
Returns:
Constructor with name and type of Symbol.
Definition at line 26 of file Symbol.cpp.
References symb_id, symb_name, and symb_type.
genevalmag::Symbol::Symbol (const Symbol & other)
Constructor copy of Symbol.
Parameters:
other
Returns:
Constructor copy of Symbol.
Definition at line 36 of file Symbol.cpp.
References copy().
genevalmag::Symbol::~Symbol () [virtual]
Destructor of Symbol.
Definition at line 44 of file Symbol.cpp.
References destroy().
Member Function Documentation
void genevalmag::Symbol::add_attr (const Attribute * attr)
Enqueues a attribute in the list of the Symbol.
Parameters:
attr Enqueues a attribute in the list of the symbol.
Definition at line 155 of file Symbol.cpp.
References symb_attrs.
Referenced by genevalmag::Attr_grammar::load_attributes().
void genevalmag::Symbol::copy (const Symbol & other) [private]
Method of copy the symbol, STL-like C++.
Parameters:
other Method of copy the Symbol, STL-like C++.
Definition at line 65 of file Symbol.cpp.
References get_attrs(), get_id(), get_name(), get_type(), symb_attrs, symb_id, symb_name, and symb_type.
Referenced by operator=(), and Symbol().
void genevalmag::Symbol::destroy () [private]
Method destroy symbol, STL-like C++.
Definition at line 76 of file Symbol.cpp.
Referenced by operator=(), and ~Symbol().
bool genevalmag::Symbol::equals (const Symbol & other) const
Compares the Symbol with other.
Parameters:
other
Returns:
Compares the symbol with other.
Definition at line 207 of file Symbol.cpp.
References key().
Referenced by genevalmag::Rule::belongs_non_terminal(), genevalmag::check_eq_defines_it(), genevalmag::Rule::count_non_terminal(), genevalmag::Rule::equals(), genevalmag::Builder_visit_sequences::gen_visit_seq(), genevalmag::generate_expr_text(), genevalmag::Builder_visit_sequences::generate_visit_sequences(), genevalmag::Builder_plans::generates_topological_order(), and utilities::project_graph().
const Attribute * genevalmag::Symbol::get_attribute (const string & name_attr) const
Finds in the list of attribute of the symbol and
 returns the attribute with that name passed as parameter.
Parameters:
name_attr
Returns:
Finds in the list of attribute of the symbol and returns the attribute with that name passed as parameter.
Definition at line 116 of file Symbol.cpp.
References get_name(), and symb_attrs.
Referenced by genevalmag::save_attr_ins().
const vector< const Attribute * > & genevalmag::Symbol::get_attrs () const
Returns the list of attributes of the Symbol.
Returns:
Returns the list of attributes of the symbol.
Definition at line 107 of file Symbol.cpp.
References symb_attrs.
Referenced by copy().
unsigned short genevalmag::Symbol::get_id () const
Returns the id of the Symbol.
Returns:
Returns the id of the symbol.
Definition at line 91 of file Symbol.cpp.
References symb_id.
Referenced by copy().
string genevalmag::Symbol::get_name () const
Returns the name of the Symbol.
Returns:
Returns the name of the symbol.
Definition at line 83 of file Symbol.cpp.
References symb_name.
Referenced by genevalmag::belong(), genevalmag::Semantics_checks::check_reachability(), copy(), genevalmag::Expr_instance::equals_without_index(), genevalmag::generate_expr_text(), get_attribute(), genevalmag::Expr_instance::key(), genevalmag::k_p_project::operator<(), genevalmag::k_p_project::operator==(), genevalmag::Builder_graphs::save_dcg_graphs(), genevalmag::save_index_ins(), genevalmag::Expr_instance::to_string(), to_string(), genevalmag::Attr_grammar::to_string(), and genevalmag::Rule::to_string_not_eqs().
symbol_type genevalmag::Symbol::get_type () const
Returns the type of the Symbol.
Returns:
Returns the type of the symbol.
Definition at line 99 of file Symbol.cpp.
References symb_type.
Referenced by copy().
const bool genevalmag::Symbol::is_non_terminal () const
Returns true if the Symbol's type is Non Terminal.
Returns:
Returns true if the symbol's type is non-terminal.
Definition at line 163 of file Symbol.cpp.
References genevalmag::k_non_terminal, and symb_type.
Referenced by genevalmag::Attr_grammar::add_symbol().
string genevalmag::Symbol::key () const
Generates and returns the string key that identifies a Symbol definitely.
 Result= <name>
Returns:
Generates and returns the string key that identifies a symbol definitely.
Result = name
Definition at line 217 of file Symbol.cpp.
References symb_name.
Referenced by genevalmag::Builder_graphs::compute_down_graph(), and equals().
Symbol & genevalmag::Symbol::operator= (const Symbol & other)
Operator assign(=) of Symbol.
Parameters:
other
Returns:
Operator assign(=) of Symbol.
Definition at line 52 of file Symbol.cpp.
References copy(), and destroy().
void genevalmag::Symbol::set_id (unsigned short id)
Sets the id of the Symbol.
Parameters:
id Sets the id of the symbol.
Definition at line 147 of file Symbol.cpp.
References symb_id.
void genevalmag::Symbol::set_name (const string name)
Sets the name of the Symbol.
Parameters:
name Sets the name of the symbol.
Definition at line 131 of file Symbol.cpp.
References symb_name.
void genevalmag::Symbol::set_type (const symbol_type type)
Sets the type of the Symbol.
Parameters:
type Sets the type of the symbol.
Definition at line 139 of file Symbol.cpp.
References symb_type.
string genevalmag::Symbol::to_string () const
Generates and returns a string reprensentation of a Symbol.
 Result= `symbol` <name> <type> `;`
 where if <type> is Non Terminal, then list the attributes of the symbol.
 list = `Attributes:` attr_1 `,` ... `,` attr_n
Returns:
Generates and returns a string reprensentation of a symbol.
Result = `symbol` name type `;`
where if 'type' is Non Terminal, then list the attributes of the symbol.
list = `Attributes:` attr_1 `,` ... `,` attr_n
Definition at line 177 of file Symbol.cpp.
References get_name(), genevalmag::k_non_terminal, genevalmag::k_terminal, symb_attrs, symb_name, and symb_type.
Member Data Documentation
genevalmag::Symbol::symb_attrs [private]
Symbol's vector attribute.
Definition at line 46 of file Symbol.h.
Referenced by add_attr(), copy(), get_attribute(), get_attrs(), and to_string().
genevalmag::Symbol::symb_id [private]
Symbol's identifier.
Definition at line 51 of file Symbol.h.
Referenced by copy(), get_id(), set_id(), and Symbol().
genevalmag::Symbol::symb_name [private]
Symbol's name.
Definition at line 36 of file Symbol.h.
Referenced by copy(), get_name(), key(), set_name(), Symbol(), and to_string().
genevalmag::Symbol::symb_type [private]
Symbol's type.
Definition at line 41 of file Symbol.h.
Referenced by copy(), get_type(), is_non_terminal(), set_type(), Symbol(), and to_string().
The documentation for this class was generated from the following files:
include/Attr_grammar/Symbol.h
src/Attr_grammar/Symbol.cpp