genevalmag::Semantics_checks Class Reference
#include <Semantics_checks.h>
Public Member Functions
Semantics_checks ()
~Semantics_checks ()
unsigned short get_precedence_level () const
unsigned short get_index_syntax_order () const
void increment_precedence_level ()
void decrement_precedence_level ()
void increment_index_syntax_order ()
void reset_semantic_context ()
void correct_precedence (Expr_function **root_tree)
void correct_associativity (Expr_function **root_tree)
bool check_all_defined_non_terminal (const map< unsigned short, Rule > &rules, const map< string, Symbol > &non_terminals)
bool check_reachability (const map< unsigned short, Rule > &rules, const map< string, Symbol > &non_terminals, const Symbol *init_symbol)
bool check_well_defined_AG (const map< unsigned short, Rule > &rules)
Private Member Functions
void correct_subtree (Expr_function **subtree, int index_root_subtree)
Private Attributes
unsigned short precedence_level
unsigned short index_syntax_order
Counter of syntax order.
Detailed Description
Definition at line 22 of file Semantics_checks.h.
Constructor & Destructor Documentation
genevalmag::Semantics_checks::Semantics_checks ()
Contructor empty of Semantics checks.
Contructor empty of Semantic check.
Definition at line 24 of file Semantics_checks.cpp.
References index_syntax_order, and precedence_level.
genevalmag::Semantics_checks::~Semantics_checks ()
Destructor of Semantics checks.
Destructor of Semantic check.
Definition at line 33 of file Semantics_checks.cpp.
Member Function Documentation
bool genevalmag::Semantics_checks::check_all_defined_non_terminal (const map< unsigned short, Rule > & rules, const map< string, Symbol > & non_terminals)
Verifies that all non-terminals in the grammar has defines in a rule. That is, it is the left value of some rule of grammar.
Parameters:
rules
non_terminals
Returns:
Verifies that all non-terminals in the grammar has defines in a rule. That is, it is the left value of some rule of grammar.
Definition at line 337 of file Semantics_checks.cpp.
Referenced by genevalmag::check_well_defined().
bool genevalmag::Semantics_checks::check_reachability (const map< unsigned short, Rule > & rules, const map< string, Symbol > & non_terminals, const Symbol * init_symbol)
Computes the boolean adjacency matrix of all the rules of the attributes grammar, then computes the Warshall algorithm for transitive closure and thus can identify from the initial symbol all symbols reachable.
Parameters:
rules
non_terminals
init_symbol
Returns:
Computes the boolean adjacency matrix of all the rules of the attributes grammar, then computes the Warshall algorithm for transitive closure and thus can identify from the initial symbol all symbols reachable.
Definition at line 406 of file Semantics_checks.cpp.
References genevalmag::get_index(), genevalmag::Symbol::get_name(), and genevalmag::warshall_algorithm().
Referenced by genevalmag::check_well_defined().
bool genevalmag::Semantics_checks::check_well_defined_AG (const map< unsigned short, Rule > & rules)
Checks that all synthetized attributes of the left symbols of all rule are defined with an equation. And all inherit attributes of all right symbol too.
Parameters:
rules
Returns:
Checks that all synthetized attributes of the left symbols of all rule are defined with an equation. And all inherit attributes of all right symbol too.
Definition at line 487 of file Semantics_checks.cpp.
References genevalmag::check_eq_defines_it().
Referenced by genevalmag::check_well_defined().
void genevalmag::Semantics_checks::correct_associativity (Expr_function ** root_tree)
Controls around the tree, that any operator who applies more than once on the same level is associated according to the signature. If it detects conflicts modifying the expression tree with rotations and resources to continue controlling.
Parameters:
root_tree Controls around the tree, that any operator who applies more than once on the same level is associated according to the signature. If it detects conflicts modifying the expression tree with rotations and resources to continue controlling.
Definition at line 291 of file Semantics_checks.cpp.
References genevalmag::Expr_function::get_function(), genevalmag::k_non_assoc, genevalmag::k_right, and genevalmag::swap_root_child().
Referenced by genevalmag::save_rvalue().
void genevalmag::Semantics_checks::correct_precedence (Expr_function ** root_tree)
Checking from the root of the expression tree to the leaves, which all operators are applies according to their precedence. If there are conflicts resolves them doing rotations, leaving the operator with lower precedence, as the new root.
Obs: The following checks are performed and only make changes in the structure of the tree, if it fulfills the following three conditions:
Operations that are changed are at the same level of precedence (with respect wiht parentheses).
The syntactic order of the expression is not altered.
The operation with higher precedence apply first.
Parameters:
root_tree Checking from the root of the expression tree to the leaves, which all operators are applies according to their precedence. If there are conflicts resolves them doing rotations, leaving the operator with lower precedence, as the new root.
Obs: The following checks are performed and only make changes in the structure of the tree, if it fulfills the following three conditions:
Operations that are changed are at the same level of precedence (with respect wiht parentheses).
The syntactic order of the expression is not altered.
The operation with higher precedence apply first.
Definition at line 209 of file Semantics_checks.cpp.
References correct_subtree(), genevalmag::Expr_function::get_function(), genevalmag::Function::get_prec(), genevalmag::Expr_function::is_postfix(), genevalmag::Expr_function::is_prefix(), genevalmag::swap_root_child(), and genevalmag::swap_root_grandson().
Referenced by correct_subtree(), genevalmag::create_root_infix_node(), genevalmag::create_root_postfix_node(), and genevalmag::create_root_prefix_node().
void genevalmag::Semantics_checks::correct_subtree (Expr_function ** subtree, int index_root_subtree) [private]
Check and correct the precendence of the operator in a subtree.
Parameters:
subtree
index_root_subtree Checks and correct the precendence of the operator in a subtree.
Definition at line 172 of file Semantics_checks.cpp.
References correct_precedence(), and genevalmag::swap_root_child().
Referenced by correct_precedence().
void genevalmag::Semantics_checks::decrement_precedence_level ()
Decrements the level because a parenthesis closing.
Definition at line 64 of file Semantics_checks.cpp.
References precedence_level.
Referenced by genevalmag::decrement_level().
unsigned short genevalmag::Semantics_checks::get_index_syntax_order () const
Returns the current index of the syntax order.
Returns:
Returns the current index of the syntax order.
Definition at line 48 of file Semantics_checks.cpp.
References index_syntax_order.
Referenced by genevalmag::create_func_node().
unsigned short genevalmag::Semantics_checks::get_precedence_level () const
Returns the precedence level.
Returns:
Returns the precedence level.
Definition at line 40 of file Semantics_checks.cpp.
References precedence_level.
Referenced by genevalmag::create_func_node().
void genevalmag::Semantics_checks::increment_index_syntax_order ()
Increments the syntax order global.
Definition at line 72 of file Semantics_checks.cpp.
References index_syntax_order.
Referenced by genevalmag::create_func_node().
void genevalmag::Semantics_checks::increment_precedence_level ()
Increments the level because a new parenthesis opening.
Definition at line 56 of file Semantics_checks.cpp.
References precedence_level.
Referenced by genevalmag::increment_level().
void genevalmag::Semantics_checks::reset_semantic_context ()
Resets all variables that affect in the precedence analisys.
Definition at line 80 of file Semantics_checks.cpp.
References index_syntax_order, and precedence_level.
Referenced by genevalmag::save_rvalue().
Member Data Documentation
genevalmag::Semantics_checks::index_syntax_order [private]
Counter of syntax order.
Definition at line 35 of file Semantics_checks.h.
Referenced by get_index_syntax_order(), increment_index_syntax_order(), reset_semantic_context(), and Semantics_checks().
unsigned short genevalmag::Semantics_checks::precedence_level [private]
Definition at line 29 of file Semantics_checks.h.
Referenced by decrement_precedence_level(), get_precedence_level(), increment_precedence_level(), reset_semantic_context(), and Semantics_checks().
The documentation for this class was generated from the following files:
include/Parser/Semantics_checks.h
src/Parser/Semantics_checks.cpp