genevalmag::Expr_literal Class Reference
#include <Expr_literal.h>
Inherits genevalmag::Expr_leaf.
Public Member Functions
Expr_literal ()
Expr_literal (const Expr_literal &other)
virtual ~Expr_literal ()
Expr_literal & operator= (const Expr_literal &other)
literal_type get_type () const
string get_value () const
void set_type (literal_type new_type)
void set_value (string new_value)
string to_string () const
Private Member Functions
void copy (const Expr_literal &other)
void destroy ()
Private Attributes
string value
literal value.
literal_type type
literal type: this type may be k_int, k_float, k_char, k_string.
Detailed Description
Definition at line 29 of file Expr_literal.h.
Constructor & Destructor Documentation
genevalmag::Expr_literal::Expr_literal ()
Constructor empty of Expr_literal.
Returns:
Constructor empty of Expr_literal.
Definition at line 23 of file Expr_literal.cpp.
genevalmag::Expr_literal::Expr_literal (const Expr_literal & other)
Constructor copy of Expr_literal.
Parameters:
other
Returns:
Constructor copy of Expr_literal.
Definition at line 33 of file Expr_literal.cpp.
References copy().
genevalmag::Expr_literal::~Expr_literal () [virtual]
Destructor of Expr_literal.
Returns:
Destructor of Expr_literal.
Definition at line 45 of file Expr_literal.cpp.
References destroy().
Member Function Documentation
void genevalmag::Expr_literal::copy (const Expr_literal & other) [private]
Method of copy the Expr_literal, STL-like C++.
Parameters:
other Method of copy the Expr_literal, STL-like C++.
Definition at line 74 of file Expr_literal.cpp.
References genevalmag::Expression::conflict, genevalmag::Expression::get_conflict(), genevalmag::Expression::get_parent(), get_type(), genevalmag::Expression::get_type_synthetized(), get_value(), genevalmag::Expression::parent, type, genevalmag::Expression::type_synthetized, and value.
Referenced by Expr_literal(), and operator=().
void genevalmag::Expr_literal::destroy () [private]
Method destroy Expr_literal, STL-like C++.
Definition at line 86 of file Expr_literal.cpp.
Referenced by operator=(), and ~Expr_literal().
literal_type genevalmag::Expr_literal::get_type () const
Returns the type of the Expr_literal.
Returns:
Returns the type of the Expr_literal.
Definition at line 93 of file Expr_literal.cpp.
References type.
Referenced by copy().
string genevalmag::Expr_literal::get_value () const
Returns the value of the Expr_literal.
Returns:
Returns the value of the Expr_literal.
Definition at line 101 of file Expr_literal.cpp.
References value.
Referenced by copy().
Expr_literal & genevalmag::Expr_literal::operator= (const Expr_literal & other)
Operator assign(=) of Expr_literal.
Parameters:
other
Returns:
Operator assign(=) of Expr_literal.
Definition at line 61 of file Expr_literal.cpp.
References copy(), and destroy().
void genevalmag::Expr_literal::set_type (literal_type new_type)
Sets the type of the Expr_literal.
Parameters:
new_type Sets the type of the Expr_literal.
Definition at line 109 of file Expr_literal.cpp.
References type.
Referenced by genevalmag::create_bool(), genevalmag::create_lit_ch(), genevalmag::create_lit_number(), and genevalmag::create_lit_str().
void genevalmag::Expr_literal::set_value (string new_value)
Sets the value of the Expr_literal.
Parameters:
new_value Sets the value of the Expr_literal.
Definition at line 117 of file Expr_literal.cpp.
References value.
Referenced by genevalmag::create_bool(), genevalmag::create_lit_ch(), genevalmag::create_lit_number(), genevalmag::create_lit_str(), and genevalmag::push_mark().
string genevalmag::Expr_literal::to_string () const [virtual]
Generate and return a string reprensentation of a Expr_literal.
 Result= literal
 Ex: 1 -> int, short or long
 1.0 -> float or double
 '1' -> char or wchar_t
 `1` -> string
 true -> bool
Returns:
Generate and return a string reprensentation of a Expr_literal.
Result= literal
Ex: 1 -> int 1.0 -> float '1' -> char `1` -> string
Implements genevalmag::Expr_leaf.
Definition at line 132 of file Expr_literal.cpp.
References genevalmag::k_bool, genevalmag::k_char, genevalmag::k_float, genevalmag::k_int, genevalmag::k_string, type, and value.
Referenced by genevalmag::generate_expr_text().
Member Data Documentation
genevalmag::Expr_literal::type [private]
literal type: this type may be k_int, k_float, k_char, k_string.
Definition at line 41 of file Expr_literal.h.
Referenced by copy(), get_type(), set_type(), and to_string().
genevalmag::Expr_literal::value [private]
literal value.
Definition at line 36 of file Expr_literal.h.
Referenced by copy(), get_value(), set_value(), and to_string().
The documentation for this class was generated from the following files:
include/Expression_tree/Expr_literal.h
src/Expression_tree/Expr_literal.cpp