genevalmag::Attribute Class Reference
#include <Attribute.h>
Public Member Functions
Attribute ()
Attribute (const Attribute &other)
virtual ~Attribute ()
Attribute & operator= (const Attribute &other)
const string get_name () const
const Sort * get_sort_type () const
const type_attr get_mod_type () const
const string get_member_symbol () const
void set_name (const string name)
void set_sort_type (const Sort *sort_type)
void set_mod_type (const type_attr mod_type)
void set_member_symbol (const string member_symbol)
const bool is_synthetize () const
const bool is_inherit () const
const string to_string () const
const bool equals (const Attribute &other) const
const string key () const
Private Member Functions
void copy (const Attribute &other)
void destroy ()
Private Attributes
string a_name
Attribute's name.
const Sort * a_sort_type
Attribute's type sort.
type_attr a_mod_type
Attribute's type.
string a_member_symbol
Attribute's member list.
Detailed Description
Definition at line 26 of file Attribute.h.
Constructor & Destructor Documentation
genevalmag::Attribute::Attribute ()
Constructor empty of attribute.
Definition at line 20 of file Attribute.cpp.
genevalmag::Attribute::Attribute (const Attribute & other)
Constructor copy of attribute.
Parameters:
other
Returns:
Constructor copy of attribute.
Definition at line 27 of file Attribute.cpp.
References copy().
genevalmag::Attribute::~Attribute () [virtual]
Destructor of attribute.
Definition at line 35 of file Attribute.cpp.
References destroy().
Member Function Documentation
void genevalmag::Attribute::copy (const Attribute & other) [private]
Method of copy the attribute, STL-like C++.
Parameters:
other Method of copy the attribute, STL-like.
Definition at line 56 of file Attribute.cpp.
References a_member_symbol, a_mod_type, a_name, a_sort_type, get_member_symbol(), get_mod_type(), get_name(), and get_sort_type().
Referenced by Attribute(), and operator=().
void genevalmag::Attribute::destroy () [private]
Method destroy attribute, STL-like C++.
Method destroy the attribute, STL-like.
Definition at line 67 of file Attribute.cpp.
Referenced by operator=(), and ~Attribute().
const bool genevalmag::Attribute::equals (const Attribute & other) const
Compares the attribute with other.
Parameters:
other
Returns:
Compares the attribute with other.
Definition at line 181 of file Attribute.cpp.
References key().
Referenced by genevalmag::check_eq_defines_it().
const string genevalmag::Attribute::get_member_symbol () const
Returns the membership list of the attribute.
Returns:
Return the membership list of the attribute.
Definition at line 98 of file Attribute.cpp.
References a_member_symbol.
Referenced by copy().
const type_attr genevalmag::Attribute::get_mod_type () const
Returns the modifiers of the attribute.
Returns:
Return the modifiers of the attribute.
Definition at line 90 of file Attribute.cpp.
References a_mod_type.
Referenced by copy().
const string genevalmag::Attribute::get_name () const
Returns the name of the attribute.
Returns:
Return the name of the attribute.
Definition at line 74 of file Attribute.cpp.
References a_name.
Referenced by copy(), genevalmag::Expr_instance::equals_without_index(), genevalmag::generate_expr_text(), genevalmag::Expr_instance::key(), and genevalmag::Expr_instance::to_string().
const Sort * genevalmag::Attribute::get_sort_type () const
Returns the sort type of the attribute.
Returns:
Return the sort type of the attribute.
Definition at line 82 of file Attribute.cpp.
References a_sort_type.
Referenced by copy(), genevalmag::create_instance_node(), and genevalmag::save_rvalue().
const bool genevalmag::Attribute::is_inherit () const
Returns true if the modifiers of the attribute is inherit.
Returns:
Return true if the modifiers of the attribute is inherit.
Definition at line 146 of file Attribute.cpp.
References a_mod_type, and genevalmag::k_inherit.
Referenced by genevalmag::Builder_visit_sequences::gen_visit_seq(), and genevalmag::Builder_plans::generates_topological_order().
const bool genevalmag::Attribute::is_synthetize () const
Returns true if the modifiers of the attribute is synthetize.
Returns:
Return true if the modifiers of the attribute is synthetized.
Definition at line 138 of file Attribute.cpp.
References a_mod_type, and genevalmag::k_synthetize.
Referenced by genevalmag::Builder_visit_sequences::gen_visit_seq(), genevalmag::Attr_grammar::get_index_eq_with_context(), and to_string().
const string genevalmag::Attribute::key () const
Generates and returns the string key that identifies a attribute definitely.
 Result = name modifiers sort_type membership_list
Returns:
Generate and return the string key that identifies a attribute definitely.
Result= name modifiers sort_type membership_list
Definition at line 191 of file Attribute.cpp.
References a_member_symbol, a_name, a_sort_type, and genevalmag::Sort::get_name().
Referenced by equals().
Attribute & genevalmag::Attribute::operator= (const Attribute & other)
Operator assign(=) of attribute.
Parameters:
other
Returns:
Operator assign(=) of attribute.
Definition at line 43 of file Attribute.cpp.
References copy(), and destroy().
void genevalmag::Attribute::set_member_symbol (const string member_symbol)
Sets the membership list of the attribute.
Parameters:
member_symbol Set the membership list of the attribute.
Definition at line 130 of file Attribute.cpp.
References a_member_symbol.
Referenced by genevalmag::create_attributes().
void genevalmag::Attribute::set_mod_type (const type_attr mod_type)
Sets the modifiers of the attribute.
Parameters:
mod_type Set the modifiers of the attribute.
Definition at line 122 of file Attribute.cpp.
References a_mod_type.
Referenced by genevalmag::create_attributes().
void genevalmag::Attribute::set_name (const string name)
Sets the name of the attribute.
Parameters:
name Set the name of the attribute.
Definition at line 106 of file Attribute.cpp.
References a_name.
Referenced by genevalmag::create_attributes().
void genevalmag::Attribute::set_sort_type (const Sort * sort_type)
Sets the sort type of the attribute.
Parameters:
sort_type Set the sort type of the attribute.
Definition at line 114 of file Attribute.cpp.
References a_sort_type.
Referenced by genevalmag::create_attributes().
const string genevalmag::Attribute::to_string () const
Generates and returns a string reprensentation of a attribute.
 Result = name `:` modifiers `<` sort_type [`(` instance `)` IF DEBUG IS ON] `> of ` membership_list
Returns:
Generate and return a string reprensentation of a attribute.
Result= name `:` modifiers `<` sort_type [`(` instance `)` IF DEBUG IS ON] `> of ` membership_list
Definition at line 156 of file Attribute.cpp.
References a_member_symbol, a_name, a_sort_type, genevalmag::Sort::get_name(), and is_synthetize().
Member Data Documentation
genevalmag::Attribute::a_member_symbol [private]
Attribute's member list.
Definition at line 48 of file Attribute.h.
Referenced by copy(), get_member_symbol(), key(), set_member_symbol(), and to_string().
genevalmag::Attribute::a_mod_type [private]
Attribute's type.
Definition at line 43 of file Attribute.h.
Referenced by copy(), get_mod_type(), is_inherit(), is_synthetize(), and set_mod_type().
genevalmag::Attribute::a_name [private]
Attribute's name.
Definition at line 33 of file Attribute.h.
Referenced by copy(), get_name(), key(), set_name(), and to_string().
genevalmag::Attribute::a_sort_type [private]
Attribute's type sort.
Definition at line 38 of file Attribute.h.
Referenced by copy(), get_sort_type(), key(), set_sort_type(), and to_string().
The documentation for this class was generated from the following files:
include/Attr_grammar/Attribute.h
src/Attr_grammar/Attribute.cpp