genevalmag::Attr_grammar Class Reference
#include <Attr_grammar.h>
Public Member Functions
Attr_grammar ()
virtual ~Attr_grammar ()
const bool add_sort (const Sort &sort)
const bool add_function (const Function &func)
const bool add_attribute (const Attribute &attr)
const bool add_symbol (const Symbol &symb)
const bool add_rule (Rule &rule)
const Sort & return_sort (const string name_sort)
const map< string, Sort > & get_sorts () const
const Function * get_function (const string key_function) const
const map< string, Function > & get_functions () const
const Symbol & get_symbol (const string name_symbol) const
const map< unsigned short, Rule > & get_rules () const
const Rule & get_rule (const unsigned short index) const
const map< string, Symbol > & get_non_terminal_symbols () const
const Symbol * get_initial_symb () const
const vector< unsigned short > get_rules_with_left_symbol (const Symbol *symb) const
const unsigned short get_index_eq_with_context (const Expr_instance *ins, const vector< unsigned short > &context_rule) const
const Equation * get_eq (const unsigned short index) const
const Expr_instance * get_eq_l_value (const unsigned short index) const
const unsigned short get_count_eqs () const
const string to_string () const
Private Member Functions
void load_attributes (Symbol &symb) const
const bool defined_rule (const Rule &rule) const
Private Attributes
map< string, Sort > ag_sort
map< string, Function > ag_func
map< string, Attribute > ag_attr
map< string, Symbol > ag_symb_terminals
map< string, Symbol > ag_symb_non_terminals
map< unsigned short, Rule > ag_rule
unsigned short count_eqs
Store the count of equations in the gramamar.
const Symbol * ag_initial_symb
Saves the name of the initial symbol of the grammar's attribute.
Detailed Description
Definition at line 25 of file Attr_grammar.h.
Constructor & Destructor Documentation
genevalmag::Attr_grammar::Attr_grammar ()
Contructor empty of semantic domain.
Contructor empty of attribute grammar.
Initialice values.
Definition at line 22 of file Attr_grammar.cpp.
References ag_initial_symb, and count_eqs.
genevalmag::Attr_grammar::~Attr_grammar () [virtual]
Destructor of the semantic domain.
Destructor of the attribute grammar.
Definition at line 32 of file Attr_grammar.cpp.
Member Function Documentation
const bool genevalmag::Attr_grammar::add_attribute (const Attribute & attr)
Enqueues a attribute in the list of the semantic domain.
Parameters:
attr
Returns:
Enqueues a attribute in the list of the attribute grammar.
Definition at line 85 of file Attr_grammar.cpp.
References ag_attr.
Referenced by genevalmag::create_attributes().
const bool genevalmag::Attr_grammar::add_function (const Function & func)
Enqueues a function in the list of the semantic domain.
Parameters:
func
Returns:
Enqueues a function in the list of the attribute grammar.
Definition at line 77 of file Attr_grammar.cpp.
References ag_func.
Referenced by genevalmag::add_function().
const bool genevalmag::Attr_grammar::add_rule (Rule & rule)
Enqueues a rule in the list of the semantic domain.
Parameters:
rule
Returns:
Enqueues a rule in the list of the attribute grammar.
Definition at line 183 of file Attr_grammar.cpp.
References ag_initial_symb, ag_rule, genevalmag::Rule::belongs_non_terminal(), count_eqs, defined_rule(), genevalmag::Rule::get_eqs(), genevalmag::Rule::get_left_symbol(), and genevalmag::Rule::set_id().
Referenced by genevalmag::save_rule().
const bool genevalmag::Attr_grammar::add_sort (const Sort & sort)
Enqueues a sort in the list of the semantic domain.
Parameters:
sort
Returns:
Enqueues a sort in the list of the attribute grammar.
Definition at line 69 of file Attr_grammar.cpp.
References ag_sort.
Referenced by genevalmag::create_sort(), and return_sort().
const bool genevalmag::Attr_grammar::add_symbol (const Symbol & symb)
Enqueues a symbol in the list of the semantic domain.
Parameters:
symb
Returns:
Enqueues a symbol in the list of the attribute grammar.
Definition at line 142 of file Attr_grammar.cpp.
References ag_symb_non_terminals, ag_symb_terminals, genevalmag::Symbol::is_non_terminal(), and load_attributes().
Referenced by genevalmag::create_new_non_terminal(), and genevalmag::create_new_terminal().
const bool genevalmag::Attr_grammar::defined_rule (const Rule & rule) const [private]
Checks that the rule is not already defined in the grammar.
Parameters:
rule
Returns:
Checks that the rule is not already defined in the grammar.
Definition at line 168 of file Attr_grammar.cpp.
References ag_rule.
Referenced by add_rule().
const unsigned short genevalmag::Attr_grammar::get_count_eqs () const
Returns the count of equations in the grammar.
Returns:
Returns the count of equations in the grammar.
Definition at line 397 of file Attr_grammar.cpp.
References count_eqs.
Referenced by genevalmag::Builder_code::generate_all_compute_eq().
const Equation * genevalmag::Attr_grammar::get_eq (const unsigned short index) const
Returns the equation with this index.
Parameters:
index
Returns:
Returns the equation with this index.
Definition at line 367 of file Attr_grammar.cpp.
References ag_rule, and count_eqs.
Referenced by get_eq_l_value(), genevalmag::Builder_plans::save_all_plans(), and genevalmag::Builder_plans::save_all_plans_project().
const Expr_instance * genevalmag::Attr_grammar::get_eq_l_value (const unsigned short index) const
Returns the l_value of the equation with this index.
Parameters:
index
Returns:
Returns the l_value of the equation with this index.
Definition at line 387 of file Attr_grammar.cpp.
References get_eq(), and genevalmag::Equation::get_l_value().
Referenced by genevalmag::Builder_plans::compute_order().
const Function * genevalmag::Attr_grammar::get_function (const string key_function) const
Finds in the list of function of the semantic domain and returns the function with that name.
Parameters:
key_function
Returns:
Finds in the list of function of the attribute grammar and returns the function with that name.
Definition at line 246 of file Attr_grammar.cpp.
References ag_func.
Referenced by genevalmag::create_root_function_node(), genevalmag::create_root_infix_node(), genevalmag::create_root_postfix_node(), and genevalmag::create_root_prefix_node().
const map< string, Function > & genevalmag::Attr_grammar::get_functions () const
Returns the map with all functions.
Returns:
Returns the map with all functions.
Definition at line 259 of file Attr_grammar.cpp.
References ag_func.
const unsigned short genevalmag::Attr_grammar::get_index_eq_with_context (const Expr_instance * ins, const vector< unsigned short > & context_rule) const
Returns the index of an equation in this range of rules with l_value equals to ins.
Parameters:
ins
context_rule
Returns:
Returns the index of an equation in this range of rules with l_value equals to ins.
Definition at line 329 of file Attr_grammar.cpp.
References ag_rule, genevalmag::Expr_instance::get_attr(), genevalmag::Expr_instance::get_num(), and genevalmag::Attribute::is_synthetize().
Referenced by genevalmag::Builder_plans::generates_topological_order().
const Symbol * genevalmag::Attr_grammar::get_initial_symb () const
Returns the initial rule.
Returns:
Returns the initial symbol.
Definition at line 304 of file Attr_grammar.cpp.
References ag_initial_symb.
Referenced by genevalmag::check_well_defined(), and genevalmag::Builder_visit_sequences::generate_visit_sequences().
const map< string, Symbol > & genevalmag::Attr_grammar::get_non_terminal_symbols () const
Returns the map with all symbols.
Returns:
Returns the map with all symbols.
Definition at line 296 of file Attr_grammar.cpp.
References ag_symb_non_terminals.
Referenced by genevalmag::check_well_defined(), genevalmag::Builder_graphs::compute_attr_vertex(), and genevalmag::Builder_code::generate_structs().
const Rule & genevalmag::Attr_grammar::get_rule (const unsigned short index) const
Returns the rule on paramenter.
Parameters:
index
Returns:
Returns the rule on paramenter.
Definition at line 288 of file Attr_grammar.cpp.
References ag_rule.
Referenced by genevalmag::Builder_visit_sequences::gen_visit_seq(), genevalmag::Builder_plans::generate_plans(), genevalmag::Builder_visit_sequences::generate_visit_sequences(), and genevalmag::Builder_plans::generates_topological_order().
const map< unsigned short, Rule > & genevalmag::Attr_grammar::get_rules () const
Returns the map with all rules.
Returns:
Returns the map with all rules.
Definition at line 280 of file Attr_grammar.cpp.
References ag_rule.
Referenced by genevalmag::check_well_defined(), genevalmag::Builder_graphs::complete_dp_graphs(), genevalmag::Builder_graphs::compute_adp_graph(), genevalmag::Builder_graphs::compute_dcg(), genevalmag::Builder_graphs::compute_dependency_graphs(), genevalmag::Builder_graphs::compute_down_graph(), genevalmag::Builder_code::generate_all_methods_eqs(), genevalmag::Builder_code::generate_initialize_rules(), genevalmag::Builder_plans::generate_plans(), genevalmag::Builder_graphs::save_adp_graphs(), genevalmag::Builder_plans::save_all_plans(), genevalmag::Builder_plans::save_all_plans_project(), genevalmag::Builder_graphs::save_cyclic_graphs(), genevalmag::Builder_graphs::save_dcg_graphs(), and genevalmag::Builder_graphs::save_dp_graphs().
const vector< unsigned short > genevalmag::Attr_grammar::get_rules_with_left_symbol (const Symbol * symb) const
Returns vector with all rules with the left symbol equal that parameter.
Parameters:
symb
Returns:
Returns vector with all rules with the left symbol equal that parameter.
Definition at line 312 of file Attr_grammar.cpp.
References ag_rule.
Referenced by genevalmag::Builder_graphs::compute_adp_graph().
const map< string, Sort > & genevalmag::Attr_grammar::get_sorts () const
Returns the map with all sorts.
Returns:
Returns the map with all sorts.
Definition at line 238 of file Attr_grammar.cpp.
References ag_sort.
const Symbol & genevalmag::Attr_grammar::get_symbol (const string name_symbol) const
Finds in the list of symbol of the semantic domain and returns the symbol with that name.
Parameters:
name_symbol
Returns:
Finds in the list of operator of the attribute grammar and returns the operator with that name.
Definition at line 267 of file Attr_grammar.cpp.
References ag_symb_non_terminals, and ag_symb_terminals.
Referenced by genevalmag::create_instance(), genevalmag::create_rule(), and genevalmag::save_right_side_rule().
void genevalmag::Attr_grammar::load_attributes (Symbol & symb) const [private]
Insert the attributes belong the symbol.
Parameters:
symb Inserts the attributes belong the symbol.
Definition at line 128 of file Attr_grammar.cpp.
References genevalmag::Symbol::add_attr(), ag_attr, and genevalmag::belong().
Referenced by add_symbol().
const Sort & genevalmag::Attr_grammar::return_sort (const string name_sort)
Finds in the list of sort of the semantic domain and returns the sort with that name.
Parameters:
name_sort
Returns:
Finds in the list of sort of the attribute grammar and returns the sort with that name.
Definition at line 225 of file Attr_grammar.cpp.
References add_sort(), ag_sort, and genevalmag::Sort::set_type_basic().
Referenced by genevalmag::create_attributes(), genevalmag::save_domain_func(), and genevalmag::save_image_func().
const string genevalmag::Attr_grammar::to_string () const
Generates and returns a string reprensentation of a semantic domain.
 Result = `semantic domain`
 <sorts>
 <operators>
 <functions>
 `attributes`
 <attributes>
 [This section is commented so that it can be parsed again.]
 ***********************************************************
 `symbols`
 <symbols>
 ***********************************************************
 `rules`
 <rules>
 where <sorts>, <operators>, <functions>, <attributes>, <symbols> and <rules>,
 are a full representation of each type.
Returns:
Generates and returns a string reprensentation of a attribute grammar. where sorts, operators, functions, attributes, symbols and rules, are full representation of each type.
Definition at line 407 of file Attr_grammar.cpp.
References ag_attr, ag_func, ag_initial_symb, ag_rule, ag_sort, ag_symb_non_terminals, ag_symb_terminals, and genevalmag::Symbol::get_name().
Referenced by genevalmag::Parser_AG::save_grammar_file().
Member Data Documentation
map<string, Attribute> genevalmag::Attr_grammar::ag_attr [private]
Definition at line 39 of file Attr_grammar.h.
Referenced by add_attribute(), load_attributes(), and to_string().
map<string, Function> genevalmag::Attr_grammar::ag_func [private]
Definition at line 38 of file Attr_grammar.h.
Referenced by add_function(), get_function(), get_functions(), and to_string().
genevalmag::Attr_grammar::ag_initial_symb [private]
Saves the name of the initial symbol of the grammar's attribute.
Definition at line 54 of file Attr_grammar.h.
Referenced by add_rule(), Attr_grammar(), get_initial_symb(), and to_string().
map<unsigned short, Rule> genevalmag::Attr_grammar::ag_rule [private]
Definition at line 42 of file Attr_grammar.h.
Referenced by add_rule(), defined_rule(), get_eq(), get_index_eq_with_context(), get_rule(), get_rules(), get_rules_with_left_symbol(), and to_string().
map<string, Sort> genevalmag::Attr_grammar::ag_sort [private]
Definition at line 37 of file Attr_grammar.h.
Referenced by add_sort(), get_sorts(), return_sort(), and to_string().
map<string, Symbol> genevalmag::Attr_grammar::ag_symb_non_terminals [private]
Definition at line 41 of file Attr_grammar.h.
Referenced by add_symbol(), get_non_terminal_symbols(), get_symbol(), and to_string().
map<string, Symbol> genevalmag::Attr_grammar::ag_symb_terminals [private]
Definition at line 40 of file Attr_grammar.h.
Referenced by add_symbol(), get_symbol(), and to_string().
genevalmag::Attr_grammar::count_eqs [private]
Store the count of equations in the gramamar.
Definition at line 48 of file Attr_grammar.h.
Referenced by add_rule(), Attr_grammar(), get_count_eqs(), and get_eq().
The documentation for this class was generated from the following files:
include/Attr_grammar/Attr_grammar.h
src/Attr_grammar/Attr_grammar.cpp