genevalmag::Rule Class Reference
#include <Rule.h>
Public Member Functions
Rule ()
Rule (const Rule &other)
virtual ~Rule ()
Rule & operator= (const Rule &other)
const Symbol * get_left_symbol () const
const vector< const Symbol * > & get_right_side () const
const map< unsigned short, Equation > & get_eqs () const
const size_t get_number_eqs () const
const Equation * get_eq (const unsigned short index) const
const unsigned short get_offset () const
const int count_non_terminal (const Symbol *symb) const
const bool belongs_non_terminal (const Symbol &non_term) const
const vector< const Symbol * > get_non_terminals_right_side () const
void set_id (const unsigned short id)
void set_left_symbol (const Symbol *left_symb)
void add_right_symbol (const Symbol *right_symb)
const bool add_eq (Equation &eq)
const string to_string () const
const string to_string_not_eqs () const
const bool equals (const Rule &other) const
const unsigned short key () const
Private Member Functions
void copy (const Rule &other)
void destroy ()
const bool defined_equation (const Equation &eq) const
Private Attributes
unsigned short r_id
Rule's identifier.
const Symbol * r_left_symbol
Rule's left symbol.
vector< const Symbol * > r_right_side
Rule's vector of right symbols.
map< unsigned short, Equation > r_eqs
Rule's map of equations.
unsigned short r_offset
Rule's offset.
Detailed Description
Definition at line 20 of file Rule.h.
Constructor & Destructor Documentation
genevalmag::Rule::Rule ()
Constructor empty of rule.
Definition at line 25 of file Rule.cpp.
References r_offset.
genevalmag::Rule::Rule (const Rule & other)
Constructor copy of rule.
Parameters:
other
Returns:
Constructor copy of rule.
Definition at line 33 of file Rule.cpp.
References copy().
genevalmag::Rule::~Rule () [virtual]
Destructor of rule.
Definition at line 41 of file Rule.cpp.
References destroy().
Member Function Documentation
const bool genevalmag::Rule::add_eq (Equation & eq)
Enqueues a equation in the list of the rule.
Parameters:
eq
Returns:
Enqueues a equation in the list of the rule.
Definition at line 195 of file Rule.cpp.
References defined_equation(), get_number_eqs(), r_eqs, r_offset, and genevalmag::Equation::set_id().
Referenced by genevalmag::save_rvalue().
void genevalmag::Rule::add_right_symbol (const Symbol * right_symb)
Enqueues a symbol in the right side of the rule.
Parameters:
right_symb Enqueues a symbol in the right side of the rule.
Definition at line 153 of file Rule.cpp.
References r_right_side.
Referenced by genevalmag::save_right_side_rule().
const bool genevalmag::Rule::belongs_non_terminal (const Symbol & non_term) const
Checks that symbol is a non-terminal into the rule.
Parameters:
non_term
Returns:
Checks that symbol is a non-terminal into the rule.
Definition at line 176 of file Rule.cpp.
References genevalmag::Symbol::equals(), r_left_symbol, and r_right_side.
Referenced by genevalmag::Attr_grammar::add_rule(), and genevalmag::create_instance().
void genevalmag::Rule::copy (const Rule & other) [private]
Method of copy the rule, STL-like C++.
Parameters:
other Method of copy the rule, STL-like C++.
Definition at line 62 of file Rule.cpp.
References get_eqs(), get_left_symbol(), get_offset(), get_right_side(), key(), r_eqs, r_id, r_left_symbol, r_offset, and r_right_side.
Referenced by operator=(), and Rule().
const int genevalmag::Rule::count_non_terminal (const Symbol * symb) const
Returns the count of ocurrences of these symbol in the rule.
Parameters:
symb
Returns:
Returns the count of ocurrences of these symbol in the rule.
Definition at line 318 of file Rule.cpp.
References genevalmag::Symbol::equals(), r_left_symbol, and r_right_side.
Referenced by genevalmag::save_index_ins().
const bool genevalmag::Rule::defined_equation (const Equation & eq) const [private]
Checks that the equation is not already defined in the rule.
Parameters:
eq
Returns:
Checks that the equation is not already defined in the rule.
Definition at line 161 of file Rule.cpp.
References genevalmag::Equation::get_l_value(), and r_eqs.
Referenced by add_eq().
void genevalmag::Rule::destroy () [private]
Method destroy rule, STL-like C++.
Definition at line 74 of file Rule.cpp.
Referenced by operator=(), and ~Rule().
const bool genevalmag::Rule::equals (const Rule & other) const
Compares the rule with other.
Parameters:
other
Returns:
Compares the rule with other.
Definition at line 281 of file Rule.cpp.
References genevalmag::Symbol::equals(), get_left_symbol(), get_right_side(), r_left_symbol, and r_right_side.
const Equation * genevalmag::Rule::get_eq (const unsigned short index) const
Returns the i-equation of the rule.
Parameters:
index
Returns:
Returns the i-equation of the rule.
Definition at line 121 of file Rule.cpp.
References r_eqs.
Referenced by genevalmag::Builder_visit_sequences::gen_visit_seq(), and genevalmag::purge_plan_with().
const map< unsigned short, Equation > & genevalmag::Rule::get_eqs () const
Returns the equations of the rule.
Returns:
Returns the equations of the rule.
Definition at line 97 of file Rule.cpp.
References r_eqs.
Referenced by genevalmag::Attr_grammar::add_rule(), genevalmag::Builder_graphs::compute_dependency_graphs(), and copy().
const Symbol * genevalmag::Rule::get_left_symbol () const
Returns the left symbol of the rule.
Returns:
Returns the left symbol of the rule.
Definition at line 81 of file Rule.cpp.
References r_left_symbol.
Referenced by genevalmag::Attr_grammar::add_rule(), genevalmag::Builder_graphs::compute_dcg(), genevalmag::Builder_graphs::compute_down_graph(), copy(), genevalmag::create_abbreviated_rule(), equals(), genevalmag::Builder_visit_sequences::gen_visit_seq(), genevalmag::generate_expr_text(), genevalmag::Builder_visit_sequences::generate_visit_sequences(), genevalmag::Builder_plans::generates_topological_order(), and genevalmag::Builder_graphs::save_dcg_graphs().
const vector< const Symbol * > genevalmag::Rule::get_non_terminals_right_side () const
Returns the non-terminals symbols the right side of the rule.
Returns:
Returns the non-terminals symbols the right side of the rule.
Definition at line 338 of file Rule.cpp.
References r_right_side.
Referenced by genevalmag::Builder_graphs::compute_adp_graph(), genevalmag::Builder_graphs::compute_dcg(), genevalmag::Builder_graphs::compute_down_graph(), genevalmag::Builder_visit_sequences::gen_visit_seq(), and genevalmag::generate_expr_text().
const size_t genevalmag::Rule::get_number_eqs () const
Returns the number of equations of the rule.
Returns:
Returns the number of equations of the rule.
Definition at line 105 of file Rule.cpp.
References r_eqs.
Referenced by add_eq().
const unsigned short genevalmag::Rule::get_offset () const
Returns the offset of all equation of the rule.
Returns:
Returns the offset of all equation of the rule.
Definition at line 113 of file Rule.cpp.
References r_offset.
Referenced by copy().
const vector< const Symbol * > & genevalmag::Rule::get_right_side () const
Returns the right side of the rule.
Returns:
Returns the right side of the rule.
Definition at line 89 of file Rule.cpp.
References r_right_side.
Referenced by copy(), and equals().
const unsigned short genevalmag::Rule::key () const
Returns the number key that identifies a rule definitely.
 Result = <id_rule>
Returns:
Returns the number key that identifies a rule definitely.
Result = <id_rule>
Definition at line 310 of file Rule.cpp.
References r_id.
Referenced by genevalmag::Builder_graphs::combined_inf_contexts(), genevalmag::Builder_graphs::compute_dcg(), genevalmag::Builder_graphs::compute_dependency_graphs(), and copy().
Rule & genevalmag::Rule::operator= (const Rule & other)
Operator assign(=) of rule.
Parameters:
other
Returns:
Operator assign(=) of rule.
Definition at line 49 of file Rule.cpp.
References copy(), and destroy().
void genevalmag::Rule::set_id (const unsigned short id)
Sets the identificator of the rule.
Parameters:
id Sets the identificator of the rule.
Definition at line 137 of file Rule.cpp.
References r_id.
Referenced by genevalmag::Attr_grammar::add_rule().
void genevalmag::Rule::set_left_symbol (const Symbol * left_symb)
Sets the left symbol of the rule.
Parameters:
left_symb Sets the left symbol of the rule.
Definition at line 145 of file Rule.cpp.
References r_left_symbol.
Referenced by genevalmag::create_abbreviated_rule(), and genevalmag::create_rule().
const string genevalmag::Rule::to_string () const
Generates and returns a string reprensentation of a rule.
 Result = left_symbol `::=` right_side
 `compute`
 eq_1
 ...
 eq_n
 `end;`
 where right_ride is = symbol_1 ` ` ... ` ` symbol_n
Returns:
Generates and returns a string reprensentation of a Rule.
 Result = <left_symbol> `::=` <right_side>
 `compute`
 eq_1
 ...
 eq_n
 `end;`
 where <right_ride> is s= symbol_1 ` ` ... ` ` symbol_n
Definition at line 229 of file Rule.cpp.
References r_eqs, and to_string_not_eqs().
const string genevalmag::Rule::to_string_not_eqs () const
Generates and returns a string reprensentation of a rule.
 Result= left_symbol `::=` right_side `;`
 where right_ride is = symbol_1 ` ` ... ` ` symbol_n
Returns:
Generates and returns a string reprensentation of a rule.
Result = left_symbol `::=` right_side `;`
where right_ride is= symbol_1 ` ` ... ` ` symbol_n
Definition at line 255 of file Rule.cpp.
References genevalmag::Symbol::get_name(), r_id, r_left_symbol, and r_right_side.
Referenced by genevalmag::create_instance(), genevalmag::Builder_graphs::save_adp_graphs(), genevalmag::Builder_plans::save_all_plans(), genevalmag::Builder_plans::save_all_plans_project(), genevalmag::Builder_graphs::save_cyclic_graphs(), genevalmag::Builder_graphs::save_dcg_graphs(), genevalmag::Builder_graphs::save_dp_graphs(), genevalmag::save_rvalue(), and to_string().
Member Data Documentation
genevalmag::Rule::r_eqs [private]
Rule's map of equations.
Definition at line 42 of file Rule.h.
Referenced by add_eq(), copy(), defined_equation(), get_eq(), get_eqs(), get_number_eqs(), and to_string().
genevalmag::Rule::r_id [private]
Rule's identifier.
Definition at line 27 of file Rule.h.
Referenced by copy(), key(), set_id(), and to_string_not_eqs().
genevalmag::Rule::r_left_symbol [private]
Rule's left symbol.
Definition at line 32 of file Rule.h.
Referenced by belongs_non_terminal(), copy(), count_non_terminal(), equals(), get_left_symbol(), set_left_symbol(), and to_string_not_eqs().
genevalmag::Rule::r_offset [private]
Rule's offset.
Definition at line 47 of file Rule.h.
Referenced by add_eq(), copy(), get_offset(), and Rule().
genevalmag::Rule::r_right_side [private]
Rule's vector of right symbols.
Definition at line 37 of file Rule.h.
Referenced by add_right_symbol(), belongs_non_terminal(), copy(), count_non_terminal(), equals(), get_non_terminals_right_side(), get_right_side(), and to_string_not_eqs().
The documentation for this class was generated from the following files:
include/Attr_grammar/Rule.h
src/Attr_grammar/Rule.cpp