genevalmag::Expr_leaf Class Reference
#include <Expr_leaf.h>
Public Member Functions
Expr_leaf ()
virtual ~Expr_leaf ()
virtual string to_string () const =0
bool equals (const Expr_leaf *other) const
Detailed Description
Definition at line 17 of file Expr_leaf.h.
Constructor & Destructor Documentation
genevalmag::Expr_leaf::Expr_leaf ()
Constructor of Expr_leaf.
Returns:
Definition at line 14 of file Expr_leaf.cpp.
genevalmag::Expr_leaf::~Expr_leaf () [virtual]
Destructor of Expr_leaf.
Returns:
Destructor of Expr_leaf.
Definition at line 19 of file Expr_leaf.cpp.
Member Function Documentation
bool genevalmag::Expr_leaf::equals (const Expr_leaf * other) const
Compares the Expr_leaf with other.
Parameters:
other
Returns:
Compares the Expr_leaf with other.
Definition at line 24 of file Expr_leaf.cpp.
References to_string().
Referenced by utilities::return_vertex().
virtual string genevalmag::Expr_leaf::to_string () const [pure virtual]
Generates and returns a string reprensentation of a Expr_leaf.
Returns:
Implements genevalmag::Expression.
Implemented in genevalmag::Expr_instance, and genevalmag::Expr_literal.
Referenced by equals().
The documentation for this class was generated from the following files:
include/Expression_tree/Expr_leaf.h
src/Expression_tree/Expr_leaf.cpp