genevalmag::Builder_graphs Class Reference
#include <Builder_graphs.h>
Public Member Functions
Builder_graphs (const Attr_grammar &attribute_grammar)
~Builder_graphs ()
const map< vector< unsigned short >, Graph > & get_adp_graphs () const
const map< vector< unsigned short >, Graph > & get_cyclic_graphs () const
const Graph & get_dcg_graph (unsigned short index_rule) const
bool compute_dependency_graphs ()
bool compute_down_graph ()
bool compute_dcg ()
bool compute_adp_graph ()
bool check_cyclic_adp_dependencies ()
bool save_all_graphs (const string path_output) const
bool save_cyclic_graphs (const string path_output) const
bool save_dp_graphs (const string path_output) const
bool save_down_graphs (const string path_output) const
bool save_dcg_graphs (const string path_output) const
bool save_adp_graphs (const string path_output) const
Private Member Functions
void compute_attr_vertex ()
void complete_dp_graphs ()
bool combined_inf_contexts (const Rule *rule, Graph &graph, vector< vector< unsigned short > > &inf_context, size_t index_to_combine)
Private Attributes
const Attr_grammar & attr_grammar
References to the attribute grammar.
map< unsigned short, Graph > p_Dp_graphs
Store the DP graphs. The key corresponds to the key Rule..
map< string, Graph > attr_vertex_graphs
Store the vertex-attr graphs. The key corresponds to the key Symbol.
map< string, Graph > p_Down_graphs
Store the down graphs. The key corresponds to the key Symbol.
map< unsigned short, Graph > p_Dcg_graphs
Store the dcg graphs. The key corresponds to the key Rule.
map< vector< unsigned short >, Graph > p_Adp_graphs
Store the adp graphs. The key corresponds to the key Rule with the inferior context.
map< vector< unsigned short >, Graph > p_Adp_subgraphs_cyclics
Store the adp graphs. The key corresponds to the key Rule with the inferior context.
Detailed Description
Definition at line 40 of file Builder_graphs.h.
Constructor & Destructor Documentation
genevalmag::Builder_graphs::Builder_graphs (const Attr_grammar & attribute_grammar)
Constructor empty of Builder graphs.
Parameters:
attribute_grammar
Returns:
Constructor empty of Builder graphs.
Definition at line 56 of file Builder_graphs.cpp.
genevalmag::Builder_graphs::~Builder_graphs ()
Destructor empty of Builder graphs.
Returns:
Destructor empty of Builder graphs.
Definition at line 63 of file Builder_graphs.cpp.
Member Function Documentation
bool genevalmag::Builder_graphs::check_cyclic_adp_dependencies ()
Checks if the graph contains cycle. Utilities a deph-firts-seach for traverse the graphs.
Returns:
Checks if the graph contains cycle. Utilities a deph-firts-seach for traverse the graphs.
Definition at line 444 of file Builder_graphs.cpp.
References p_Adp_graphs, and p_Adp_subgraphs_cyclics.
Referenced by genevalmag::Builder_plans::build_plans().
bool genevalmag::Builder_graphs::combined_inf_contexts (const Rule * rule, Graph & graph, vector< vector< unsigned short > > & inf_context, size_t index_to_combine) [private]
Generate all combinations of the rules and saves a graph ADP for each of them.
Parameters:
rule
graph
inf_context
index_to_combine
Returns:
Generate all combinations of the rules and saves a graph ADP for each of them.
Definition at line 301 of file Builder_graphs.cpp.
References genevalmag::Rule::key(), utilities::merge_graph(), p_Adp_graphs, and p_Dcg_graphs.
Referenced by compute_adp_graph().
void genevalmag::Builder_graphs::complete_dp_graphs () [private]
Completes dp-graph with the vertex of low on instances.
Definition at line 469 of file Builder_graphs.cpp.
References attr_grammar, attr_vertex_graphs, genevalmag::Attr_grammar::get_rules(), utilities::merge_graph(), and p_Dp_graphs.
Referenced by compute_down_graph().
bool genevalmag::Builder_graphs::compute_adp_graph ()
Algorithm ADP Builds the graphs ADP for each rule of the grammar. Ex: ADP(1): (1) E:= E + T. graph G: DP(1) U Dcg E (J1..JN) U Dcg T (K1..KM) Where Ji y ki are rule with left-symbol E and T respectly.
Returns:
Algorithm ADP Builds the graphs ADP for each rule of the grammar. Ex: ADP(1): (1) E:= E + T. graph G: DP(1) U Dcg E (J1..JN) U Dcg T (K1..KM) Where Ji y ki are rule with left-symbol E and T respectly.
Definition at line 360 of file Builder_graphs.cpp.
References attr_grammar, combined_inf_contexts(), genevalmag::current_rule, genevalmag::Rule::get_non_terminals_right_side(), genevalmag::Attr_grammar::get_rules(), genevalmag::Attr_grammar::get_rules_with_left_symbol(), and p_Dp_graphs.
Referenced by genevalmag::Builder_plans::generate_graphs().
void genevalmag::Builder_graphs::compute_attr_vertex () [private]
Builds a graph for each symbol of the grammar with all atributes. The graph only has vertexs. It hasn't edges. Ex: Symbol E ; attributes: s,i graph: vertex: E.s, E.i
Definition at line 155 of file Builder_graphs.cpp.
References attr_grammar, attr_vertex_graphs, genevalmag::Attr_grammar::get_non_terminal_symbols(), p_Dp_graphs, utilities::return_vertex(), genevalmag::Expr_instance::set_attr(), genevalmag::Expr_instance::set_num(), and genevalmag::Expr_instance::set_symb().
Referenced by compute_down_graph().
bool genevalmag::Builder_graphs::compute_dcg ()
Algorithm DCG Builds the graph Dcg for each rule of the grammar. Ex: Dcg E(1) : (1) E:= E + T. graph G: DP(1) U Down(E) U Down(T) Project(G,{attributes of E})
Returns:
Algorithm DCG Builds the graph Dcg for each rule of the grammar. Ex: Dcg E(1) : (1) E:= E + T. graph G: DP(1) U Down(E) U Down(T) Project(G,{attributes of E})
Definition at line 262 of file Builder_graphs.cpp.
References attr_grammar, genevalmag::current_rule, genevalmag::Rule::get_left_symbol(), genevalmag::Rule::get_non_terminals_right_side(), genevalmag::Attr_grammar::get_rules(), genevalmag::Rule::key(), utilities::merge_graph(), p_Dcg_graphs, p_Down_graphs, p_Dp_graphs, and utilities::project_graph().
Referenced by genevalmag::Builder_plans::generate_graphs().
bool genevalmag::Builder_graphs::compute_dependency_graphs ()
Algorithm DP Builds a graph dp for each rule of the grammar. Ex: E:= E + T graph: vertex: E,T Edges: E --> E T---> E
Returns:
Algorithm DP Builds a graph dp for each rule of the grammar. Ex: E:= E + T graph: vertex: E,T Edges: E --> E T---> E
Definition at line 99 of file Builder_graphs.cpp.
References attr_grammar, genevalmag::Rule::get_eqs(), genevalmag::Attr_grammar::get_rules(), genevalmag::Rule::key(), p_Dp_graphs, and utilities::return_vertex().
Referenced by genevalmag::Builder_plans::generate_graphs().
bool genevalmag::Builder_graphs::compute_down_graph ()
Algorithm Down Builds the graphs down for each symbol of the grammar. Ex: Down(E) : (1) E:= E + T. graph G: DP(1) U Down(E) U Down(T) Project(G,{attributes of E})
Returns:
Algorithm Down Builds the graphs down for each symbol of the grammar. Ex: Down(E) : (1) E:= E + T. graph G: DP(1) U Down(E) U Down(T) Project(G,{attributes of E})
Definition at line 201 of file Builder_graphs.cpp.
References attr_grammar, attr_vertex_graphs, complete_dp_graphs(), compute_attr_vertex(), genevalmag::current_rule, genevalmag::Rule::get_left_symbol(), genevalmag::Rule::get_non_terminals_right_side(), genevalmag::Attr_grammar::get_rules(), genevalmag::Symbol::key(), utilities::merge_graph(), p_Down_graphs, p_Dp_graphs, and utilities::project_graph().
Referenced by genevalmag::Builder_plans::generate_graphs().
const map< vector< unsigned short >, Graph > & genevalmag::Builder_graphs::get_adp_graphs () const
Returns the map with all ADP graphs creates.
Returns:
Returns the map with all ADP graphs creates.
Definition at line 70 of file Builder_graphs.cpp.
References p_Adp_graphs.
Referenced by genevalmag::Builder_plans::generate_plans().
const map< vector< unsigned short >, Graph > & genevalmag::Builder_graphs::get_cyclic_graphs () const
Returns the map with all ADP with cycle graphs creates.
Returns:
Returns the map with all ADP graphs creates.
Definition at line 78 of file Builder_graphs.cpp.
References p_Adp_subgraphs_cyclics.
const Graph & genevalmag::Builder_graphs::get_dcg_graph (unsigned short index_rule) const
Returns the down graph of the symbol.
Parameters:
index_rule
Returns:
Returns the down graph of the symbol.
Definition at line 86 of file Builder_graphs.cpp.
References p_Dcg_graphs.
Referenced by genevalmag::Builder_plans::generate_plans().
bool genevalmag::Builder_graphs::save_adp_graphs (const string path_output) const
Saves all adp-graphs generates
Parameters:
path_output
Returns:
Saves all adp-graphs generates.
Definition at line 570 of file Builder_graphs.cpp.
References attr_grammar, utilities::clean_output_folder(), utilities::cleaning_tabs(), genevalmag::FILE_ADP_GRAPH(), utilities::generate_names_instance(), genevalmag::Attr_grammar::get_rules(), p_Adp_graphs, genevalmag::PATH_OUTPUT_ADP(), utilities::print_graph(), genevalmag::Rule::to_string_not_eqs(), and utilities::write_inf_context().
Referenced by save_all_graphs().
bool genevalmag::Builder_graphs::save_all_graphs (const string path_output) const
Saves all graphs generates: DP, Down, DCG and ADP.
Parameters:
path_output
Returns:
Saves all graphs generates: DP, Down, DCG and ADP.
Definition at line 602 of file Builder_graphs.cpp.
References utilities::clean_output_folder(), genevalmag::PATH_OUTPUT_GRAPHS(), save_adp_graphs(), save_dcg_graphs(), save_down_graphs(), and save_dp_graphs().
Referenced by genevalmag::Builder_plans::save_all_graphs().
bool genevalmag::Builder_graphs::save_cyclic_graphs (const string path_output) const
Saves all graphs graph cycles.
Parameters:
path_output
Returns:
Definition at line 620 of file Builder_graphs.cpp.
References attr_grammar, utilities::clean_output_folder(), utilities::cleaning_tabs(), genevalmag::FILE_ADP_SUBGRAPH_CYCLIC(), utilities::generate_names_instance(), genevalmag::Attr_grammar::get_rules(), p_Adp_subgraphs_cyclics, genevalmag::PATH_OUTPUT_CYCLIC(), genevalmag::PATH_OUTPUT_GRAPHS(), utilities::print_graph(), genevalmag::Rule::to_string_not_eqs(), and utilities::write_inf_context().
Referenced by genevalmag::Builder_plans::save_cyclic_graphs().
bool genevalmag::Builder_graphs::save_dcg_graphs (const string path_output) const
Saves all dcg-graphs generates
Parameters:
path_output
Returns:
Saves all dcg-graphs generates.
Definition at line 540 of file Builder_graphs.cpp.
References attr_grammar, utilities::clean_output_folder(), utilities::cleaning_tabs(), genevalmag::current_rule, genevalmag::FILE_DCG_GRAPH(), utilities::generate_names_instance(), genevalmag::Rule::get_left_symbol(), genevalmag::Symbol::get_name(), genevalmag::Attr_grammar::get_rules(), p_Dcg_graphs, genevalmag::PATH_OUTPUT_DCG(), utilities::print_graph(), and genevalmag::Rule::to_string_not_eqs().
Referenced by save_all_graphs().
bool genevalmag::Builder_graphs::save_down_graphs (const string path_output) const
Saves all down-graphs generates
Parameters:
path_output
Returns:
Saves all down-graphs generates.
Definition at line 514 of file Builder_graphs.cpp.
References utilities::clean_output_folder(), genevalmag::FILE_DOWN_GRAPH(), utilities::generate_names_attr(), p_Down_graphs, genevalmag::PATH_OUTPUT_DOWN(), and utilities::print_graph().
Referenced by save_all_graphs().
bool genevalmag::Builder_graphs::save_dp_graphs (const string path_output) const
Saves all dp-graphs generates
Parameters:
path_output
Returns:
Saves all dp-graphs generates
Definition at line 486 of file Builder_graphs.cpp.
References attr_grammar, utilities::clean_output_folder(), utilities::cleaning_tabs(), genevalmag::current_rule, genevalmag::FILE_DP_GRAPH(), utilities::generate_names_instance(), genevalmag::Attr_grammar::get_rules(), p_Dp_graphs, genevalmag::PATH_OUTPUT_DP(), utilities::print_graph(), and genevalmag::Rule::to_string_not_eqs().
Referenced by save_all_graphs().
Member Data Documentation
genevalmag::Builder_graphs::attr_grammar [private]
References to the attribute grammar.
Definition at line 47 of file Builder_graphs.h.
Referenced by complete_dp_graphs(), compute_adp_graph(), compute_attr_vertex(), compute_dcg(), compute_dependency_graphs(), compute_down_graph(), save_adp_graphs(), save_cyclic_graphs(), save_dcg_graphs(), and save_dp_graphs().
genevalmag::Builder_graphs::attr_vertex_graphs [private]
Store the vertex-attr graphs. The key corresponds to the key Symbol.
Definition at line 58 of file Builder_graphs.h.
Referenced by complete_dp_graphs(), compute_attr_vertex(), and compute_down_graph().
genevalmag::Builder_graphs::p_Adp_graphs [private]
Store the adp graphs. The key corresponds to the key Rule with the inferior context.
Definition at line 74 of file Builder_graphs.h.
Referenced by check_cyclic_adp_dependencies(), combined_inf_contexts(), get_adp_graphs(), and save_adp_graphs().
genevalmag::Builder_graphs::p_Adp_subgraphs_cyclics [private]
Store the adp graphs. The key corresponds to the key Rule with the inferior context.
Definition at line 79 of file Builder_graphs.h.
Referenced by check_cyclic_adp_dependencies(), get_cyclic_graphs(), and save_cyclic_graphs().
genevalmag::Builder_graphs::p_Dcg_graphs [private]
Store the dcg graphs. The key corresponds to the key Rule.
Definition at line 69 of file Builder_graphs.h.
Referenced by combined_inf_contexts(), compute_dcg(), get_dcg_graph(), and save_dcg_graphs().
genevalmag::Builder_graphs::p_Down_graphs [private]
Store the down graphs. The key corresponds to the key Symbol.
Definition at line 63 of file Builder_graphs.h.
Referenced by compute_dcg(), compute_down_graph(), and save_down_graphs().
genevalmag::Builder_graphs::p_Dp_graphs [private]
Store the DP graphs. The key corresponds to the key Rule..
Definition at line 53 of file Builder_graphs.h.
Referenced by complete_dp_graphs(), compute_adp_graph(), compute_attr_vertex(), compute_dcg(), compute_dependency_graphs(), compute_down_graph(), and save_dp_graphs().
The documentation for this class was generated from the following files:
include/Builders/Builder_graphs.h
src/Builders/Builder_graphs.cpp