src/maggen.cpp File Reference
Tool for Generation of Static Evaluators for Multi-plans Attribute Grammars.
#include <stdio.h>
#include <iostream>
#include <fstream>
#include <string>
#include <time.h>
#include <sys/time.h>
#include <sys/stat.h>
#include <boost/tokenizer.hpp>
#include `../include/Maglib.h`
Namespaces
namespace genevalmag
Functions
const string genevalmag::DEFAULT_PATH (`./out_maggen/`)
const string genevalmag::DEFAULT_FILE_NAME (`mag_eval`)
const string genevalmag::DEFAULT_INPUT_FILE (`/tmp/.input_maggen_default`)
double genevalmag::timeval_diff (struct timeval *a, struct timeval *b)
bool genevalmag::check_file_exist (const string &strFilename)
bool genevalmag::check_name (const string &strFilename)
void genevalmag::show_help_information ()
bool genevalmag::parse_parameters (int argc, char *argv[], string &path_input_file, string &path_folder_output, string &name_library, vector< string > &headers)
int main (int argc, char *argv[], char *envp[])
Detailed Description
Tool for Generation of Static Evaluators for Multi-plans Attribute Grammars.
.
Date: 09/02/2010
Author: Kilmurray, Gerardo Luis <gerakilmurray@gmail.com>
Picco, Gonzalo Martín <gonzalopicco@gmail.com>
Definition in file maggen.cpp.
Function Documentation
int main (int argc, char * argv[], char * envp[])
Main method of the parsing.
Definition at line 235 of file maggen.cpp.
References genevalmag::DEFAULT_FILE_NAME(), genevalmag::DEFAULT_INPUT_FILE(), genevalmag::DEFAULT_PATH(), genevalmag::Maglib::gen_evaluator(), genevalmag::parse_parameters(), genevalmag::show_help_information(), and genevalmag::timeval_diff().