utilities Namespace Reference
Functions
bool create_folder (const string path)
bool clean_output_folder (const string path)
bool copy_static_code (const string path)
void generate_names_instance (const Graph &graph, string datas[], size_t size_d)
void generate_names_attr (const Graph &graph, string datas[], size_t size_d)
void print_graph (const Graph &graph, const string path, const string name_file, const string name_graph, const string names[], string shape_vertex)
void print_graph_txt (const Graph &graph)
Vertex return_vertex (const Graph &graph, const Expr_leaf *node)
void merge_graph (const Graph &graph1, const Graph &graph2, Graph &graph_merged)
void project_graph (const Symbol *symb, Graph &graph)
string cleaning_tabs (const string str)
string write_inf_context (const vector< unsigned short > &context_vec)
bool belong_index (const unsigned short &index, const vector< unsigned short > &vec)
Function Documentation
bool utilities::belong_index (const unsigned short & index, const vector< unsigned short > & vec)
Seachs a index in a vector.
Parameters:
index
vec
Returns:
Definition at line 234 of file Utilities.cpp.
Referenced by genevalmag::Builder_visit_sequences::gen_visit_seq(), genevalmag::Builder_visit_sequences::generate_visit_sequences(), genevalmag::plan_family_computed(), and genevalmag::purge_plan_with().
bool utilities::clean_output_folder (const string path)
Remove and create the output folder of files .dot and .png.
Parameters:
path
Returns:
Remove and create the output folder of files .dot and .png.
Definition at line 41 of file Utilities.cpp.
References create_folder().
Referenced by genevalmag::Maglib::gen_evaluator(), genevalmag::Builder_graphs::save_adp_graphs(), genevalmag::Builder_graphs::save_all_graphs(), genevalmag::Builder_plans::save_all_plans(), genevalmag::Builder_plans::save_all_plans_project(), genevalmag::Builder_graphs::save_cyclic_graphs(), genevalmag::Builder_graphs::save_dcg_graphs(), genevalmag::Builder_graphs::save_down_graphs(), and genevalmag::Builder_graphs::save_dp_graphs().
string utilities::cleaning_tabs (const string str)
Remove tabs and replace for spaces.
Parameters:
str
Returns:
Remove tabs and replace for spaces.
Definition at line 249 of file Utilities.cpp.
Referenced by genevalmag::create_instance(), genevalmag::Builder_code::generate_all_methods_eqs(), genevalmag::Builder_graphs::save_adp_graphs(), genevalmag::Builder_plans::save_all_plans(), genevalmag::Builder_plans::save_all_plans_project(), genevalmag::Builder_graphs::save_cyclic_graphs(), genevalmag::Builder_graphs::save_dcg_graphs(), genevalmag::Builder_graphs::save_dp_graphs(), and genevalmag::save_rvalue().
bool utilities::copy_static_code (const string path)
Copies the static file to the generation path.
Parameters:
path
Returns:
Copies the static file to the generation path.
Definition at line 57 of file Utilities.cpp.
Referenced by genevalmag::Builder_code::generate_code().
bool utilities::create_folder (const string path)
Create the folder passed as parameter.
Parameters:
path
Returns:
Create the folder passed as parameter.
Definition at line 26 of file Utilities.cpp.
Referenced by clean_output_folder().
void utilities::generate_names_attr (const Graph & graph, string datas[], size_t size_d)
Generates the names of vertex for down graph. (The vertex's name is an attribute).
Parameters:
graph
datas
size_d Generates the names of vertex for down graph. (The vertex's name is an attribute).
Definition at line 87 of file Utilities.cpp.
Referenced by genevalmag::Builder_graphs::save_down_graphs().
void utilities::generate_names_instance (const Graph & graph, string datas[], size_t size_d)
Generates the names of vertex. (The vertex's name is an instance).
Parameters:
graph
datas
size_d Generates the names of vertex. (The vertex's name is an instance).
Definition at line 74 of file Utilities.cpp.
Referenced by genevalmag::Builder_graphs::save_adp_graphs(), genevalmag::Builder_graphs::save_cyclic_graphs(), genevalmag::Builder_graphs::save_dcg_graphs(), and genevalmag::Builder_graphs::save_dp_graphs().
void utilities::merge_graph (const Graph & graph1, const Graph & graph2, Graph & graph_merged)
Joins graph1 and graph2 in graph_merged.
Parameters:
graph1
graph2
graph_merged Joins graph1 and graph2 in graph_merged.
Definition at line 175 of file Utilities.cpp.
References return_vertex().
Referenced by genevalmag::Builder_graphs::combined_inf_contexts(), genevalmag::Builder_graphs::complete_dp_graphs(), genevalmag::Builder_graphs::compute_dcg(), and genevalmag::Builder_graphs::compute_down_graph().
void utilities::print_graph (const Graph & graph, const string path, const string name_file, const string name_graph, const string names[], string shape_vertex)
Prints a graph in a file .dot for generate image .spng.
Parameters:
graph
path
name_file
name_graph
names
shape_vertex Prints a graph in a file .dot for generate image .spng.
Definition at line 101 of file Utilities.cpp.
Referenced by genevalmag::Builder_graphs::save_adp_graphs(), genevalmag::Builder_plans::save_all_plans(), genevalmag::Builder_plans::save_all_plans_project(), genevalmag::Builder_graphs::save_cyclic_graphs(), genevalmag::Builder_graphs::save_dcg_graphs(), genevalmag::Builder_graphs::save_down_graphs(), and genevalmag::Builder_graphs::save_dp_graphs().
void utilities::print_graph_txt (const Graph & graph)
Prints a graph in the standart output (std:cout).
Parameters:
graph Prints a graph in the standart output (std:cout).
Definition at line 136 of file Utilities.cpp.
void utilities::project_graph (const Symbol * symb, Graph & graph)
Projects a graph with only vertex that belongs to symbol `symb`. Modifies the parameter `graph`.
Parameters:
symb
graph Projects a graph with only vertex that belongs to symbol `symb`. Modifies the parameter `graph`.
Definition at line 215 of file Utilities.cpp.
References genevalmag::Symbol::equals(), genevalmag::Expr_instance::get_num(), and genevalmag::Expr_instance::get_symb().
Referenced by genevalmag::Builder_graphs::compute_dcg(), and genevalmag::Builder_graphs::compute_down_graph().
Vertex utilities::return_vertex (const Graph & graph, const Expr_leaf * node)
Given a graph and node, returns the vertex descriptor of node in the graph. If not search it, so returns USHRT_MAX.
Parameters:
graph
node
Returns:
Given a graph and node, returns the vertex descriptor of node in the graph. If not search it, so returns USHRT_MAX.
Definition at line 161 of file Utilities.cpp.
References genevalmag::Expr_leaf::equals().
Referenced by genevalmag::Builder_graphs::compute_attr_vertex(), genevalmag::Builder_graphs::compute_dependency_graphs(), genevalmag::Builder_plans::compute_order(), genevalmag::cycle_detector::examine_edge(), and merge_graph().
string utilities::write_inf_context (const vector< unsigned short > & context_vec)
Writes inferior contex in a string and returns it.
Parameters:
context_vec
Returns:
Definition at line 259 of file Utilities.cpp.
Referenced by genevalmag::Builder_graphs::save_adp_graphs(), genevalmag::Builder_plans::save_all_plans(), genevalmag::Builder_plans::save_all_plans_project(), and genevalmag::Builder_graphs::save_cyclic_graphs().