genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT > Struct Template Reference
Public Types
typedef rule< ScannerT > rule_exp
typedef rule< typename lexeme_scanner< ScannerT >::type > rule_lexeme
Public Member Functions
definition (attritute_grammar const &self)
rule_exp const & start () const
Public Attributes
symbols st_sorts
symbols st_op_prefix
symbols st_op_infix
symbols st_op_postfix
symbols st_functions
symbols st_attributes
symbols st_non_terminal
rule_exp r_reserved_word
rule_exp r_cpp_reserved_words
rule_exp r_cpp_basic_types
rule_exp r_ident
rule_exp r_oper
rule_exp r_char
rule_exp r_string
rule_exp r_boolean
rule_lexeme r_id_op
rule_lexeme r_string_lit
rule_lexeme r_esc_seq
rule_exp r_semantic_domain
rule_exp r_bloq_sem
rule_exp r_decl_sort
rule_exp r_decl_oper
rule_exp r_decl_func
rule_exp r_oper_assoc
rule_exp r_oper_mode
rule_exp r_oper_prefix
rule_exp r_oper_infix
rule_exp r_oper_postfix
rule_exp r_dom_func
rule_exp r_attributes
rule_exp r_decl_attr
rule_exp r_type_attr
rule_exp r_conj_symb
rule_exp r_rules
rule_exp r_decl_rule
rule_exp r_equation
rule_exp r_right_rule
rule_exp r_terminal
rule_exp r_compute_eq
rule_exp r_expression
rule_exp r_expr_prime
rule_exp r_expr_prime_prime
rule_exp r_function
rule_exp r_literal
rule_exp r_instance
rule_exp r_sort_st
rule_exp r_op_prefix_st
rule_exp r_op_infix_st
rule_exp r_op_postfix_st
rule_exp r_function_st
rule_exp r_attribute_st
rule_exp r_non_term_st
rule_exp r_sort_stable
rule_exp r_att_grammar
Detailed Description
template<typename ScannerT> struct genevalmag::attritute_grammar::definition< ScannerT >
Definition at line 95 of file Parser_AG.cpp.
Member Typedef Documentation
template<typename ScannerT > typedef rule<ScannerT> genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::rule_exp
Definition at line 354 of file Parser_AG.cpp.
template<typename ScannerT > typedef rule<typename lexeme_scanner<ScannerT>::type> genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::rule_lexeme
Definition at line 357 of file Parser_AG.cpp.
Constructor & Destructor Documentation
template<typename ScannerT > genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition (attritute_grammar const & self) [inline]
Definition at line 97 of file Parser_AG.cpp.
References genevalmag::add_attribute(), genevalmag::add_function(), genevalmag::add_operator(), genevalmag::check_well_defined(), genevalmag::create_abbreviated_rule(), genevalmag::create_attributes(), genevalmag::create_bool(), genevalmag::create_equation(), genevalmag::create_func_node(), genevalmag::create_function(), genevalmag::create_instance(), genevalmag::create_instance_node(), genevalmag::create_lit_ch(), genevalmag::create_lit_number(), genevalmag::create_lit_str(), genevalmag::create_literal_node(), genevalmag::create_new_non_terminal(), genevalmag::create_new_terminal(), genevalmag::create_operator(), genevalmag::create_root_function_node(), genevalmag::create_root_infix_node(), genevalmag::create_root_postfix_node(), genevalmag::create_root_prefix_node(), genevalmag::create_rule(), genevalmag::create_sort(), genevalmag::decrement_level(), genevalmag::increment_level(), genevalmag::inic_func(), genevalmag::push_mark(), genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_att_grammar, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_attribute_st, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_attributes, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_bloq_sem, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_boolean, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_char, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_compute_eq, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_conj_symb, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_cpp_basic_types, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_cpp_reserved_words, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_decl_attr, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_decl_func, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_decl_oper, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_decl_rule, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_decl_sort, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_dom_func, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_equation, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_esc_seq, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_expr_prime, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_expr_prime_prime, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_expression, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_function, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_function_st, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_id_op, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_ident, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_instance, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_literal, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_non_term_st, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_op_infix_st, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_op_postfix_st, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_op_prefix_st, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_oper, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_oper_assoc, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_oper_infix, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_oper_mode, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_oper_postfix, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_oper_prefix, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_reserved_word, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_right_rule, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_rules, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_semantic_domain, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_sort_st, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_string, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_string_lit, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_terminal, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_type_attr, genevalmag::save_assoc_op(), genevalmag::save_attr_ins(), genevalmag::save_domain_func(), genevalmag::save_image_func(), genevalmag::save_index_ins(), genevalmag::save_member_list_attr(), genevalmag::save_mode_op(), genevalmag::save_name_func(), genevalmag::save_prec_op(), genevalmag::save_right_side_rule(), genevalmag::save_rule(), genevalmag::save_rvalue(), genevalmag::save_sort_attr(), genevalmag::save_type_attr(), genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::st_attributes, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::st_functions, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::st_non_terminal, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::st_op_infix, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::st_op_postfix, genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::st_op_prefix, and genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::st_sorts.
Member Function Documentation
template<typename ScannerT > rule_exp const& genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::start () const [inline]
Definition at line 388 of file Parser_AG.cpp.
References genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_att_grammar.
Member Data Documentation
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_att_grammar
Definition at line 386 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition(), and genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::start().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_attribute_st
Definition at line 382 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_attributes
Definition at line 371 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_bloq_sem
Definition at line 366 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_boolean
Definition at line 360 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_char
Definition at line 360 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_compute_eq
Definition at line 374 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_conj_symb
Definition at line 371 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_cpp_basic_types
Definition at line 360 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_cpp_reserved_words
Definition at line 360 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_decl_attr
Definition at line 371 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_decl_func
Definition at line 366 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_decl_oper
Definition at line 366 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_decl_rule
Definition at line 374 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_decl_sort
Definition at line 366 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_dom_func
Definition at line 366 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_equation
Definition at line 374 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_lexeme genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_esc_seq
Definition at line 363 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_expr_prime
Definition at line 378 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_expr_prime_prime
Definition at line 378 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_expression
Definition at line 378 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_function
Definition at line 378 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_function_st
Definition at line 382 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_lexeme genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_id_op
Definition at line 363 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_ident
Definition at line 360 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_instance
Definition at line 378 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_literal
Definition at line 378 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_non_term_st
Definition at line 382 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_op_infix_st
Definition at line 382 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_op_postfix_st
Definition at line 382 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_op_prefix_st
Definition at line 382 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_oper
Definition at line 360 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_oper_assoc
Definition at line 366 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_oper_infix
Definition at line 366 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_oper_mode
Definition at line 366 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_oper_postfix
Definition at line 366 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_oper_prefix
Definition at line 366 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_reserved_word
Definition at line 360 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_right_rule
Definition at line 374 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_rules
Definition at line 374 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_semantic_domain
Definition at line 366 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_sort_st
Definition at line 382 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_sort_stable
Definition at line 382 of file Parser_AG.cpp.
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_string
Definition at line 360 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_lexeme genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_string_lit
Definition at line 363 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_terminal
Definition at line 374 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > rule_exp genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::r_type_attr
Definition at line 371 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > symbols genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::st_attributes
Definition at line 348 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > symbols genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::st_functions
Definition at line 347 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > symbols genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::st_non_terminal
Definition at line 349 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > symbols genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::st_op_infix
Definition at line 345 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > symbols genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::st_op_postfix
Definition at line 346 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > symbols genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::st_op_prefix
Definition at line 344 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
template<typename ScannerT > symbols genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::st_sorts
Definition at line 343 of file Parser_AG.cpp.
Referenced by genevalmag::attritute_grammar::attritute_grammar::definition< ScannerT >::definition().
The documentation for this struct was generated from the following file:
src/Parser/Parser_AG.cpp